### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by wagafo** [soimort/translate-shell#10]
Does not work for me, it just waits forever after entering the command. 

Can it be that I'm behing a proxy? Should it work behind a proxy?

**Comment by soimort** [comment]
No, to the best of my knowledge, GNU awk does not respect system proxy settings.

That means you can't use it with a proxy.

**Comment by awesom3o** [comment]
same issue here,latest version of gawk is installed,same result in bash and zsh,and not using a proxy.

**Comment by agentOfChaos** [comment]
I had the same issue, solved replacing line 61 in translate.awk:
from: `print "GET " url |& httpService`
to: `print "GET " url " HTTP/1.0\r\n" |& httpService`
(I didn't test it with a proxy though)
