### ISSUE TITLE
Option to not query for translation when using Text-to-Speech

### ISSUE THREAD

**Issue by admirabilis** [soimort/translate-shell#100]
Hello, @soimort!

If I just want to listen to the pronunciation of some word or sentence, I know I can use the option `-speak` (`-sp`), but before speaking the text, translate-shell queries for a translation of the text, which causes a noticeable delay.

What I would like is an option to skip the translation (eg. `-no-translate`) and just call the text-to-speech function, that would speed things up for me when I just want to hear the correct pronunciation of a text, which I do very often!

Thank you for your attention!

**Comment by soimort** [comment]
I think it's a good idea :+1:

**Comment by admirabilis** [comment]
This is awesome! Thank you!
