### ISSUE TITLE
Adding an option to disable the use of FriBidi?

### ISSUE THREAD

**Issue by bjesus** [soimort/translate-shell#101]
I'm using translate-shell as a translator to Hebrew. The support of FriBidi allows me to use it in the terminal and still read the text correctly, which is great. The problem is that when I try to use the output elsewhere, on places that support RTL in first place - the translation is written backwards because FriBidi reverses it for the terminal.

Is there anyway to disable this behavior? I've tried piping the output, using an output file - still FriBidi  makes the text goes backward.

Does an option like this exists and I'm just missing it?

Thanks!

**Comment by soimort** [comment]
Thanks for the suggestion. There's now a `-no-bidi` option, which should allow you to disable the use of FriBidi.

**Comment by bjesus** [comment]
Amazing, thank you!
