### ISSUE TITLE
Display translation language in brief mode.

### ISSUE THREAD

**Issue by biodranik** [soimort/translate-shell#102]
It's hard to understand which language is it when launching `trans -b {en:ru+uk+es+...} word`
Would be very convenient to have an option to see output like

```
ru:слово
uk:word_in_ukrainian
es:word_in_spanish
...
```

**Comment by soimort** [comment]
The whole point of using brief mode is to display _the closest translation_ alone, and _nothing more_. Users should already be informed of the languages they would like to translate to, e.g., the 1st line is for `ru`, the 2nd line is for `uk`, as they're shown clearly in the command-line.

If you want more information, the proper solution is to use verbose mode.
