### ISSUE TITLE
Error: doesn't work with "do shell script" in an AppleScript

### ISSUE THREAD

**Issue by JayBrown** [soimort/translate-shell#104]
Example (AppleScript for language identification):
set theLanguage to (do shell script /usr/local/bin/trans -no-ansi -identify " & quoted form of theText)

That doesn't work, I only get: error "Application got an error: /usr/local/bin/trans: line 4738: gawk: command not found" number 127

I assume it's because AppleScript uses the sh, and trans wants zsh or bash. When I run the command directly in my zsh, or in bash, or from within a shell script, everything's fine, because /usr/local/bin is in my path system wide, and I have installed gawk.

I tried adding "bash -c" to the beginning of the above do shell script line… didn't work. Also tried adding "export PATH='/usr/local/bin;$PATH';" to the beginning of the do shell script line… didn't work either. When adding just "export PATH='/usr/local/bin';" the AppleScript does run the trans command, but eventually has errors too, e.g. "sh: rev: command not found" and "sh: hexdump: command not found".

Any way out of this AppleScript/sh mess?

PS: Of course I can always symlink gawk from the Cellar into /usr/bin, and then it also works with AppleScript, but that's not an elegant solution. Want to keep the extra binaries in /usr/local/bin.

**Comment by JayBrown** [comment]
Okay, you can lock the issue. Found the solution myself. The problem is that in sh the export PATH command needs a slightly different syntax than in bash or zsh. Run an AppleScript command like this, and everything seems to work fine:

do shell script "export PATH=\"/usr/local/bin:$PATH\";/usr/local/bin/trans -no-ansi -show-original n -identify " & quoted form of theText

Maybe there's yet a different way to do it—if yes, please post it here—, but the above works well for me.

**Comment by soimort** [comment]
Or you could just close the issue yourself: )

I had no experience with AppleScript at all, so if someone (perhaps using
trans with AppleScript on a daily basis) can take some leisure time to
write up a wiki page, that would be very welcome.

**Comment by JayBrown** [comment]
I've quickly edited a wiki page incl. two examples and a note about symlinking gawk.

https://github.com/soimort/translate-shell/wiki
https://github.com/soimort/translate-shell/wiki/AppleScript

**Comment by soimort** [comment]
Cool :+1: , thanks!

**Comment by JayBrown** [comment]
No, sir, _we_ must thank _you_ for this great software. :)
