### ISSUE TITLE
Hi, file socket support ? *un

### ISSUE THREAD

**Issue by ghost** [soimort/translate-shell#107]
good idea support network/file socket for input and output, or/and fifo file..

**Comment by soimort** [comment]
Could you please elaborate a bit on this issue?

It seems `stdin`/`stdout` should suffice, in any case – you may redirect them to/from anywhere as you like (POSIX sockets, files, etc.). If you know what a [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) is, the best way to achieve this is by concatenating tools together, not by creating a single tool to handle everything (immaturely).

**Comment by ghost** [comment]
I agree, maybe sockets are not the best idea. Now I look in the direction of D-Bus for accessing transditertsii no apparent relation to translation API.
It would be desirable to have a user-friendly interface to access the word translations from C/C++ code.

**Comment by soimort** [comment]
Not sure what you are trying to achieve, but this tool was not designed to be a library (nor it is a "free API wrapper" to Google Translate), not to mention C/C++. You may fork it like a normal (child) process which gives you stdin/stdout access, and that's all we should have.

Hint: If you want a user-friendly interface that much, you may consider [Google's official API](https://cloud.google.com/translate/) (and according to Google's TOS, that's the only legit way of using it).
