### ISSUE TITLE
Antigen: Can't source file / path problem

### ISSUE THREAD

**Issue by GuillaumeSeren** [soimort/translate-shell#109]
Hi,
installing the project by antigen, adding to my zshrc:
antigen bundle soimort/translate-shell

Then antigen update, after trying to call a translation:
trans 'Saluton, Mondo!'
gawk: translate.awk:3: error: can't open source file `metainfo' for reading (No such file or directory)

I think the problem come from the path of the file, like:
@include "metainfo"

So basically it break the install on antigen, did anyone experienced this behavior ?

**Comment by soimort** [comment]
Which version of `gawk` are you using?

(If you install from antigen, gawk 4.1 is prerequisite)

**Comment by GuillaumeSeren** [comment]
Ah didn't see that I used gawk-4.0.2, upgrading to 4.1.2 fix the problem, thank you !
:thumbsup:
