### ISSUE TITLE
Does not work under shells where {} are interpreted

### ISSUE THREAD

**Issue by wagafo** [soimort/translate-shell#11]
If the shell is of the csh type it doesn't work because {} is interpreted.

**Comment by soimort** [comment]
hmm, I wasn't aware of csh compatibility. Curly braces are supposed to work well on bash and zsh.
In csh, you have to use single or double quotes, e.g.,

``` sh
% trs '{=fr}' hallo
```

**Comment by a1ip** [comment]
For **fish shell** you can use such function:

``` fish
function trs --description 'Google translate'
    translate \{$argv[1]\} $argv[2..(count $argv)]
end
```

It works good for me.

**Comment by soimort** [comment]
@a1ip Thanks for the tip! will add it to the README.

**Comment by a1ip** [comment]
``` bash
function trs --description 'Google translate'
    if test (count $argv) -gt 1
        translate \{$argv[1]\} $argv[2..(count $argv)] | gawk '{gsub(/^({+\s+)+/, "")};1' | gawk '{gsub(/\s+}+$/, "")};1'
    else
        translate $argv
    end
end
```

I've added some improvement correcting defect of adding excess curly braces with translation of the first argument in such cases as when user uses more then one string to translate but omits language parameters at all.
And it looks like a mess now.

**Comment by soimort** [comment]
We have a better support for **csh**, **ksh** and **fish** now, so no more workaround needed in those shells.

Furthermore, you can write language parameters either with or without brackets:

```
% ./translate {=@ja} hello
% ./translate =@ja hello
```
