### ISSUE TITLE
output in terminal

### ISSUE THREAD

**Issue by fratcn** [soimort/translate-shell#112]
ESC[1mwhile you all put your idle units at front they attacked meESC[22m

[ ESC[4mEnglishESC[24m -> ESC[1mEnglishESC[22m ](END)

lots of ESC[1m and ESC[22m symbols etc.

**Comment by soimort** [comment]
Please explain your issue in more details - I'm not sure what environment you're in, and what exact problem you're reporting.

**Comment by fratcn** [comment]
archlinux,zsh:

$trans -t de 'while you all put your idle units at front they attacked me'
$while you all put your idle units at front they attacked me

   ESC[1mwährend Sie alle Ihre im Leerlauf Einheiten vorne setzte sie mich angegriffenESC[22m

   [ ESC[4mEnglishESC[24m -> ESC[1mDeutschESC[22m ]
   (END)

**Comment by fratcn** [comment]
sorry,i get it,the view problem.thank u
