### ISSUE TITLE
Strange translations

### ISSUE THREAD

**Issue by SPDEX** [soimort/translate-shell#114]
If you translate this some texts you get strange results, there are more translations like this with Www.Booked.cz but I didn't know how to reproduce that, maybe they have the same cause.

`"./trans" -b en:hu ".. --<br>... -- " = ".. - Www.Booked.hu... -"`
`"./trans" -b af:en ", <br>" = ", Dictionary"`
`"./trans" -b sk:en ", <br>" = ", Photo"`

**Comment by soimort** [comment]
That's exactly what you will get on Google Translate.

![screenshot from 2016-04-07 06-27-41](https://cloud.githubusercontent.com/assets/342945/14340658/fb18eb9c-fc89-11e5-96cf-d189f5a5a381.png)

So, nope, it's not something that I can fix : )
