### ISSUE TITLE
make install on OSX requires ginstall to use -D option or removal of -D

### ISSUE THREAD

**Issue by LaurentFough** [soimort/translate-shell#115]
- `make install` on OSX requires GNU install (ginstall) to be available for a clean install with the default Makefile. The "-D" option is not available on OSX.
  Install coreutils via Homebrew works.
- Alternatively removing the "-D" option from the "@install" works as expected.
# Note:
- using "-d" (lowercase) with the standard OS X install also breaks the install.

**Comment by soimort** [comment]
I'd recommend OS X users to install via brew. I'm pretty sure `install -D` is GNU specific and incompatible with BSD / OS X's install, but I don't know of a one-command solution which will cover both systems.

On OS X you could as well use `-d` to achieve the same (creating parent paths), so the fix might be trivial (requires two `install` invokes).

**Comment by LaurentFough** [comment]
We could add this bit of information to the docs, as a nice little FYI.

**Comment by soimort** [comment]
Thanks for the suggestion :+1: Will add it to README.
