### ISSUE TITLE
Empty output using the Ubuntu deb package

### ISSUE THREAD

**Issue by orschiro** [soimort/translate-shell#116]
Dear all, 

Thanks for all your efforts for this great package!

I installed the Ubuntu deb package version `0.8.23-1` directly from the repositories.

However, running the README examples lead to an empty output:

![image](https://cloud.githubusercontent.com/assets/170947/14631689/f12b838a-0614-11e6-8737-07625ee39e2d.png)

Any idea why this might be?

Thankfully,

~Robert

**Comment by soimort** [comment]
0.8.23 is **very outdated** and does not function anymore. Just use the latest version here.

**Comment by orschiro** [comment]
Thank you @soimort!

I will raise this concern on the Ubuntu Bugtracker:

https://bugs.launchpad.net/ubuntu/+source/translate-shell/+bug/1572035

Thankfully,

~Robert
