### ISSUE TITLE
Crash on attempt to translate big file (200k lines)

### ISSUE THREAD

**Issue by ryukinix** [soimort/translate-shell#118]
``` python-traceback
[lerax@starfox Desktop]$ trans en:pt -b -i questions-words.txt -o questions-words-pt-br.txt
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(
gawk: /dev/fd/63:522: fatal: cannot open pipe `echo 'Bamako Mali Canberra Australia' | hexdump -v -e'1/1 "%03u" " "'' (Too many open files)
```

data: [questions-words.txt](https://trello-attachments.s3.amazonaws.com/56f946dc38e43c54739cc2b4/5723bda56ca1da78aa2b97c7/aa78704530a1375897bd66012bbebb75/questions-words.txt)

**Comment by soimort** [comment]
Generally, a "`Null response`" message means the HTTP request got no response, which indicates that Google Translate has blocked your access because of excess usage.

Sorry but there's nothing I can do in this situation.

**Comment by ryukinix** [comment]
The requests are sent by line? Maybe clustering the lines could be avoid that sad type of behavior.

**Comment by soimort** [comment]
That brings us to #30. Note that if you upload the whole file onto Google Translate's web interface, only part of it can be translated (from my observation). So Google Translate still has a limitation on POST requests.

---

Tips: If you want to do something reasonably large, don't rely on `trans`. Use Google's official Translate API instead.
