### ISSUE TITLE
Can NOT specify language

### ISSUE THREAD

**Issue by Santino-Wu** [soimort/translate-shell#119]
Hi,

Specified a language was not working for me, it just output an empty line, e.g.

```
# Neither with colon
$ trans ja: 手紙
   # empty line here
# nor option `source`
$ trans -s ja 手紙
   # empty line here
```

---

Version information:

```
Translate Shell       0.9.3.2

platform              Darwin
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) 0.19.7
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 localhost:8123
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
```

**Comment by soimort** [comment]
1. Does this work without the language option?
2. Does this work without your proxy `localhost:8123`?
3.  Please post the full output with `-D` option.

**Comment by Santino-Wu** [comment]
Hi, @soimort !

It _works_ without the language option, however, i have to use proxy since the _GFW_.

It seems the request was bad request after using `-D` option, please see the following log for the question 1 and 3.

---

```
# Result of question 1:
$ trans -b :it hello
ciao

# Result of question 3:
$ trans -D -s ja 手紙
text = 手紙
tkk = 406306
tk = 453431.55317
  35 bytes > HTTP/1.1 400 Error in request line
  18 bytes > Connection: close
  36 bytes > Date: Sun, 08 May 2016 10:24:31 GMT
  24 bytes > Content-Type: text/html
  20 bytes > Content-Length: 419
  11 bytes > Expires: 0
  24 bytes > Cache-Control: no-cache
  17 bytes > Pragma: no-cache
   1 bytes >
 102 bytes > <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
  12 bytes > <html><head>
  54 bytes > <title>Proxy error: 400 Error in request line.</title>
  13 bytes > </head><body>
  34 bytes > <h1>400 Error in request line</h1>
  40 bytes > <p>The following error occurred:<br><br>
  46 bytes > <strong>400 Error in request line</strong></p>
  94 bytes > <hr>Generated Sun, 08 May 2016 18:24:31 CST by Polipo on <em>_MY_COMPUTER_NAME_.local:8123</em>.
  15 bytes > </body></html>
content = '''
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><head>
<title>Proxy error: 400 Error in request line.</title>
</head><body>
<h1>400 Error in request line</h1>
<p>The following error occurred:<br><br>
<strong>400 Error in request line</strong></p>
<hr>Generated Sun, 08 May 2016 18:24:31 CST by Polipo on <em>_MY_COMPUTER_NAME_.local:8123</em>.
</body></html>
'''
tokens = ["<!DOCTYPE", "HTML", "PUBLIC", "\"-//W3C//DTD HTML 4.01 Transitional//EN\"", "\"http://www.w3.org/TR/html4/loose.dtd\"", ">", "<html><head>", "<title>Proxy", "error:", "400", "Error", "in", "request", "line", ".", "</title>", "</head><body>", "<h", "1", ">", "400", "Error", "in", "request", "line</h", "1", ">", "<p>The", "following", "error", "occurred:<br><br>", "<strong>", "400", "Error", "in", "request", "line</strong></p>", "<hr>Generated", "Sun", ",", "0", "8", "May", "2016", "18", ":", "24", ":", "31", "CST", "by", "Polipo", "on", "<em>_MY_COMPUTER_NAME_", ".", "local:", "8123", "</em>", ".", "</body></html>"]
ast = {
"0" "Sun"
"1" "</body></html>"
}
-- display original text & phonetics


-- display major translation & phonetics

```

Best,

**Comment by soimort** [comment]
Try this one, but with source language (English) specified explictly:

```
$ trans -b en:it hello
ciao
```

If the above works, then the problem isn't about language option at all. It's possibly that your proxy are tampering HTTP requests (for non-Unicode characters?)

From your debug output there is a line `Proxy error: 400 Error in request line`, so I can almost tell the proxy isn't forwarding the request correctly (wrong charset?).

**Comment by Santino-Wu** [comment]
Thanks for checking this issue, @soimort !

You were right, unicode did not work for me since the proxy did not parse the request parameters correctly.

However, it works if i tried to translate with letters:

```
$ trans -b ja: tegami
letter

$ trans -b zh: shijie
world
```

im currently not sure what the problem was, but it had nothing to do with translate-shell.

**Comment by soimort** [comment]
You're welcome.

Currently `trans` makes use of only HTTP `GET` requests,  where all words (assumed Unicode) are encoded in plain URLs, so your proxy needs to handle that properly. It's just a guess though. If you have access to logs of your proxy server, you may easily check what's up with it.

**Comment by Santino-Wu** [comment]
Finally, i resolved this problem! 🎉 

_Polipo_, the proxy i used before, was not abled to parse requests which contain Unicode characters. 

To use _Privoxy_ instead of _Polipo_, it work well now:

```
$ trans -b zh:en 谢谢，soimort！
Thank you, soimort!
```

**Comment by soimort** [comment]
Filtering proxies do some tricks on HTTP headers, and if there were implemented in C, UTF-8 encoding needs to be done very carefully. Some of them fail to do this. Another working alternative would be Shadowsocks, but requires a proxychains hook since translate-shell doesn't support SOCKS directly.

Anyway, good to know it works for you.

**Comment by Santino-Wu** [comment]
Got it, i have Shadowsocks, however it could not handle http request in my terminal, so i need a http proxy `Privoxy` in this case.
