### ISSUE TITLE
empty output - solved

### ISSUE THREAD

**Issue by theogrcz** [soimort/translate-shell#127]
Hello people,

thats an already closed issue for me but i am creating this in order to help anyone with similar problem.

i installed the trans with Option #1 and i was getting empty results(output). I removed the ./trans and i used the Option #3 the git installation. after that everything is just working perfect.

my trans -V:

Translate Shell       0.9.3.2-git:888b0d0

platform              Linux
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) 0.19.6
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues

@soimort 

it doesn't matter how many thanks i will say to you man... thats a FANTASTIC shell integration!! For Linux admins that work all day in front of the console, its SUCH a help!!! Million thanks!!!

**Comment by soimort** [comment]
Thanks for reporting -- I'm closing this now, as #123 is marked as fully fixed.

A new version should be released very soon.
