### ISSUE TITLE
Make test not working on OS X due to readline differences

### ISSUE THREAD

**Issue by Synchro** [soimort/translate-shell#14]
trs works fine when I run it myself, but when I run `make test`, I get this:

``` bash
 `./translate 忍者` = 'Ninja' ]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
[ `./translate {zh=} 忍者` = 'Ninja' ]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
[ `./translate {=fr} 忍者` = 'Ninja' ]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
[ `./translate {ja=@ja} 忍者` = 'Ninja' ]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
[ `./translate {zh=ja} 忍者` = '忍者' ]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

A little search led me to [this topic](http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac) - BSD readlink is quite different to Linux readlink :( There are several solutions there, but none are especially pretty.

**Comment by soimort** [comment]
Not a big issue -- I never expected this `make test` to be ran by human. It's for Travis CI only. As long as it runs on a Linux server, it's good enough :sunglasses:

**Comment by luzpaz** [comment]
What's the solution then? Because everytime I run ./translate I get the above 2 lines as well?

**Comment by soimort** [comment]
Sorry for that. It seems that commit ea69bb26738231038c1c53785a5ebe609e671582 (which makes use of `readlink -f`) causes the issue. I was not aware of that.

I'll fix it very soon.

**Comment by soimort** [comment]
Reverted so that `./translate` works for OS X users.
