### ISSUE TITLE
support XDG

### ISSUE THREAD

**Issue by teto** [soimort/translate-shell#141]
I've been looking for such software for a long time, really happy to find one !

Would it be possible to support https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html ?
Most likely it would consist in looking for $XDG_CONFIG_HOME and if not set in ".config/translate-shell" directories for the config file.
It prevents cluttering the $HOME folder along with other advantages.

Nb: is there any vim plugin for this, else I might write a short one

**Comment by soimort** [comment]
Thanks for the suggestion -- support for `XDG_CONFIG_HOME` has been added in 3bd84a9.

**Comment by teto** [comment]
Thanks !
