### ISSUE TITLE
Work with offline providers (dict/dictd for instance)

### ISSUE THREAD

**Issue by teto** [soimort/translate-shell#142]
I often work offline and though I haven't found any great offline translation tool (or rather dictionary), I use "dict" which is better than nothing.
Would it be possible to support "dict" so as to use a single command for online and offline queries ?

**Comment by MVoz** [comment]
trans -list-engines
trans -engines apertium

https://www.apertium.org

offline 
http://wiki.apertium.org/wiki/Installation
http://wiki.apertium.org/wiki/Translating_man_pages

**Comment by teto** [comment]
thanks for the tip.
