### ISSUE TITLE
Error when translation engine is bing and text contains quotes

### ISSUE THREAD

**Issue by zainescu** [soimort/translate-shell#143]
When the translation engine is bing and the text contains a quote the request will fail.

bash trans -b -engine bing :fr -no-ansi "Life's but a walking shadow, a poor player"
[ERROR] Invalid request
[ERROR] You must specify a JSON array of Translate requests in the POST body

Same request is successful with google/yandex
bash trans -b -engine google :fr -no-ansi "Life's but a walking shadow, a poor player"
, Un pauvre joueur de vie mais une ombre de marche

**Comment by soimort** [comment]
Thanks for the report -- should be fixed now.
