### ISSUE TITLE
line 4125: syntax error near unexpected token `)'

### ISSUE THREAD

**Issue by for-coursera** [soimort/translate-shell#146]
OS X 10.8.5
GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin12)
GNU Awk 4.1.3, API: 1.1

Installed via wget:

```
$ wget git.io/trans
$ chmod +x ./trans
```

After running like this:

```
trans :ru table
```

I'm getting the following error:

```
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(
/Users/myname/usr/local/scripts/trans: line 4125: syntax error near unexpected token `)'
/Users/myname/usr/local/scripts/trans: line 4125: `/%W/) gsub(/%W/, strftime("%W"), p)'
```

Translate shell (started via `gawk -f <(curl -Ls git.io/translate) -shell`) works fine.

**Comment by soimort** [comment]
Can you please run the following command?

```
$ sha1sum /Users/myname/usr/local/scripts/trans
```

**Comment by for-coursera** [comment]
Not `sha1sum` but `shasum` (1 is the default algorythm):

```
ab8c1ca58ade85b0c5ad5bc1cc19d3ed77c1ffd4
```

**Comment by soimort** [comment]
Then you're not using the one from http://git.io/trans, or it has been forged. The sha1sum should be `010a803ff202a5549c1f69964d9d9ef3380d9f4a`:

```
$ wget git.io/trans
$ sha1sum ./trans 
010a803ff202a5549c1f69964d9d9ef3380d9f4a  ./trans
```

**Comment by for-coursera** [comment]
Yep, sorry.

Probably, before `wget`ing it today for the first time, I also had to remove the previous version manually... (and yet, `ls -la` showed different sizes before and after that first today's download. Strange things happen :))
