### ISSUE TITLE
Not clear how to specify narrator

### ISSUE THREAD

**Issue by guest73** [soimort/translate-shell#147]
There is a parameter -narrator for the trans command. Can someone clarify in the wiki docs what values are supported?

**Comment by soimort** [comment]
The only TTS engine that ever supports narrator voice selection is Bing translator, for which I should fix (together with some accessible documentation) very soon.

**Comment by soimort** [comment]
Here it is: https://github.com/soimort/translate-shell/wiki/Narrator-Selection

**Comment by guest73** [comment]
Thank you.
