### ISSUE TITLE
Installed without gnu awk.. how to uninstall?

### ISSUE THREAD

**Issue by asaji** [soimort/translate-shell#15]
I installed this without installing GNU Awk on my mac. How do i go about doing an uninstall? I installed coretools (Contains gawk) using homebrew to try and remedy the problem but i still get this error:

env: gawk: No such file or directory

**Comment by soimort** [comment]
```
make uninstall
```

**Comment by asaji** [comment]
Hi solmort,

I just got your script working. As a mac user i just wanted to include some comments you can include in the documentation for future users. 
1. Install Homebrew:
   ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
2. Install gawk:
   brew install gawk

**Comment by soimort** [comment]
Installing `gawk` from either Homebrew or MacPorts, or directly build is of one's own choice -- I expected Mac users to handle such things in their preferred way.
Thank you for your suggestion, anyway!
