### ISSUE TITLE
A fixed narrator feature seems not working in 0.9.5

### ISSUE THREAD

**Issue by guest73** [soimort/translate-shell#150]
I followed instructions from https://github.com/soimort/translate-shell/wiki/Narrator-Selection to try the Bing narrator change capability. It did not work for me. I always here default system narrator.

**Comment by soimort** [comment]
How did it not work?

Please post your exact command and observations.

**Comment by guest73** [comment]
Here is the command I use
trans -e bing "Why not test this thing" -sp -n US,f
Observations: It sounds the same as if not specifying the -n option at all. The default sounds as ugly male voice :)

trans --version
Translate Shell       0.9.5-release

platform              Linux
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) [NOT INSTALLED]
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm
user locale           en_US (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

**Comment by guest73** [comment]
Issue can be closed. I've installed mplayer and it worked. I guess I just did not have player installed. Maybe you can add a note to the docs that player installation is required.

**Comment by soimort** [comment]
Sure, the [README](https://github.com/soimort/translate-shell#recommended-dependencies) has indicated this clearly:

> mplayer, mplayer2, mpv, mpg123, or eSpeak
> required for the Text-to-Speech functionality

Good to see it works for you.

**Comment by guest73** [comment]
Thanks for your help. Just one more thing. Just tried. After player installation, this command trans -e google -t es -s en -speak "Hi" just hungs. I have to press CTRL+C to stop it. Nothing is played back.
Also I had eSpeak already installed. Apparently for bing speaking to work you need something like mplayer. So it's not so 'clearly' :)

**Comment by soimort** [comment]
> I have to press CTRL+C to stop it. Nothing is played back.

Not sure about why this happens. I suggest you to switch to `mpv`, or try to play with your browser and see what happens:

```
$ trans -e google -t es -s en -speak "Hi" -player chromium
```

**Comment by guest73** [comment]
`trans -e google -t es -s en -speak "Hi" -player chromium`
did not work for me, perhaps because I have Google Chrome installed, not Chromium.
Installing mpv, solved the problem. By stating -player mpv it works for both engines - google and bing. Thanks again.
