### ISSUE TITLE
Installing through apt at Ubuntu 14.04

### ISSUE THREAD

**Issue by vitaly-zdanevich** [soimort/translate-shell#155]
Now this is not possible:
```
$ apt show translate-shell
N: Unable to locate package translate-shell
N: Unable to locate package translate-shell
E: No packages found
```
Please add to the repository.

**Comment by soimort** [comment]
It is the distro maintainers/contributors' decision whether they would package a certain software in their repository. Unfortunately, I have no control over it.

Please send such requests to the right channel. (e.g., the Ubuntu community)
