### ISSUE TITLE
please add tts through AWS Polly

### ISSUE THREAD

**Issue by vitaly-zdanevich** [soimort/translate-shell#156]
One of the best syntheses engine.

https://aws.amazon.com/polly/

**Comment by soimort** [comment]
Does Amazon Polly have a freely available interface hosted on a public server?

If no, then this cannot be implemented with translate-shell.

**Comment by vitaly-zdanevich** [comment]
yes, try this http://docs.aws.amazon.com/polly/latest/dg/get-started-cli-exercise.html

**Comment by soimort** [comment]
> yes, try this http://docs.aws.amazon.com/polly/latest/dg/get-started-cli-exercise.html

I meant something like https://www.bing.com/translator or https://translate.google.com/, which does ***not* require one to set up their own AWS instance**.
