### ISSUE TITLE
Wrong form of translation when translate to french

### ISSUE THREAD

**Issue by fabiobh** [soimort/translate-shell#158]
I use the following command to translate my app titles

`echo bubble thousand things - assorted tiles | trans -b en:da`
In this case the result is:
"boble tusinde ting - assorterede fliser"

But for some unknown reason, when I try to translate to french using the command line below
`echo bubble thousand things - assorted tiles | trans -b en:fr`
the result is different
"Bulle, mille, choses, assorti, tuiles"

Each word is translated individually using commas, but this is not what I expect. I expect the translate of an entire sentence.

**Comment by soimort** [comment]
That's just the way how Google Translate translates it.

https://translate.google.com/#auto/fr/bubble%20thousand%20things%20-%20assorted%20tiles
