### ISSUE TITLE
Right-to-left languages support

### ISSUE THREAD

**Issue by a1ip** [soimort/translate-shell#16]
For now translation to right-to-left languages (hebrew for example) is unreadable because it's printed from left to right.
Of course I can use 'rev'

``` bash
trs {=he} 'Israel' | rev
```

But it isn't elegant solution.

**Comment by soimort** [comment]
I would pass every text into `fribidi`, but it's one more dependency we need then.

``` sh
$ trs {=he} Israel | fribidi
```

I'll look into that.
