### ISSUE TITLE
support of Android

### ISSUE THREAD

**Issue by vitaly-zdanevich** [soimort/translate-shell#160]
Hi, thank you for your translator - I use it every day. I want to use it on my Android through terminal too. But Android do not have `make` - maybe it is not difficult to make install script works without `make`?

**Comment by soimort** [comment]
You need not use `make` directly on Android. Just build it on your computer or download a [prebuilt one](http://git.io/trans) -- but `gawk` is still required anyway.

**Comment by vitaly-zdanevich** [comment]
`awk` is not enough?

**Comment by soimort** [comment]
> `awk` is not enough?

`trans` depends on GNU's variation of awk. Please take a look at this project's `README`.
