### ISSUE TITLE
narrator selector possible for Yandex too

### ISSUE THREAD

**Issue by vitaly-zdanevich** [soimort/translate-shell#162]
Now [Wiki](https://github.com/soimort/translate-shell/wiki/Narrator-Selection) says that selecting of narrator is for Bing only - but [Yandex support few narrators through api](https://tech.yandex.com/speechkit/cloud/doc/dg/concepts/speechkit-dg-tts-docpage/) too.

**Comment by soimort** [comment]
Thanks for suggesting. This is implemented now.

https://github.com/soimort/translate-shell/wiki/Narrator-Selection#yandex
