### ISSUE TITLE
Support linefeed/carriage returns.

### ISSUE THREAD

**Issue by deragon** [soimort/translate-shell#164]
When translating a text in brief mode, linefieed/carriage returns are lost.

Input text:

    Situé entre le Lac à la Truite et le Lac Noir ce chalet vous charmera comme ils nous a charmé par sa vue donnant directement sur le lac et son quai privé, a proximité de nombreuses activités quatre saisons pour profiter des Laurentides.

    Le chalet fourni pour l'été: pédalo, kayaks, planche, BBQ, chaise hamac.  En hiver, le bois pour rester au chaud et des raquettes.

    Nouveau propriétaire depuis novembre 2016.  Nous avons loué ce chalet et l'avons tellement aimé que nous l'avons acheté!

    Petit mais confortant, le chalet est bien entretenu.  Grand balcon avec vue sur le lac, avec une grande table de picnic pour dîner et souper pendant les saisons chaudes.  Chaise Hamac suspendue pour relaxer et lire.

Output text:

    Located between Lake Trout and Lac Noir this cottage will charm you as they charmed us by its view overlooking the lake and its private dock, close to many activities four seasons to enjoy the Laurentians.
    The cottage provided for the summer: pedalo, kayaks, board, BBQ, hammock chair.  In winter, wood to stay warm and snowshoes.
    New owner since November 2016. We rented this cottage and loved it so much we bought it!
    Small but comfortable, the chalet is well maintained.  Large balcony overlooking the lake, with a large picnic table for dinner and supper during warm seasons.  Hammock chair hung to relax and read.

**Comment by soimort** [comment]
Can't reproduce.

![screenshot from 2017-03-05 11-18-19](https://cloud.githubusercontent.com/assets/342945/23586467/9540a4e2-0195-11e7-9195-37e72c95780d.png)

**Comment by deragon** [comment]
I run:

    INPUT=input-fr.txt
    OUTPUT=output-fr.txt
    translate "fr=en" -b -i "${INPUT}" -o "${OUTPUT}"

Latest code from github, **develop** branch.  Content of input-fr.txt (UTF-8, LF terminated):

    Situé entre le Lac à la Truite et le Lac Noir ce chalet vous charmera comme ils nous a charmé par sa vue donnant directement sur le lac et son quai privé, a proximité de nombreuses activités quatre saisons pour profiter des Laurentides.
    
    Le chalet fourni pour l'été: pédalo, kayaks, planche, BBQ, chaise hamac.  En hiver, le bois pour rester au chaud et des raquettes.
    
    Nouveau propriétaire depuis novembre 2016.  Nous avons loué ce chalet et l'avons tellement aimé que nous l'avons acheté!
    
    Petit mais confortant, le chalet est bien entretenu.  Grand balcon avec vue sur le lac, avec une grande table de picnic pour dîner et souper pendant les saisons chaudes.  Chaise Hamac suspendue pour relaxer et lire.

**Comment by deragon** [comment]
I just tried it with input-fr.txt in DOS format (CRLF terminated) and it works fine.  It has a problem with Linux format (LF).

**Comment by soimort** [comment]
Thanks for the report -- fixed in 07171b7.
