### ISSUE TITLE
can not enter line when used option "-p"

### ISSUE THREAD

**Issue by kevin-leptons** [soimort/translate-shell#165]
If you use option "-p"

```bash
trans -p <words>
```
Every functions is work, words is translated, speech is available but
you can enter line in command-line environment
Now command line is only 3 lines. If you enter, lines up but only 3 lines.

Then, if you perform reset your command line, everything is normal

```bash
reset
```

**Comment by soimort** [comment]
I don't understand this. The option `-p` merely calls an external media player and should not interfere with the terminal at all.

Can you show a screencast to elaborate your issue?

**Comment by kevin-leptons** [comment]
After I shutdown and power-up computer, the solution is gone. 
Unfortunately I have not any screenshots and can not make issue
again.

But I provide few of specifications in case I get issue

- This is first time installed, from github repository with "make" command
and successfully

- Before get issue, I had used other options as "-s", "-t", "-shell", "-brief"
and "-v"

And I think that in case I had used "-v" with "-shell" options, it print some
what characters such as "ESC"... and that's characters make issue with
shell

Sorry because I can re-make issue again. You should feel free to close this
issue

**Comment by soimort** [comment]
It seems like your terminal emulator is not ANSI/VT100 compatible.

On Linux/Unix, use xterm or urxvt at least. If you're on Windows then I'm not sure.

**Comment by kevin-leptons** [comment]
I use gnome-terminal or console on Debian 8. 
If issue will happen, I will catch it and send you summary
