### ISSUE TITLE
"-no-auto" and "-no-ansi" not working for google engine

### ISSUE THREAD

**Issue by 7ammer** [soimort/translate-shell#166]
"-no-auto" and "-no-ansi" has no effect with google translate's engine.

`trans ru:en "<div>test</div>" -b -e google -no-auto -no-ansi`
Outputs: `u003cDivu003e test u003c/ divu003e`

**Version / machine data**
Translate Shell       0.9.5-release
platform              Darwin
gawk (GNU Awk)        4.1.4
fribidi (GNU FriBidi) [NOT INSTALLED]
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

**Comment by soimort** [comment]
It's not about -no-auto and -no-ansi, but Unicode-escaped characters (such as HTML tags) aren't recognized yet -- See #139.
