### ISSUE TITLE
Doesn't seem to work over TOR

### ISSUE THREAD

**Issue by space-potato** [soimort/translate-shell#167]
I think this is not a program's issue, but possibly Google's.. but would it be possible to download an offline dictionary to overcome that? 

The problem I'm getting through TOR is an empty output.

Normally, if I would access translate.google.com with TOR, I would be prompted a captcha before accessing the website, so maybe this is what is blocking the output

PS: I'm pretty sure it's a problem with TOR, because I tried it in clear net and it works

**Comment by soimort** [comment]
1. Google is known to limit traffic from Tor; it's almost impossible to get rid of the CAPTCHA.
2. There's no such thing as an "offline dictionary" for Google Translate. Google Translate is not open source. Although there are some [WordNet databases](https://translate.google.com/about/intl/en_ALL/license.html) freely available, incorporating them would be beyond the scope of this project.

You may want to use an offline dictionary like dictd or sdcv.

**Comment by space-potato** [comment]
Ok I found that the other engines work well. Is there a way to set a new default engine, instead of using '-e ENGINE' every time?

**Comment by soimort** [comment]
Check out the wiki: https://github.com/soimort/translate-shell/wiki/Configuration

**Comment by guidomz** [comment]
> Ok I found that the other engines work well. Is there a way to set a new default engine, instead of using '-e ENGINE' every time?

Actually, they (apertium, bing, yandex) don't work inside TOR. They may have used to work (2017), but not anymore. :disappointed:  I hope there is another way....
