### ISSUE TITLE
second "translation language" (tl) won't get translated (with bing translator)

### ISSUE THREAD

**Issue by space-potato** [soimort/translate-shell#168]
I configured my init.trans this way:

```

{
        :translate-shell        "0.9.5-git:ff6f282"
        :verbose                true
        :indent                 2
        :tl                     ["en" "it"]
        :engine                 "bing"
}
```
This way it should automatically detect the input language and translate it to both english and italian, but it's not working as it is expected. For example, this is the output of "trans hombre"

> hombre
> 
> man
> 
> [ Español -> English ]
> 
> hombre
> 
> 
> 
> [  -> Italiano ]
> 

As you can see, the second translation won't happen

EDIT: it seems to be happening only with bing translator. I tried yandex and "works"..  is this an issue with bing or your program?

**Comment by soimort** [comment]
Thanks for the report. Should be fixed now in the `develop` branch.

**Comment by space-potato** [comment]
Yes, it's working now. Thanks!
