### ISSUE TITLE
play command (-p) doesn't work for multiple translation languages

### ISSUE THREAD

**Issue by space-potato** [soimort/translate-shell#169]
If I have multiple languages as translation languages (tl) in my init.trans and try to translate a word with the -p option, the first one will be played, while for the second one I receive the following error:

> gawk: /dev/fd/63:3481: fatal: expression for `>' redirection has null string value

**Comment by soimort** [comment]
Thanks for reporting. It seems this bug is specific to the Bing Translator engine -- please always attach the output of `trans -V` in the future so it's easier for me to look into the cause.

**Comment by space-potato** [comment]
Sure, thanks again!
And thanks for the rapidity!
