### ISSUE TITLE
trans -U via cron

### ISSUE THREAD

**Issue by JPRuehmann** [soimort/translate-shell#172]
Hello
Everytime I run trans -U via cron I gt the following error.

`tput: No value for $TERM and no -T specified`

Thanks,

**Comment by fer-ri** [comment]
Can you post full command in your crontab?

**Comment by JPRuehmann** [comment]
`5 0 * * *       root    trans -U -no-ansi`

**Comment by soimort** [comment]
Crontab doesn't seem to pass around the env variable `$TERM`, which must be set for determining the correct terminal type. Since it's running as a cron job I guess we can safely ignore that.
