### ISSUE TITLE
Extra spaces between sentences in translation (using google) (a cosmetic bug)

### ISSUE THREAD

**Issue by alk0** [soimort/translate-shell#175]
`$ trans en:es -b 'First. Second.'`

**expected output:**
```
Primero. Segundo.
```
**actual output:**
```
Primero.  Segundo.
```
**debug (server response):**
```
568 bytes > [[["Primero. ","First.",null,null,1],["Segundo.","Second.",null,null,1]],null,"en",null,null,[["First.",null,[["Primero.",1000,true,false],["En primer lugar.",1000,true,false],["Primero.",1000,true,false],["Primer.",1000,true,false],["Primero.",1000,true,false]],[[0,6]],"First.",0,0],["Second.",null,[["Segundo.",1000,true,false],["Segundo.",1000,true,false],["Segundo.",1000,true,false],["Segundo.",1000,true,false],["Segunda.",1000,true,false]],[[0,7]],"Second.",0,0]],0.56029761,null,[["en"],null,[0.56029761],["en"]],null,null,null,null,null,[["second","first"]]]
```

Note 1: It's "`Primero._`", already with a space, and "`Segundo.`" without it, as the last sentence of the text.
Note 2: The previous build aada4a2 behaves the same way, so it's not a result of recent changes (fixing #174).
Note 3: Google itself removes extra spaces:
```
$ trans es:en -b 'Primero.      Segundo.'
First.  Second.
```
As to whether it needs fixing (and how) - the decision is yours.

```
$ trans -V
Translate Shell       0.9.6.3-git:5245a54

platform              Linux
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) [NOT INSTALLED]
audio player          mplayer
terminal pager        less
terminal type         xterm-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues

```

**Comment by soimort** [comment]
I believe that a minor change on the Google API server side led to this regress. If I recall correctly, there was no trailing space (neither in the original sentence nor in the translated sentence). Now the API returns `"Primero. "`  but `"First."`, which seems less consistent than it was before.

```json 
["Primero. ","First.",null,null,1],
["Segundo.","Second.",null,null,1]],
```

I pushed a workaround for that, which hopefully won't break anything.

**Comment by alk0** [comment]
I'm sorry, but I don't think it's an improvement.
First, it passes \0 to the output:
```
$ trans en:es -b 'First. Second.' | xxd
00000000: 5072 696d 6572 6f2e 2000 5365 6775 6e64  Primero. .Segund
00000010: 6f2e 0a                                  o..
```
Second, it doesn't solve the problem even visually, since I still see two spaces for \0x20\0 almost everywhere except terminal.
Third, I don't think it's safe - there's no indication that Google _always_ uses that extra space, and that it won't change any moment.
I would suggest something like `sub(/ $/, "")` before joining, if it's fast enough in awk, or any other way to _"remove just one trailing space if it exists"_ before joining lines. Or maybe `sub(/ *$/, "")` to remove all of them (less safe?). Or just leave it as it was, because now I think it has become worse.

**Comment by alk0** [comment]
This change seems to work for me. (But I'm not sure it's a brilliant idea to do it in `Commons`, might break something else, no? I didn't check all calls to `join()` in the code.)

```
diff --git a/include/Commons.awk b/include/Commons.awk
index 07d5a88..bc6898a 100644
--- a/include/Commons.awk
+++ b/include/Commons.awk
@@ -153,8 +153,10 @@ function join(array, separator, sortedIn, preserveNull,
         saveSortedIn = PROCINFO["sorted_in"]
         PROCINFO["sorted_in"] = sortedIn
         for (i in array)
-            if (preserveNull || array[i] != NULLSTR)
+            if (preserveNull || array[i] != NULLSTR) {
+                sub(/ $/, "", array[i])
                 temp = j++ ? temp separator array[i] : array[i]
+            }
         PROCINFO["sorted_in"] = saveSortedIn
     } else
         temp = array
diff --git a/include/Translators/GoogleTranslate.awk b/include/Translators/GoogleTranslate.awk
index 42fd6a4..d29c6b9 100644
--- a/include/Translators/GoogleTranslate.awk
+++ b/include/Translators/GoogleTranslate.awk
@@ -197,7 +197,7 @@ function googleTranslate(text, sl, tl, hl,
     }
     PROCINFO["sorted_in"] = saveSortedIn
 
-    translation = join(translations, "\0")
+    translation = join(translations)
 
     returnIl[0] = il = !anything(ils) || belongsTo(sl, ils) ? sl : ils[0]
     if (Option["verbose"] < 0)
```

**Comment by soimort** [comment]
> First, it passes \0 to the output:
> Second, it doesn't solve the problem even visually, since I still see two spaces for \0x20\0 almost everywhere except terminal.

This change was intentional. `\0` is invisible in the terminal, and it won't appear anywhere if you just copy-and-paste these text by hand. Certainly, if you have a program that consumes the output of `trans`, notice that `\0` still remains at the end of every sentence -- actually I think it's a beneficial thing to have, because otherwise it won't be possible to reliably break sentences (if someone wants to do that).

> Third, I don't think it's safe - there's no indication that Google always uses that extra space, and that it won't change any moment.

From my observation so far, the extra space for indicating end-of-sentence should appear in every language except for Chinese and Japanese. It might be slightly better to let Google Translate decide when to add extra spaces, and we just concatenate them with no further assumption.

**Comment by alk0** [comment]
Thank you for the comment. I see your point, but I still can't agree that this is a good solution.

("it won't appear anywhere" - in fact it appears pretty much _everywhere_: `far2l` shows it as space (both editor and terminal), `mcedit` and `nano` show it as `^@`, Sublime Text shows it as `NUL`, `xed` doesn't even want to open the file with `\0`s in it at all, complaining that it must be binary... what else? LibreOffice Writer converts it to `#`, etc.)

Still, I have the option to use my "custom" version, or to use some kind of post-processing with the original one, whenever I need to get rid of those `\0`s, so, surely this _newly created_ problem has its own workarounds...

**Comment by soimort** [comment]
When it comes to editors the NULL character is indeed a bit quirky (in fact I noticed that it's also shown as a `^@` in `emacs`). I've thrown it away in the last commit. 
(`join` is a common helper function that simply joins strings as they were, doing something hacky like `sub(/ $/, "")` on the original string might bring bad surprises, so I opted for a more consistent solution.)

**Comment by alk0** [comment]
Thank you again! _(And I totally agree that using `sub()` in join was not the best idea, just a quick and dirty hack.)_

There's still one problem, though (tested against 1f5a627)
`trans de:en -e google -b '"Ja", sagte er.'`
or
`trans de:en -e google -b "\"Ja\", sagte er."`
expected:
`"Yes," he said.`
actual output:
`"Yes,"he said.`
server response:
`["\"Yes,\" he said.","\"Ja\", sagte er.",null,null,3]`

It still looks OK after tokenization and in `ast`:
`"0,0,0,0"	"\"\\\"Yes,\\\" he said.\""`
but then it somehow loses this space after `"Yes,"`.
_(Does it get confused by nested escaping at some point?)_

As far as I can see, it happens only with `:en` direction (es, de, ru were tested), and doesn't happen with `en:` (same languages were tested), and only using google (yandex and bing work OK). Note: neither of those languages puts a comma before a quote, as English does: `"Sí",`, `"Ja",`, and `«Да»,` (and the last one uses duck-foot quotes by default).

**Comment by soimort** [comment]
Again, if I recall correctly, there used to be redundant spaces in between words and punctuation marks as were returned by the API, something more or less like `" Hello , world . "`. I guess that's why I had these dumb substitutions in `Translate.awk`:

```awk
    text = gensub(/ ([.,;:?!"])/, "\\1", "g", text)
    text = gensub(/(["]) /, "\\1", "g", text)
```

As you see, now that Google Translate has sanitized its output, the second line (which removes any space after a `"`) is causing a problem. Should be fixed now. Thanks for the report.
