### ISSUE TITLE
man pages translate

### ISSUE THREAD

**Issue by MVoz** [soimort/translate-shell#177]
Доброго времени суток
как можно реализовать перевод man страниц, с помощью вашей утилиты?

первый вариант:
trans -M | trans -e bing -b :ru
man ssh | trans -e bing -b :ru

но есть нюансы, переводит не все и искажает многое
во вторых как можно сохранить вывод в формате man страницы?

**Comment by soimort** [comment]
1. I need some clarification on details: What is the expected output? What is the actual output?
2. Please always report bugs in English.
