### ISSUE TITLE
Strange characters while using trans-shell as ruby sub-process

### ISSUE THREAD

**Issue by abhi18av** [soimort/translate-shell#178]
Hello @soimort ,

This awesome tool has become a priceless asset in my workflow - thanks 👍 

But recently, I ran across strange behaviour of the tool when I use it from within ruby for example 
``` `trans en:kk "I am interested in music." > file.txt` ```

The output in this case is mixed with strange escape characters

```sh

I'm interested in music.' null
/null/

[1mМен музыка қызықтырады. null[22m
[1m(null Men mwzıka qızıqtıradı.)[22m

Translations of [4mI'm interested in music.' null[24m
[ [4mEnglish[24m -> [1mҚазақ тілі[22m ]

[4mI[24m
    [1mМен[22m, [1mМаған[22m, [1mI[22m
[4mmusic in[24m
    [1mмузыка[22m, [1mв жасалған тамаша музыка[22m, [1mмузыка саласындағы[22m
[4minterested 'm[24m
    [1mқызықтырады[22m, [1mдеген қызығушылығым бар[22m, [1mқызығушылығым[22m, [1mқызығушылығым бар[22m, [1mдеген қызығушылығым[22m
[4m. '[24m
    [1m.[22m

```

Could you help me understand and correct this behaviour?

**Comment by soimort** [comment]
You need to specify `-no-ansi` to disable ANSI escape sequences when writing to a file descriptor other than `stdout`. Also, please update to the latest version (0.9.6.3).

**Comment by abhi18av** [comment]
Yup, did both as you suggested  - I should read documentation more hehe 😄 

Though, by that time I'd already come up with a solution of my own.

```python
import os, glob, re

files = glob.glob("*.txt")

ansiEscape = re.compile(r'\x1b[^m]*m')

for f in files:
    with open(f, 'rb+') as aFile:
        contents = aFile.read()
        print(contents)
        print("###########")
        contentsDecoded = contents.decode()
        contentsCleaned = ansiEscape.sub('', contentsDecoded)
        aFile.seek(0)
        aFile.write(contentsCleaned.encode())
        aFile.truncate()

print("Done!")
```

Anyways, got to learn something new in Python :)
