### ISSUE TITLE
Proper locale not detected automatically

### ISSUE THREAD

**Issue by Vascom** [soimort/translate-shell#179]
Hi i expected that trans will detect current locale automatically, but it can't.
I have $LANG ru_RU.UTF-8 but
```
$ trans -b word
word
```
while
```
$ trans -b :ru word
слово
```
Can you help solve problem?

**Comment by soimort** [comment]
Please check your configuration (e.g. `~/.translate-shell/init.trans`).

If you have already set `:tl` to `en` there, the current locale will be ignored.

**Comment by Vascom** [comment]
I have no configuration files at all.
```
$ ls ~/.translate-shell/init.trans
ls: невозможно получить доступ к '/home/vascom/.translate-shell/init.trans': No such file or directory
```

**Comment by soimort** [comment]
Please post your `trans -V` then.

**Comment by Vascom** [comment]
```
Translate Shell       0.9.6.3

platform              Linux
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) 0.19.7
audio player          mplayer
terminal pager        less
terminal type         xterm-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
```
I see **user locale           en_US.UTF-8 (English)** but I have
```
$ locale
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```
And 
```
$ echo $LANG
ru_RU.UTF-8
```

**Comment by soimort** [comment]
One more question: what is your `$LANGUAGE`?

**Comment by Vascom** [comment]
This variable is empty. I am use Fedora 25.

**Comment by soimort** [comment]
That would be very strange. I cannot reproduce it on my side (Arch) at all.

```
$ export LANG=ru_RU.UTF-8
$ trans -no-init -V      
Translate Shell       0.9.6.3-git:cff6696

platform              Linux
gawk (GNU Awk)        4.1.4
fribidi (GNU FriBidi) 0.19.7
audio player          mplayer
terminal pager        less
terminal type         xterm
user locale           ru_RU.UTF-8 (Russian)
home language         ru
source language       auto
target language       ru
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
```

It seems you're using a prebuilt `trans`. Could you try to fetch it from git: https://github.com/soimort/translate-shell and see if the problem persists?

**Comment by Vascom** [comment]
So locale autodetect work once during configure and make?
I am create translate-shell rpm package for Fedora users https://github.com/RussianFedora/translate-shell/blob/master/translate-shell.spec
It is builded on koji server with english locale.

**Comment by Vascom** [comment]
Also it is not work even if I clone from git and build it directly on my system.

**Comment by soimort** [comment]
Thanks, I think now I have located the problem -- locale autodetect only works for direct calls (via `./translate`) and antigen installation, but not for standalone executables.

I'll look into this issue further.

**Comment by Vascom** [comment]
Thanks. Now it work good :)
RPM packages for Fedora here http://koji.russianfedora.pro/koji/packageinfo?packageID=146 or in russianfedora repo.
