### ISSUE TITLE
How to make `trans` invoke `rlwrap` automatically?

### ISSUE THREAD

**Issue by lacygoill** [soimort/translate-shell#184]
Hello,

according to `man trans`:

    -I, -interactive, -shell
        Start an interactive shell, invoking rlwrap whenever possible (unless -no-rlwrap is specified).

So when I passed the `-shell` option to `trans`, I thought it would automatically invoke `rlwrap`,
allowing me to move on the command line using `readline` key bindings (`C-a`, `C-e`, …).
However, it doesn't seem to work, because if I start `trans` like this:

    trans -shell
    hello

… after inserting `hello`, when I press `C-a` or `C-e`, it just inserts the literal keycodes (`^A`, `^E`).

It's not a big problem, as I have defined an alias to automatically invoke `rlwrap`:

    alias trans='rlwrap trans'

However, I would like to know if I did something wrong during the installation:

    git clone https://github.com/soimort/translate-shell
    cd translate-shell
    git checkout v0.9.6.4
    make
    sudo checkinstall

The installation didn't report any error.

I'm on Ubuntu 16.04 and here's the value of my `$PATH` environment variable:

    /home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/.fzf/bin

It contains `/usr/bin` where the `rlwrap` binary is located:

    % type rlwrap
        rlwrap is /usr/bin/rlwrap

And here's the output of `trans -V`:

    Translate Shell       0.9.6.4

    platform              Linux
    gawk (GNU Awk)        4.1.3
    fribidi (GNU FriBidi) [NOT INSTALLED]
    audio player          mpv
    terminal pager        less
    terminal type         screen-256color
    user locale           en_US (English)
    home language         en
    source language       auto
    target language       en
    translation engine    google
    proxy                 [NONE]
    user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
    theme                 default
    init file             [NONE]

Thank you very much for your program.

**Comment by soimort** [comment]
Please post the result of `trans -shell -debug`.

**Comment by lacygoill** [comment]
I've started `trans` by putting a backslash in front of it (to disable the alias) and adding the `-debug` option.
Here's what it reported:

    \trans -shell -debug
    >> not found: $TRANS_PROGRAM or EntryPoint
    Translate Shell
    (:q to quit)
    > hello^A^E

**Comment by soimort** [comment]
It seems like a regression bug  caused by 16b78f2. A direct execution of `./translate` should call `rlwrap` as expected, but the built `trans` was kind of broken. Thanks for reporting this.
