### ISSUE TITLE
Sometimes doesn’t display all alternative translations

### ISSUE THREAD

**Issue by huftis** [soimort/translate-shell#188]
translate-shell sometimes doesn’t display all alternative translations. Example:

```
$ ./translate en:no nails
nails

negler

Definitions of nails
[ English -> Norsk ]

noun
    spiker
        nail
```

That is, only *negler* and *spiker* is displayed, even though translate.google.com suggests both *negler*, *spiker*, *nagler* and *neglene*.

Another example is *inclusive*, which only lists *inklusive*, not *inkluderende* (the Web site suggests both translations).

On the other hand, sometimes it works fine:

```
./translate en:no sweetheart
sweetheart
/ˈswētˌhärt/

kjæreste

Translations of sweetheart
[ English -> Norsk ]

sweetheart
    kjæreste, kjæresten, elskling, kjære
```

All four alternative translations are shown.

It looks like it *might* be related to whether the word has dictionary information. (Personally, I would prefer to be able to see a list of all alternative translations *without* any dictionary information, even if it exists.)

Output of `./translate -V`:
```
Translate Shell       0.9.6.4-git:edaa2dc

platform              Linux
gawk (GNU Awk)        4.1.4
fribidi (GNU FriBidi) 0.19.6
audio player          mplayer
terminal pager        less
terminal type         xterm-256color
user locale           nn:no:nb:da:en_GB:en@quot (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
```

**Comment by soimort** [comment]
Thanks for the issue report.

Alternative translations were indeed discarded if dictionary information exists. I don't remember why I made that choice, but now it seems there's no reason to do so since these alternatives can be useful.

(As a side note: you may use `trans en:no -show-dictionary=0 nails ` to suppress all the dictionary information, or just put `:show-dictionary false` in the config file)
