### ISSUE TITLE
player argument not work with bing engine 

### ISSUE THREAD

**Issue by labolado** [soimort/translate-shell#189]
` trans hello  -player open  `

work fine

` trans hello  -e bing -player open`

not work

system: mac 10.12.6

**Comment by soimort** [comment]
I'm not sure macOS's `open` command will work as a `-player` argument, since `trans`'s workaround for Bing TTS makes use of a temporary file which macOS's `open` may fail to infer the media type.

Have you tried to specify the actual player name (for example, `afplay`) directly?
