### ISSUE TITLE
Tests fail when offline

### ISSUE THREAD

**Issue by ferki** [soimort/translate-shell#192]
While investigating [Gentoo bug 630950](https://bugs.gentoo.org/show_bug.cgi?id=630950), I could reproduce the reported symptoms when trying to run `make check` while being offline, leading to the following failure on the output:

```
[...]
build/trans -V
Translate Shell       0.9.6.4

platform              Linux
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) 0.19.6
audio player          mpv
terminal pager        less
terminal type         st-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
[ "`build/trans -no-init -D -b 忍者`" = 'Ninja' ] &&\
[ "`build/trans -no-init -D -b 'hello world'`" = 'hello world' ]
gawk: /dev/fd/63:2910: fatal: remote host and port information (translate.googleapis.com, 80) invalid
make: *** [Makefile:30: check] Error 1
```

While it seems at least some of the supported translation engines can be configured to work offline too (see [#142 (comment)](https://github.com/soimort/translate-shell/issues/142#issuecomment-303307161)), translate-shell is clearly a tool to interact with online translation services.

So I wondered, whether fixing tests to work offline could be in the scope of the project. Perhaps an additional target in the `Makefile`? Or controlling test behaviour via an environment variable?

Let me know if you have an acceptable solution in mind. I might need some guidance, but I'm willing to send code too :)

**Comment by soimort** [comment]
`make test` is what you're looking for. It performs some sanity checks without accessing any online API.

Of course, to make sure that everything actually works, `make check` (that does use Google Translate) is a necessity.
