### ISSUE TITLE
How to pass proxy with username and password?

### ISSUE THREAD

**Issue by fer-ri** [soimort/translate-shell#193]
Hi

How to pass proxy in format `username:password@domain.com:80` ?

Because i always get 

```
gawk: /dev/fd/63:2910: fatal: remote host and port information 
(...) invalid
```
Thanks

**Comment by soimort** [comment]
Please post your full command and debug information.

**Comment by fer-ri** [comment]
Hi @soimort 

This is my command

```
$ trans -b -t de -proxy username:password@de106.nordvpn.com:80 "Hello world"
gawk: /dev/fd/63:2910: fatal: remote host and port information (username:password@de106.nordvpn.com, 80) invalid
```

And sorry, how to get debug information?

Thanks

**Comment by soimort** [comment]
Please try the latest `develop` branch. I've implemented some basic proxy authentication for this.

(Digest authentication takes significantly more work and is yet to be done, but in your case, a basic auth should be sufficient.)

**Comment by fer-ri** [comment]
Ok,

I'll try it with `develop` branch ..

Thanks for your effort @soimort :+1: 

Have a great day ..

**Comment by fer-ri** [comment]
Hi @soimort 

I've tried, but always get blank response

This my version with `develop` build

```
$ trans -version
Translate Shell       0.9.6.4-git:f7e4d9c

platform              Linux
gawk (GNU Awk)        4.0.1
fribidi (GNU FriBidi) [NOT INSTALLED]
audio player          mplayer
terminal pager        less
terminal type         xterm
user locale           en_US (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]
```

And this is my screenshot when running command

![image](https://user-images.githubusercontent.com/1922652/30600025-87f17c32-9d88-11e7-8037-abbf610836b6.png)

Thanks

**Comment by soimort** [comment]
Can you try these two commands? (Replace `user:pass` with your own username/password.)

```
$ trans -D -x user:pass@de106.nordvpn.com:80 "Hello world" 2> >(head -n 14)

$ curl -I -x user:pass@de106.nordvpn.com:80 http://example.com/
```
If you get `407` on both, it could be your user/password is wrong. Otherwise it's something else I need to fix...

**Comment by fer-ri** [comment]
Hi @soimort 

Sorry for late response, It's morning right now in my place :)

First command gave me 407 and second command gave me 200

![image](https://user-images.githubusercontent.com/1922652/30622481-1c457aa2-9ddc-11e7-8b3d-d7cfbcdd2bb1.png)

Thanks

**Comment by soimort** [comment]
Well, I have no clue now. It's hard to debug these credential problems without a context. (since I don't have access to that exact proxy server.)

You could try running
```
$ sudo tcpdump -l -A 'tcp dst port 80' 2>/dev/null | grep 'Proxy-Authorization'
```
in a separate window, repeat the above two commands (`trans` and `curl`) and compare the results yourself.

Let me know if there's a difference, but don't post the actual output here because they are really base64-encoded credentials.

**Comment by fer-ri** [comment]
Hi

How to use this command with Wifi?

```
$ sudo tcpdump -l -A 'tcp dst port 80' 2>/dev/null | grep 'Proxy-Authorization'
```
 Or how to send you private message for username pass for the proxy?

Thanks

**Comment by fer-ri** [comment]
Hi @soimort 

Finally make it,

Since my username of proxy using email, so usually i need to encode `@` character become `%40`, especially in PHP.

But if i keep using `@` with `trans` then everything is working :D

![image](https://user-images.githubusercontent.com/1922652/30685711-0053eebe-9ee0-11e7-8f7e-ef4a7422ad71.png)

My last question, since this changes stilll in develop branch, so when is it available from this URL `wget git.io/trans` ?

I'm really happy. Thanks @soimort

**Comment by soimort** [comment]
For consistency with `curl`, URL encoded strings like `%40` are supported now as well as the literal `@`.

`git.io/trans` is updated synchronously with each stable release. (but hopefully it's not a big problem since you can always use the `develop` branch.)

**Comment by fer-ri** [comment]
Thanks @soimort for your patience :+1: 

Have a great day :+1:
