### ISSUE TITLE
base64 blank when translating multi line with proxy

### ISSUE THREAD

**Issue by fer-ri** [soimort/translate-shell#195]
Hi @soimort 

When trying to translate multi line using `-input` or  `file://` with user password proxy, only first request or first line is success. Second line and so on is blank.

```
trans -no-auto -b -t de -proxy username:password@my-proxy.com:80 -input article.txt
```

After investigating the header sent, proxy header authentication become blank for second request and so on.

It's cause by `base64` function that failed to return on sequence request

```
Proxy-Authorization: Basic 
```

For quick fix, right now i modify to like this

```awk
if (HttpAuthUser && HttpAuthPass)
        # TODO: digest auth
        ("echo -n " HttpAuthUser ":" HttpAuthPass PIPE "base64") | getline base64Auth

        header = header "Proxy-Authorization: Basic "   \
            base64Auth "\n"
```

While debugging, i've tried something like this, and i can confirmed `base64` not working after first request

```
    if (HttpAuthUser && HttpAuthPass)
        # TODO: digest auth
        header = header "Proxy-Authorization: Basic "   \
            base64(HttpAuthUser ":" HttpAuthPass) "\n"

    p(header)
    p("Start base64")
    p(base64("Hello world"))
    p("End base64")
```

![image](https://user-images.githubusercontent.com/1922652/30698619-b40b617c-9f0c-11e7-9766-261caaa6b5f6.png)

Do you have any idea why this happen?

Thanks

**Comment by soimort** [comment]
I suspect that this is a bug (or at least misfeature) of GNU awk. For performance reasons, gawk will only run each unique piped command once (even if it is called multiple times in a script). But if `getline` feeds into a local variable, the binding is lost in the subsequent environment. I don't really know the rationale for this:

    $ gawk 'function f(x){"echo "x | getline t;return t} BEGIN{print f(1)f(1)}'
    11

    $ gawk 'function f(x,t){"echo "x | getline t;return t} BEGIN{print f(1)f(1)}'
    1

It's rather easy to fix on our side, though.

**Comment by fer-ri** [comment]
Thanks @soimort 

Seems like awk is the culprit .. hehhee..
