### ISSUE TITLE
Extension will not start. Error: can't  convert length to an integer. 

### ISSUE THREAD

**Issue by develroo** [soimort/translate-shell#199]
As it says above. The translate shell is installed and works fine on it's own on the command line. But the extension refuses to load and this is what I get when I look at it with Looking Glass.

This happened during the last update. 

Any ideas where I can go to fix this?

**Comment by soimort** [comment]
I don't know what "extension" you're referring to, since this repository is purely for the command-line program. If it's a 3rd party software, then you should direct the question to the right place (i.e. the maintainer of the extension).

**Comment by develroo** [comment]
My mistake. Was looking a the wrong git hub page. translate-shell works fine. I was looking at [the extension]( https://extensions.gnome.org/extension/593/text-translator/) that uses it.

Sorry.
