### ISSUE TITLE
Daily limits?

### ISSUE THREAD

**Issue by morlan** [soimort/translate-shell#20]
Are there any daily limits?  I've tried to translate a long file and it will translate only a portion of it.  Then I try running 'trs' from command line and Google returns blank responses to any requests.  I wait 24 hours and then it works again.  Any advice?

**Comment by soimort** [comment]
If Google noticed any overuse - I'm sure it will issue an IP block.

Unfortunately we are unable to resolve this. The suggestion is to use Google's official API, in that case.

**Comment by SGmuwa** [comment]
Could trans catch limit and report to stderr?
