### ISSUE TITLE
Autocorrection work not fine

### ISSUE THREAD

**Issue by Vascom** [soimort/translate-shell#200]
Then I enter word with error I can't see corrected word:
```
$ trans -b feeedback
Showing translation for:  (use -no-auto to disable autocorrect)
Обратная связь
```
Engine - google.

**Comment by soimort** [comment]
This is actually intended behavior, as the original text is suppressed in the `brief` mode which outputs _as minimum as possible_. Otherwise it will be like (in default mode)

```
Showing translation for:  (use -no-auto to disable autocorrect)
feedback
/ˈfēdˌbak/

Обратная связь
(Obratnaya svyaz')
```

Perhaps the first-line hint should be removed to avoid any confusion.

**Comment by Vascom** [comment]
OK, don't remove it. It must indicate that mistake present.
