### ISSUE TITLE
Direct translate Shortcut key in terminal

### ISSUE THREAD

**Issue by caogia** [soimort/translate-shell#201]
Hi
You shell is perfect. 
I would like to have a shortcut directly translate it from English - Vietnamses (en-vi) or Vi-En. It's mean when I press a combination key, the shell show up, what i need to do is write the word and enter. Then press esc to escape. 
So i suggest for: - Fast directly translating  - Simple GUI commandline (same like run command promt box)
I'm on Solus and new in Linux. Also bad at english too. 
Thank you

**Comment by soimort** [comment]
I'm not quite sure how to implement that, but GUI integration is something beyond the scope of this project. Sorry.
