### ISSUE TITLE
each time I try to translate something XQuartz app pops up...

### ISSUE THREAD

**Issue by KirilShishkoski** [soimort/translate-shell#206]
Hi,

It's not an issue, but rather is annoying me. Each time I try to translate something XQuartz is launching and then after, the translation appears. It seems by default the user agent is X11 or what? How to change it?

Here's the trans -V output:

```
Translate Shell       0.9.6.6-git:c8107fe

platform              Darwin
gawk (GNU Awk)        4.2.0
fribidi (GNU FriBidi) 0.19.7
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
```

**Comment by soimort** [comment]
In normal use cases `trans` does not rely upon X11 at all, so I don't see how it could ever happen. 

1. Are you on macOS, and have you configured anything extra like Automator instead of running `trans` through a terminal directly? 
2. Please open a terminal, run 
```
$ gawk -f <(curl -Ls git.io/translate) -- -shell
```
 and see if you can reproduce the issue.

**Comment by KirilShishkoski** [comment]
I'm on macOS. Previously I used it via HomeBrew and it had no problems at all. But for certain reasons I had to switch to MacPorts. After switching to MacPorts I faced to an additional issue such as: 'Oops! Something went wrong and I can't translate it for you' and XQuartz was still popping :(. So, I decided to download the source and compile it. I got it working, but each time XQuartz is popping and it's annoying. I ran the gawk command from above, and the XQuartz is still launching.

**Comment by soimort** [comment]
I'm neither familiar with macOS nor MacPorts. Just to be clear, in the source folder, run:

```
$ ./translate -V
```

Does it still launch XQuartz?

Moreover, does running `gawk` itself launch XQuartz?

**Comment by KirilShishkoski** [comment]
XQuartz is still launching even on ./translate -V in the src and gawk. 
I think before installing XQuartz the program was working good. Once I installed XQuartz this started happening. But I can't just uninstall XQuartz cos it's a dependency for another package.

**Comment by soimort** [comment]
> XQuartz is still launching even on ./translate -V in the src and gawk.

Then it's clear that XQuartz is messing up with your MacPorts `gawk` installation, and this has nothing to do with translate-shell itself.

Please consider reinstalling `gawk` (perhaps also XQuartz) via Homebrew. If you want to keep using MacPorts, then maybe you can report to them something like "gawk is launching XQuartz unexpectedly". `gawk` is a useful command-line utility that one might need from time to time, so it's definitely a misbehavior for it to launch X in any case.

**Comment by KirilShishkoski** [comment]
Forgot to write but I fixed the issue. If anyone has the same problem, just unload it from the LaunchAgents or:

sudo launchctl unload -w /Library/LaunchAgents/org.macosforge.xquartz.startx.plist

The apps that rely on xquartz will still work without any problems.
