### ISSUE TITLE
Null response on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by VadimKulagin** [soimort/translate-shell#208]
After installing via apt (`sudo apt install translate-shell`), I get this error:

```
$ trans Hello 
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```

```
$ trans -V 
Translate Shell       0.9.2.1

platform              Linux
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) 0.19.7
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-256color
user locale           ru (Russian)
home language         ru
source language       auto
target language       ru
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0
theme                 default
init file             [NONE]
```

I know about solution in issue #67 but it does not help.

I noticed that in the repository for Ubuntu 16.04 LTS there is an old version of the program - 0.9.2.1. However, if I download the program from GitHub via `"Direct Download"`, then it works fine.

But it is more convenient for me (and I think that not only for me) to manage programs via the `apt`, so I think that it is worth updating the program in the repository for Ubuntu 16.04 LTS.

**Comment by soimort** [comment]
This is really a problem about your Linux distribution, and I ≠ Ubuntu.You need to channel this problem to the right place, i.e., the Ubuntu community. 

To my knowledge, a newer version is available on [Ubuntu bionic](https://packages.ubuntu.com/bionic/translate-shell), but I'm not quite sure whether you can use that from Ubuntu 16.04 LTS. (probably not.)
