### ISSUE TITLE
Feature Request: Only output the identified language with -id and -b 

### ISSUE THREAD

**Issue by Nottt** [soimort/translate-shell#209]
Right now I do this :

```
root@z:~# ./trans -b --id --input /home/x/Desktop/sample.vtt 
Malti
Name                  Maltese
Family                Afro-Asiatic
Writing system        Latin
Code                  mt
ISO 639-3             mlt
SIL                   http://www-01.sil.org/iso639-3/documentation.asp?id=mlt
Glottolog             http://glottolog.org/resource/languoid/id/malt1254
Wikipedia             http://en.wikipedia.org/wiki/Maltese_language

[...]

Português
Name                  Portuguese
Family                Indo-European
Writing system        Latin
Code                  pt
ISO 639-3             por
SIL                   http://www-01.sil.org/iso639-3/documentation.asp?id=por
Glottolog             http://glottolog.org/resource/languoid/id/port1283
Wikipedia             http://en.wikipedia.org/wiki/Portuguese_language
```

I suppose this is the guesses it does, until it reaches a final decision on the last output right? But that's way too much information, and not friendly with scripts.

Maybe I'm missing something? I looked at the --help section, tried all kind of combinations of commands to suppress this output, and it seems to be breaking grep too:

![screenshot from 2018-01-17 22-15-39](https://user-images.githubusercontent.com/13532436/35074442-05e71c64-fbd5-11e7-9f0d-37f12162e38a.png)

It would be nice if we had a option to suppress even more output so we can get right to what we need in a non-interactive way, like ISO codes, name, etc.

Thanks ❤

**Comment by soimort** [comment]
Good idea.

Tip: If your `grep` (or whatever text filter you use) doesn't handle ANSI color codes well, you may use `trans -no-ansi` to disable them.

**Comment by Nottt** [comment]
Hey nice to see you are still around :smiley: 

Since we both do bash scripts, you may be able to borrow code from me in the future. Since I'll be parsing the current output anyway :D

**Comment by Nottt** [comment]
Hey I see you closed this, but I'm still getting the same output? Is it a different combination I have to use?
