### ISSUE TITLE
Blocking "translate website" feature (= proxy)

### ISSUE THREAD

**Issue by AvtechScientific** [soimort/translate-shell#210]
Hi,

first of all thank you for "translate-shell"!
I have following problem: normally I block all Internet traffic for my kid user account using iptables (I'm on Linux/Debian). I would like him to use translate-shell, but my problem is that enabling access EVEN ONLY to https://translate.google.com - will allow him to use it as proxy (via translate website functionality) and thus access ANY website.
1. Is there a way to let him use "translate-shell" but without the "translate website" feature?
2. Is it possible to block access to https://translate.google.com with browser all together?
3. Any other ideas how to achieve this?

Thank you!

**Comment by soimort** [comment]
Actually Google Translate API is hosted on the domain `translate.googleapis.com`, so I guess you may block the others (incl. `translate.google.com`) safely.

**Comment by AvtechScientific** [comment]
Block totally Internet access to kids!
e.g.:
`iptables -A OUTPUT ! -o lo -m owner --uid-owner $USERNAME -j DROP`

substitute $USERNAME with the desired username.

Enable translation via command line through sudo while blocking translating URLs:
`visudo`

```
beny    ALL= NOPASSWD: /usr/bin/trans
beny    ALL= NOPASSWD: ! /usr/bin/trans http*
beny    ALL= NOPASSWD: ! /usr/bin/trans * http*

```
Create shortcut scripts:
e.g.:
```
#!/bin/bash
sudo trans en:he -speak -player mpg123 "$1"
```
