### ISSUE TITLE
translate

### ISSUE THREAD

**Issue by alejnavarro** [soimort/translate-shell#213]
hi, i'm just ending the view of the project and notice that you don't have any information in spanish, i wonder if you want to translate something into it, because if you want to, i'll be glad to do it for you, if you let me.

**Comment by soimort** [comment]
Thanks for your interest!

You are very welcome to [create a Wiki page](https://github.com/soimort/translate-shell/wiki/_new) with Spanish translation as you like, or write about it anywhere else. I have no plan to maintain a multilingual documentation myself; but if someone can do any kind of translation in the Wiki, then I would be happy to put a link to it into the main README.
