### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by MarjaE2** [soimort/translate-shell#215]
I keep getting broken pipe errors when trying to translate .txt documents. Have tried several documents. Have tried restarting computer:

gawk: /dev/fd/63:2997: fatal: print to "/inet/tcp/0/translate.googleapis.com/80" failed (Broken pipe)

Installed using Homebrew on MacOS 10.12.6.

**Comment by soimort** [comment]
Please follow the guide and include details (e.g., command, program version) in your issue report:

https://github.com/soimort/translate-shell/blob/develop/CONTRIBUTING.md#how-to-report-an-issue

**Comment by MarjaE2** [comment]
For a short .txt file:

[user prompt] trans -b uk:en file:///Users/Marja/Downloads/Translations/Input-1.txt Output-1.txt
gawk: /dev/fd/63:2997: fatal: print to "/inet/tcp/0/translate.googleapis.com/80" failed (Broken pipe)

I had similar problems with full-length .txt files. Output.txt in my user folder was my intended output.

For trans -V

[user prompt] trans -V
Translate Shell       0.9.6.6

platform              Darwin
gawk (GNU Awk)        4.2.0
fribidi (GNU FriBidi) 1.0.1
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues

**Comment by soimort** [comment]
Does it even work in normal use cases (i.e., not translating files)? Please try the following two:

```
$ trans -debug 'Saluton, Mondo'
```

```
$ gawk -f <(curl -Ls git.io/translate) -- -debug 'Saluton, Mondo'
```

**Comment by MarjaE2** [comment]
I guess that works. But I installed this to translate files.

**Comment by soimort** [comment]
> I guess that works. But I installed this to translate files.

Then how does your file look like?

Due to technical restrictions of HTTP GET requests, files with very long lines may crash the pipe (so you might be hitting #30). Also, notice that for large files even without long lines, Translate API has an implicit quota on the number of requests every IP can make in a short time period, so if you exceed it, things might break as well.

For now, you can either try to: (1) Split your file, do not have long lines in a file, and do not translate very large files at once. (2) Switch to `bing` engine, that might partly solve the problem as it does support longer lines.

**Comment by MarjaE2** [comment]
I *already* split my file, and had the same problem with the shorter files. I can't really search for line lengths.

Google seems to be the only one with a broken pipe. Bing and Apertium drop after a couple seconds with blank output files.  Apertium doesn't seem to support Ukrainian.

**Comment by soimort** [comment]
> I already split my file, and had the same problem with the shorter files. I can't really search for line lengths.

Use `cat filename | awk '{print length}' | sort -nr | head -1`

> Bing and Apertium drop after a couple seconds with blank output files

which implies that your usage has exceeded their free quota.

**Comment by MarjaE2** [comment]
Okay, 210037 for one section after splitting. 3528 for the whole before splitting. Not sure how splitting would increase either line length or file size...

**Comment by soimort** [comment]
> Okay, 210037

210037 is long enough to displease Google. In fact, if you upload such a file using the "translate a document" button from Google Translate's web interface, you'll only get part of the translation.

Please do not abuse this tool for extreme use cases. Consider [paying Google](https://cloud.google.com/translate/pricing) if you want to use their API more intensively.
(FYI, the price is $20 per 1,000,000 characters, so you were basically requesting a free beer from them :sunglasses: )

**Comment by MarjaE2** [comment]
I have a lot of trouble using Google's own translate site, with my disabilities, and can't get more than a couple lines at a time. Which is why I was searching for alternatives. Anyway, I had been using txt-splitter software to try to avoid trouble, but I think it did something that caused a lot of this trouble.

**Comment by soimort** [comment]
I will certainly strive to make `trans` a viable alternative (specially for those who are more comfortable working in command-line) to Google's official web interface. However, as I said, if you're doing intensive translations beyond their free quota, then there's nothing I can do about it.

Good luck.
