### ISSUE TITLE
Add support for translate.google.cn

### ISSUE THREAD

**Issue by et2010** [soimort/translate-shell#216]
The `cn` domain is available in mainland China. It's much faster than the proxy solution. Could you please add support for that? Thanks!

**Comment by soimort** [comment]
The API we use is actually on a separate domain `translate.googleapis.com` (rather than `google.com`), which should be available in mainland China already.

Or are you having problems accessing `translate.googleapis.com`?

**Comment by et2010** [comment]
That url is a 404 for me here. Does that mean it's blocked?

**Comment by soimort** [comment]
404 is normal, and it implies that the API server is approachable.

It seems to me `trans` should work for you without any proxy.

**Comment by et2010** [comment]
Thanks for clarification! I remember It didn't work last year. Anyway, it works now. Thanks for this great app!

谢谢！
