### ISSUE TITLE
how to translate a whole text file in a raw?

### ISSUE THREAD

**Issue by cromatikap** [soimort/translate-shell#217]
Hi there, I'd like to translate a text into another text without all the output around the translation for each line.
I tried
`trans -i Εξαιρέσεις.txt -o test`
`cat Εξαιρέσεις.txt | trans el:en`
and the output is something like this : 

> Η μέρα κυλάει
> (I méra kyláei)
> 
> The day is rolling
> 
> Translations of Η μέρα κυλάει
> [ Ελληνικά → English ]
> 
> Η μέρα κυλάει
>     The day is rolling, The day rolls
> ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
> Για να `ρθει η επόμενη να φέρει σκέψεις άλλο αέρα
> (Gia na `rthei i epómeni na férei sképseis állo aéra)
> 
> For the next one to bring thoughts of another air
> 
> Translations of Για να `ρθει η επόμενη να φέρει σκέψεις άλλο αέρα
> [ Ελληνικά → English ]
> 
> Για να `ρθει η επόμενη να φέρει σκέψεις άλλο αέρα
>     For the next one to bring thoughts of another air, To 'come the next to bring another air thoughts
> 

You see, I'd just like something like this : 
> The day is rolling
> For the next one to bring thoughts of another air

Is there a way to do that ?
Thank you, ευχαριστώ πολή!

**Comment by soimort** [comment]
Use the `-brief` (`-b`) option.

https://github.com/soimort/translate-shell#brief-mode

**Comment by cromatikap** [comment]
I'll try that, thank you. peace
