### ISSUE TITLE
Curl tests fail when offline

### ISSUE THREAD

**Issue by wigust** [soimort/translate-shell#221]
Hello,

Seems da788136d31dc04f85c898b3bb28fe009096bb4e has the same issue as #192 

`make test` requires internet connection because of Curl tests.

```
[FAIL] ( 1/1 ) TESTING curl()
assertEqual:  IS NOT EQUAL TO https://httpbin.org/get
[FAIL] ( 1/1 ) TESTING curlPost()
assertEqual:  IS NOT EQUAL TO https://httpbin.org/post
```

**Comment by soimort** [comment]
This is an intended behavior since I use it as a sanity check for the `curl` tool, which `trans` optionally depends on.

What do you expect then? (You can always skip those tests as if they don't exist.)

**Comment by wigust** [comment]
> What do you expect then?

I except a make target for testing which doesn't require a network access (it was a `test` target, as I understand).

> You can always skip those tests as if they don't exist.

Could you recommend a way to do it, please?

I think about removing `@include "test/TestUtils"` from `test/Test.awk` with a `sed` like utility in Guix.  It doesn't look great though, because e.g. Gentoo folks should do the same a different way as was mentioned in #192.

**Comment by soimort** [comment]
Not sure about your specific use case here, so my apologies if these questions sound too dull to you: 1. Are you a package maintainer or a user, and why would you need to run `make test` after all? 2. What is your environment, and why does it forbid tests from network access?

Here's my suggestions:

1. On Arch, the `makepkg --nocheck` option is used to skip all tests in PKGBUILD. I'm sure you'll find a similar option for other Linux distros.
2. In case you are packaging `trans` on a distro that forbids network access (e.g., Gentoo), I recommend simply adding a patch that delete [L33-L49](https://github.com/soimort/translate-shell/blob/develop/test/TestUtils.awk#L33-L49).

**Comment by wigust** [comment]
> Not sure about your specific use case here, so my apologies if these questions sound too dull to you: 

It's not dull, no problem.  Always welcome!

> 1. Are you a package maintainer or a user?

I'm a `translate-shell` user for a long time.  Also I maintain and write packages for [Guix](https://www.gnu.org/software/guix/).  Specifically we have a `guix refresh` command to upgrade a package recipe.  I want to upgrade it.  Upgrade from 0.9.6.4 to 0.9.6.7 is not possible without modifying `translate-shell` tests code.

> and why would you need to run make test after all?

We test all package recipes to insure they work as expected.  It's possible to push a package without tests too, but still we would like to test them if it's possible.

> 2. What is your environment?

Build processes in a chroot, under one of the ‘guixbuilder’ users. The chroot environment contains nothing but:

- a minimal ‘/dev’ directory, created mostly independently from the host ‘/dev’(2);

- the ‘/proc’ directory; it only shows the processes of the container since a separate PID name space is used;

- ‘/etc/passwd’ with an entry for the current user and an entry for user ‘nobody’;

- ‘/etc/group’ with an entry for the user’s group;

- ‘/etc/hosts’ with an entry that maps ‘localhost’ to ‘127.0.0.1’;

- a writable ‘/tmp’ directory.

https://www.gnu.org/software/guix/manual/html_node/Build-Environment-Setup.html

> and why does it forbid tests from network access?

Guix targets reproducible builds.  We cannot archive them with a network access, so all packages are build without it.

> Here's my suggestions:
>
> On Arch, the makepkg --nocheck option is used to skip all tests in PKGBUILD. I'm sure you'll find a similar option for other Linux distros.
>
> In case you are packaging trans on a distro that forbids network access (e.g., Gentoo), I recommend simply adding a patch that delete L33-L49.

OK, thank you.

Still it would be helpful to have a `make` target for testing without network access to decrease amount of the same work for multiple distributions, e.g. Gentoo, NixOS, GuixSD.  

Also Debian probably does without network access too, because they are one of the favorites of reproducible builds.  https://reproducible-builds.org/

**Comment by soimort** [comment]
Thanks for the detailed clarification! I had barely any knowledge about Guix and it's good to know how things are supposed to work under different systems.

Network-dependent tests are not going away, since they could be useful and gives Travis CI the possibility to shout out when something's broken. However, I have made it aware of an environment variable `$NETWORK_ACCESS`, so that it's possible to perform tests without any network now:

    $ make NETWORK_ACCESS=no test

Hope that helps. (this will take effect on the next release)

**Comment by wigust** [comment]
Thank you!  I succeeded to build and test bb9f32d3145125ba664b6b05bf0a2fd34108e9d2 

I'll close the issue.
