### ISSUE TITLE
Bing engine fails on large BLOB of text

### ISSUE THREAD

**Issue by AdrianSimionov** [soimort/translate-shell#222]
I noticed that the Bing engine fails to break a big BLOB into smaller part, while the Google one does not have this problem. Google engine has a limit on the text size, I assume you do multiple requests to overcome this limitation. It seems this does not happen for the Bing engine.

**Comment by soimort** [comment]
File input is always broken down into lines (for all engines). There is no special circumvention for Google Translate at all.

If something works for Google Translate but not Bing, then it means you've reached Bing's free quota of requests per IP per sec. (and that cannot be solved simply by breaking a file further.)
