### ISSUE TITLE
selection text from desktop and output to zenity  integration for ubuntu.

### ISSUE THREAD

**Issue by skypce** [soimort/translate-shell#226]
Hi all, thank you by your awesome script. I was made a little script that allow use your script from ubuntu desktop.
https://github.com/skypce/translating-from-any-language-using-translate-shell-script

**Comment by soimort** [comment]
Please feel free to use the wiki to share your own scripts / plugins based on translate-shell, like this one:
https://github.com/soimort/translate-shell/wiki/System-taskbar-(popup-notification-message)--integration

I'm closing this issue now.
