### ISSUE TITLE
Add wiki information to man page or package

### ISSUE THREAD

**Issue by Boruch-Baum** [soimort/translate-shell#227]
There is a lot of basic (and not-so-basic) information missing from the `man` page, but available on this project's github wiki. Those pages aren't included with the debian distribution package, and they wouldn't be included in a `git clone`.

Please consider either:

1] Including all the wiki pages into a single long but very useful `man` page.

2] Including some form of the wiki pages in the distributed code (and mention that in the `man` page!).

**Comment by soimort** [comment]
Please note that for any FOSS project like this, the man page and the wiki would serve for very different purposes: The man page is a formal description of the command-line utility itself, written authoritatively by the owner, providing quick references of what each argument does; On the other hand, the wiki is quite informal, ideally community-driven, editable by anyone, providing tutorials and tips & tricks possibly shared by other users.

The content of the wiki will not be included in the man page. I have, however, added a link to it in the man page, under the "Further Documentation" section.
