### ISSUE TITLE
Smarter arg parsing

### ISSUE THREAD

**Issue by guaka** [soimort/translate-shell#23]
On my shell I have to add backslashes to pass the language parameters e.g. `trs \{=de\} overmorgen`.

I guess `trs =de overmorgen` could be easily parsed as well. Or `trs fr=ar demain`, `trs es saber`.
All language codes are two letters and if someone wants to translate word that happens to be a language code they could fall back in the `{` syntax.

**Comment by soimort** [comment]
If you read it somewhere else about Google Translate CLI, please read the new `README.md` here, for it's now Translate Shell.

We don't prefer the curly bracket syntax now - for the very reason that it needs escaping on some shells.
The preferred syntax is `trans :de overmorgen`. Or you can use `trans =de overmorgen` as well.

**Comment by guaka** [comment]
ok, `trs \=de overmorgen` works (`:de` doesn't)

**Comment by soimort** [comment]
@guaka 

You are still using the deprecated Google Translate CLI. Please update it from the git repo.

**Comment by guaka** [comment]
Aha! お疲れ様!
