### ISSUE TITLE
Translate in WSL cannot work due to proxy problem

### ISSUE THREAD

**Issue by huieric** [soimort/translate-shell#231]
I have zsh and antigen installed in WSL. Then I install translate-shell with the following line added in `.zshrc`:
`antigen bundle soimort/translate-shell` 
Without any trouble, I sucessfully install the plugin:
![image](https://user-images.githubusercontent.com/16113041/40113156-0bdd1eac-593b-11e8-8544-b1e6df53535a.png)
But when I try to run `trans` or `translate` to get some usage information, I get nothing with it just running all the time. I guess it is because proxy don't work in WSL, but when I run shadowsocks in WSL as I used to do in Ubuntu, translate still not work.
![image](https://user-images.githubusercontent.com/16113041/40112982-6c327096-593a-11e8-81cd-e233c030ff24.png)
I don't know what's the problem. Any help?

But this can work: `gawk -f <(curl -Ls git.io/translate) -- -shell`
![image](https://user-images.githubusercontent.com/16113041/40114501-c27fbc24-593f-11e8-98aa-12fcdf559598.png)

**Comment by soimort** [comment]
`trans` consumes `/dev/stdin` by default. You need to send it something to translate.

Please take a look at the [README](https://github.com/soimort/translate-shell#translate-shell) first. The command to print usage information is `trans -h`.

**Comment by huieric** [comment]
@soimort Thanks. But I mean I get nothing when I translate something, eg. `trans :zh 'apple'` even after I wait for a long time. So I wonder if I miss something or something went wrong in WSL. I have spent half of the day trying to fix it but no advances. Thanks very much again!

**Comment by soimort** [comment]
Please attach the results of both
```
$ gawk -f <(curl -Ls git.io/translate) -- -debug :zh 'apple'
```
and
```
$ trans -debug :zh 'apple'
```

**Comment by huieric** [comment]
I'm sorry but after waiting for ten minutes I still cannot get any info or even a warning :
```
$ gawk -f <(curl -Ls git.io/translate) -- -debug :zh 'apple'
```
![image](https://user-images.githubusercontent.com/16113041/40119326-f1ef6900-594e-11e8-8b45-1488588099b2.png)
```
`$ trans -debug :zh 'apple'`
```
![image](https://user-images.githubusercontent.com/16113041/40119343-02564f8e-594f-11e8-8b4b-b063c8d10edb.png)
It just seems to keep running and running.
I check my internet connection : 
```
➜  ~ ping baidu.com
PING baidu.com (220.181.57.216) 56(84) bytes of data.
64 bytes from 220.181.57.216: icmp_seq=1 ttl=52 time=24.3 ms
64 bytes from 220.181.57.216: icmp_seq=2 ttl=52 time=23.8 ms
64 bytes from 220.181.57.216: icmp_seq=3 ttl=52 time=23.7 ms
64 bytes from 220.181.57.216: icmp_seq=4 ttl=52 time=49.1 ms
64 bytes from 220.181.57.216: icmp_seq=5 ttl=52 time=24.8 ms
64 bytes from 220.181.57.216: icmp_seq=6 ttl=52 time=53.6 ms
64 bytes from 220.181.57.216: icmp_seq=7 ttl=52 time=35.8 ms
64 bytes from 220.181.57.216: icmp_seq=8 ttl=52 time=26.6 ms
64 bytes from 220.181.57.216: icmp_seq=9 ttl=52 time=24.8 ms
^C
--- baidu.com ping statistics ---
9 packets transmitted, 9 received, 0% packet loss, time 8008ms
rtt min/avg/max/mdev = 23.708/31.880/53.613/11.049 ms
```
But nothing wrong with my internet connection.

**Comment by soimort** [comment]
What about `googleapis.com`?

```
$ curl http://googleapis.com
```

**Comment by huieric** [comment]
@soimort Just a moment ago I get these : 
```
➜  ~ gawk -f <(curl -Ls git.io/translate) -- -debug :zh 'apple'
[ERROR] Null response.
content = '''

'''
tokens =
ast =
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```
```
➜  ~ trans -debug :zh 'apple'
[ERROR] Null response.
content = '''

'''
tokens =
ast =
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```
and
```
➜  ~ curl http://googleapis.com
curl: (7) Failed to connect to googleapis.com port 80: Connection refused
```

**Comment by soimort** [comment]
```
➜  ~ curl http://googleapis.com
curl: (7) Failed to connect to googleapis.com port 80: Connection refused
```

that means you are blocked from accessing `googleapis.com`. I guess it's a regular GFW thing.

Configure your shadowsocks so that `curl http://googleapis.com` can work at least. In that case `trans` should work just as normal.

**Comment by huieric** [comment]
@soimort Are you sure the address is correct because I get 404 when I try to access it in Chrome in Windows?

**Comment by soimort** [comment]
1. If your Chrome is set up correctly with shadowsocks, 404 means you can reach Google's server (and it's normal, because they don't have any page hosted there). That is expected.
2. You should configure the environment of your `curl` to make it print a 404 page, too. "Connection refused" means it could not reach the server at all.

**Comment by huieric** [comment]
Again, I guess why `curl http://googleapis.com` cannot work is because of the proxy problem in WSL.
Following [How to use proxy in WSL? #2122](https://github.com/Microsoft/WSL/issues/2122), I add this alias in my `.zshrc` : 
```
alias socks='ALL_PROXY=socks5://127.0.0.1:1080/ \
        http_proxy=http://127.0.0.1:1080/ \
        https_proxy=http://127.0.0.1:1080/ \
        HTTP_PROXY=http://127.0.0.1:1080/ \
        HTTPS_PROXY=http://127.0.0.1:1080/'
```
Fortunately, `socks curl http://googleapis.com/` works as expected : 
```
➜  ~ socks curl http://googleapis.com/
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/</code> was not found on this server.  <ins>That’s all we know.</ins>
```
But the problem is that without `socks` I still get
```
➜  ~ curl http://googleapis.com/
curl: (7) Failed to connect to googleapis.com port 80: Connection refused
```
I cannot find a way to get out of it. Any suggestions?

**Comment by soimort** [comment]
I have no experience on WSL, but my guess is that it won't respect Windows' own global proxy setting at all (like a real Linux).

`trans`  cannot handle socks proxy directly. In this case, you may try to call it through [proxychains](https://github.com/rofl0r/proxychains-ng). (I assume proxychains works on WSL, hopefully.)

**Comment by huieric** [comment]
After installing [proxychains](https://github.com/rofl0r/proxychains-ng) and add my proxy in [ProxyList](https://github.com/rofl0r/proxychains-ng/blob/master/src/proxychains.conf#L111) in `proxychains.conf`, `trans :zh 'apple'` finally works fine : 
```
➜  ~ proxychains4 -q trans :zh 'apple'
apple
/ˈapəl/

苹果
(Píngguǒ)

Definitions of apple
[ English -> 简体中文 ]

noun
    苹果
        apple
    苹
        apple

apple
    苹果
```
Thanks very much for your patient help!
