### ISSUE TITLE
trans a web page failed

### ISSUE THREAD

**Issue by guanyuding** [soimort/translate-shell#232]
trans :fr http://www.w3.org/
sh: https://translate.google.com/translate?hl=zh-CN&sl=auto&tl=fr&u=http://www.w3.org/: No such file or directory

Do you have any suggestions for me？ Thanks~

**Comment by soimort** [comment]
Thanks for reporting the issue.

Please try out the latest commit (7f181da), which should work on most Linux distros and macOS.
