### ISSUE TITLE
[ERROR] Null response.

### ISSUE THREAD

**Issue by AnePill** [soimort/translate-shell#233]
# After the installation is complete, I try to translate。Then，there are tips for the following questions.

root@alex-Ubuntu:~#` trans :fr -b "Saluton, Mondo"

[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(`

**Comment by AnePill** [comment]
PS:
This is my second problem.The first problem is "I got an empty output. Should I report an issue to you?".  I have resolved by modifying the DNS.

**Comment by soimort** [comment]
Please follow the [guideline of reporting issues](https://github.com/soimort/translate-shell/blob/develop/CONTRIBUTING.md#how-to-report-an-issue) and attach the output of `trans -V`.

In this case, your `trans` is most likely to be outdated. Make sure to use `0.9.6.7`. (If the repository doesn't have that, then you need to install it manually.)
