### ISSUE TITLE
Encoding issue with DeepL on the Mac

### ISSUE THREAD

**Issue by tflo** [soimort/translate-shell#235]
When using the DeepL engine on macOS non-ASCII chars are still returned as Unicode code points instead of chars. (Version 0.9.6.7)

For details see [this comment](https://github.com/soimort/translate-shell/pull/204#issuecomment-352191382) from Dec 2017 and the follow-ups.

I’m opening a new issue because the pull request (where the other comments have been posted) is closed. Hope this is OK.

– Tom

**Comment by soimort** [comment]
It looks like the current approach of Unicode handling requires a reasonably up-to-date version of `bash` in path (since macOS's own `bash` is very stale you'll need to update it manually).

```
$ brew install bash

$ echo $BASH_VERSION
4.4.23(1)-release

$ trans -b /deepl :es 'Listen to me!'
¡Escúchame!
```

Let me know if this works.

**Comment by tflo** [comment]
Great! It works fine with bash 4.4.23.

Thanks for the hint!

–Tom
