### ISSUE TITLE
DeepL engine no longer working in Translation Shell

### ISSUE THREAD

**Issue by bowjest** [soimort/translate-shell#237]
As of yesterday I have found that the DeepL engine no longer seems to be working with Translation Shell. I had no problems working with it the day before.

I have called trans via both the command line and via a Keyboard Maestro macro, but have found it fails in both instances.

Here is my command line usage:

========================
trans -b -e deepl "Was ist das?"

(The output is just a blank line.)
========================

If called with Yandex, however, I get the following:

==========================
trans -b -e yandex "Was ist das?"
What's that?
==========================

Here is the output of trans -V:

==========================
Translate Shell       0.9.6.6-git:44cc21a

platform              Darwin
gawk (GNU Awk)        4.2.1
fribidi (GNU FriBidi) 1.0.1
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-256color
user locale           en_GB.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
==========================

I only use the command line on a "needs must" basis, so if I have inadvertently left out any required information, please ask and I will be happy to supply what I can.

Also, I am using a MacBook Pro (Yosemite 10.10.5), so if this is a known issue and has been resolved via an upgrade to a newer version of Translation Shell, I would appreciate someone pointing me to the upgrade. Again, I am not a constant GitHub/command line user, so have to reacquaint myself with things each time I need to investigate an issue.

Thanks,

Bowjest

**Comment by soimort** [comment]
I can confirm that DeepL Support just broke. https://travis-ci.org/soimort/translate-shell/jobs/399100712

Thanks for reporting this.

**Comment by bowjest** [comment]
No problem. I hope it's fixable. Trans is a great resource, particularly with DL support.

**Comment by bowjest** [comment]
Hi, soimort.

I've just seen your message above. How do we now fix this on our own systems? Do I/we (Mac users) need to run something like the following:

brew install translate-shell

and this will install the required updated file(s)?

Or should I just use something like TextWrangler and manually make the changes outlined in the case named above?

Thanks,

Bowjest

**Comment by soimort** [comment]
You can either install it directly [from git](https://github.com/soimort/translate-shell#option-3-from-git-recommended-for-seasoned-hackers), or try something like
```
$ brew reinstall --HEAD translate-shell
```

**Comment by bowjest** [comment]
Thanks. Appreciated.
