### ISSUE TITLE
trans is slow in bash

### ISSUE THREAD

**Issue by qwer1304** [soimort/translate-shell#238]
This is a continuation of issue 236.
I built translate for gawk (set target in Makefile to gawk) and execution speed is fast.
So it's bash that is slowing things down.
So I timed the two parts of bash, one where it reads in the program and the other where it invokes gawk to interpret it.
Most of the time is spent reading in the program.

**Comment by soimort** [comment]
Please be more specific about where things go wrong, especially since I can't observe any substantial performance degradation on other platforms.

If most time is spent reading in the program, then this inefficiency is actually about bash, in particular, your bash port on WSL or Cygwin. I'm afraid there's nothing I can do about it.

**Comment by qwer1304** [comment]
I confirmed that performance hit is due to bash poor performance in read statements
$ time read -r -d '' TRANS_PROGRAM < build/trans.awk

real    0m2.473s
user    0m0.109s
sys     0m2.313s

Here's an alternative implementation of heredoc (from https://stackoverflow.com/questions/1167746/how-to-assign-a-heredoc-value-to-a-variable-in-bash scroll to 2nd answer) that uses cat instead and that is much faster.

VAR=$(cat <<'END_HEREDOC'
abc'asdf"
$(dont-execute-this)
foo"bar"''
END_HEREDOC
)

The difference is that you need to add a ')' after you output EOF

heredoc with cat
$ time build/trans -b -t ru hello
Здравствуйте

real    0m1.691s
user    0m0.938s
sys     0m0.469s

heredoc with read
$ time build/trans -b -t ru hello
Здравствуйте

real    0m4.268s
user    0m1.031s
sys     0m2.828s

There's a problem though with a \ at the end of a line: bash command substitution treats this as line continuation eventhough 'EOF' is used, so you end up with RSins( instead of RS\ins(
zsh doesn't have such an issue
I didn't find a way to change the line continuation character in bash
Working through an intermediate file works though in bash, ie:
cat >zz.tmp<<'EOF'
...
...
EOF
variable=$(cat zz.tmp)
