### ISSUE TITLE
Translation with DeepL no longer works

### ISSUE THREAD

**Issue by rememberYou** [soimort/translate-shell#239]
First of all, a big thank you for this useful package.

I allow myself to open this issue because I haven't been able to get the translation with [DeepL](https://www.deepl.com/translator) for a few days now.

For example, you can reproduce this bug with: `trans --brief :en -e deepl "Bonjour"`

**NOTE:** if I don't use DeepL as a translation engine, it works perfectly.

I can provide some additional information if necessary.

**Comment by soimort** [comment]
Duplicate of #237, which is already fixed by 2399bb7.
