### ISSUE TITLE
Language name for NL is Nederlands, not Deutsch

### ISSUE THREAD

**Issue by cimm** [soimort/translate-shell#24]
When translating a Dutch word to French or Spanish the language name shown in the details is `Deutsch` (see output below) this is wrong, the correct name for the `NL` ISO code is `Nederlands`. It's correct when translating from Dutch to English or Hungarian though.

```
$ trans nl:fr hallo
bonjour

Translations of hallo
(Deutsch ➔ Français)
hallo(bonjour)
```

The correct output should be:

```
(Nederlands ➔ Français)
```

German and Dutch can be confusing, they are both different languages but their English and native names are confusing so here is a little reminder:

| ISO | English name | Native name | Spoken |
| --- | --- | --- | --- |
| DE | German | Deutsch | in Germany |
| NL | Dutch | Nederlands | in the Netherlands and Belgium |

**Comment by soimort** [comment]
As you might already know, `hallo` is a valid vocabulary in both German and Dutch - when retrieving the result, both language codes are returned but it seems the first one in the list (`de`) is used for output, instead of the one specified by the user.

Thanks for the report and I'll fix that soon.

**Comment by cimm** [comment]
Wow, that was fast. Thank you!
