### ISSUE TITLE
Some problem in Ubuntu18.06

### ISSUE THREAD

**Issue by NERD-k** [soimort/translate-shell#241]
if i input trans 'any words'
it return:
```
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```

only `gawk -f <(curl -Ls git.io/translate) -- -shell` can work.

**Comment by soimort** [comment]
Please update to the latest version then.

**Comment by NERD-k** [comment]
That version is 0.9.6.6, it can work on Fedora29.
