### ISSUE TITLE
Cannot open two way pipe

### ISSUE THREAD

**Issue by str3am** [soimort/translate-shell#242]
Today when I use it, it gives me such an error

<img width="649" alt="screen shot 2018-07-20 at 22 39 52" src="https://user-images.githubusercontent.com/33783820/43008876-c9a64fe2-8c6e-11e8-96e3-4143796f637a.png">

**Comment by soimort** [comment]
"Connection refused" indicates a network error. Please make sure you have access to googleapis.com (through a proxy or alike).
