### ISSUE TITLE
Will not apply HSTS

### ISSUE THREAD

**Issue by Elshanazadi** [soimort/translate-shell#243]
I was running a script which was translating a sentence through all languages quite for a long time , but then now after 20 translations it stops translating and I get an error :  wget git.io/trans
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/elshan/.wget-hsts'. HSTS will be disabled.
I appreciate if you help me

**Comment by soimort** [comment]
I believe this is a problem of wget rather than translate-shell. Also, why would you need to run `wget git.io/trans` repeatedly?

**Comment by Elshanazadi** [comment]
![image](https://user-images.githubusercontent.com/38067920/43051954-d95c7f98-8e20-11e8-8391-7cda30507456.png)

I don't know exactly what is the issue, but this is what happens (after almost 20 times ) there is no result for translation. (photo)
