### ISSUE TITLE
all translate engines does not work

### ISSUE THREAD

**Issue by man0xff** [soimort/translate-shell#247]
next command does not output anything:

    ./trans -S | cut -c3- | xargs -n1 -I@ ./trans -e@ :ru top

but initially after downloading the tool i managed to translate one time.

Translate Shell       0.9.6.7-release

platform              Linux
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) 0.19.7
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-256color
user locale           en_US (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

**Comment by soimort** [comment]
You should leave a space between `-e` and its parameter:
`./trans -e @`

Also, please narrow the problem down to one specific engine, e.g., Google or Bing. Of course, if this tool is abused too much (like being put into an automated script), they might block the suspected IP address for a time period. (which is a common reason why it no longer works.)

**Comment by man0xff** [comment]
thanks, it works now
