### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by ErraticMaker** [soimort/translate-shell#25]
I'm getting this error when I try to install the stable version

```
$ make install 
gawk: build.awk:3: error: can't open source file `include/Commons' for reading (No such file or directory)
make: *** [trans] Error 1
```

I have `gawk` version `4.0.1` in a new Ubuntu Gnome 14.04 installation.

The `include` folder is there, as it is the Commons.awk file inside it.

**Note**: I don't know (g)awk

**Comment by soimort** [comment]
Thanks for reporting this.

The build script had a compatibility issue with `gawk 4.0` (filename extensions must not be omitted) - I'm using the latest build of `gawk` (`4.1`) so I wasn't aware of it.

It should be fixed now.
