### ISSUE TITLE
Privacy conditions

### ISSUE THREAD

**Issue by KebabLord** [soimort/translate-shell#256]
I'm wondering, if it's running in realtime then is it means that related search engines can get our terminal info? I mean I don't want my personel/os/terminal data to be reachable or can be collected by those engine companies,
what are the privacy conditions?

**Comment by soimort** [comment]
`trans` only sends **what you want it to translate** as an HTTP request to, like, Google Translate's server. The requests do not contain more information than the text you translate.

Your data will only be collected if you try to translate them.
