### ISSUE TITLE
bug?not work on ubuntu 14.04

### ISSUE THREAD

**Issue by fenix-soft** [soimort/translate-shell#261]
hi guys, I have a problem .. translate-shell does not work. Premise are on ubuntu 14.04 and up to a few months ago everything worked with the version (0.9.6.6), I regularly update the packages. Today I needed to use the rogram (0.9.6.6) did not work with any engine, then I tried if there were updates in fact he told me that there was 0.9.6.8. I installed but it does not continue to go with any engine. It is also a program that I use often so I do not think I'm wrong using the syntax ... I even used the examples of use but the result is the same ...
can anyone check to see if it works to understand where the problem is? if it's my system or program? Thanks for the help!
I attach the printed version to the terminal:

`
fenix@fenix-pc:~$ trans -V
Translate Shell       0.9.6.8-release

platform              Linux
gawk (GNU Awk)        4.0.1
fribidi (GNU FriBidi) 0.19.6
audio player          mpv --no-config
terminal pager        less
terminal type         xterm
user locale           it_IT (Italian)
home language         it
source language       auto
target language       it
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
`

**Comment by soimort** [comment]
What do you exactly mean by "did not work"? 

Please post the output of

```
$ trans -debug 'hello world'
```

**Comment by fenix-soft** [comment]
guys I do not know what to say ... it will be a bad day? however changing the user agent with the -u option works ... I made other attempts by restoring the default user agent and now it works regularly! .. try with different engines and now it works! maybe dsn problem? mah .. seems to work ... same syntax

  thanks anyway.

` trans -debug 'hello world'
  33 bytes > HTTP/1.1 503 Service Unavailable
  36 bytes > Date: Tue, 23 Oct 2018 15:27:57 GMT
  17 bytes > Pragma: no-cache
  39 bytes > Expires: Fri, 01 Jan 1990 00:00:00 GMT
  51 bytes > Cache-Control: no-store, no-cache, must-revalidate
  24 bytes > Content-Type: text/html
  30 bytes > Server: HTTP server (unknown)
  21 bytes > Content-Length: 2363
  32 bytes > X-XSS-Protection: 1; mode=block
  18 bytes > Connection: close
   1 bytes > 
  63 bytes > <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
  16 bytes > <html DIR="LTR">
 382 bytes > <head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>http://translate.googleapis.com/translate_a/single?client=gtx&amp;ie=UTF-8&amp;oe=UTF-8&amp;dt=bd&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;dt=at&amp;dt=qca&amp;sl=auto&amp;tl=it&amp;hl=it&amp;q=hello%20world</title></head>
 177 bytes > <body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;" onload="e=document.getElementById('captcha');if(e){e.focus();}">
  30 bytes > <div style="max-width:400px;">
  68 bytes > <hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
  29 bytes > <div style="font-size:13px;">
 261 bytes > I nostri sistemi hanno rilevato un traffico insolito proveniente dalla rete del tuo computer. Prova a inviare nuovamente la tua richiesta più tardi. <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">A che cosa è dovuto?</a><br><br>
 115 bytes > <div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
 858 bytes > Questa pagina viene visualizzata quando Google rileva automaticamente delle richieste provenienti dalla rete del tuo computer che apparentemente violano i <a href="//www.google.com/policies/terms/">Termini di servizio</a>. Il blocco scadrà quando tali richieste saranno terminate. <br><br>Questo traffico potrebbe essere stato inviato da software dannoso, da un plug-in del browser o da script che invia richieste automatiche. Se condividi la connessione di rete, rivolgiti all'amministratore per assistenza: la responsabilità potrebbe essere di un altro computer che utilizza lo stesso indirizzo IP. <a href="//support.google.com/websearch/answer/86640">Ulteriori informazioni</a><br><br>A volte questa pagina viene visualizzata se stai impiegando termini avanzati che vengono solitamente utilizzati dai robot o se stai inviando richieste molto rapidamente.
   0 bytes > 
  10 bytes > </div><br>
 308 bytes > Indirizzo IP: 62.10.30.148<br>Data: 2018-10-23T15:27:57Z<br>URL: http://translate.googleapis.com/translate_a/single?client=gtx&amp;ie=UTF-8&amp;oe=UTF-8&amp;dt=bd&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;dt=at&amp;dt=qca&amp;sl=auto&amp;tl=it&amp;hl=it&amp;q=hello%20world<br>
  12 bytes > </div></div>
   7 bytes > </body>
   7 bytes > </html>
content = '''
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html DIR="LTR">
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>http://translate.googleapis.com/translate_a/single?client=gtx&amp;ie=UTF-8&amp;oe=UTF-8&amp;dt=bd&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;dt=at&amp;dt=qca&amp;sl=auto&amp;tl=it&amp;hl=it&amp;q=hello%20world</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;" onload="e=document.getElementById('captcha');if(e){e.focus();}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<div style="font-size:13px;">
I nostri sistemi hanno rilevato un traffico insolito proveniente dalla rete del tuo computer. Prova a inviare nuovamente la tua richiesta più tardi. <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">A che cosa è dovuto?</a><br><br>
<div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
Questa pagina viene visualizzata quando Google rileva automaticamente delle richieste provenienti dalla rete del tuo computer che apparentemente violano i <a href="//www.google.com/policies/terms/">Termini di servizio</a>. Il blocco scadrà quando tali richieste saranno terminate. <br><br>Questo traffico potrebbe essere stato inviato da software dannoso, da un plug-in del browser o da script che invia richieste automatiche. Se condividi la connessione di rete, rivolgiti all'amministratore per assistenza: la responsabilità potrebbe essere di un altro computer che utilizza lo stesso indirizzo IP. <a href="//support.google.com/websearch/answer/86640">Ulteriori informazioni</a><br><br>A volte questa pagina viene visualizzata se stai impiegando termini avanzati che vengono solitamente utilizzati dai robot o se stai inviando richieste molto rapidamente.

</div><br>
Indirizzo IP: 62.10.30.148<br>Data: 2018-10-23T15:27:57Z<br>URL: http://translate.googleapis.com/translate_a/single?client=gtx&amp;ie=UTF-8&amp;oe=UTF-8&amp;dt=bd&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;dt=at&amp;dt=qca&amp;sl=auto&amp;tl=it&amp;hl=it&amp;q=hello%20world<br>
</div></div>
</body>
</html>
'''
tokens = ["<!DOCTYPE", "html", "PUBLIC", "\"-//W3C//DTD HTML 4.01 Transitional//EN\"", ">", "<html", "DIR=", "\"LTR\"", ">", "<head><meta", "http-equiv=", "\"content-type\"", "content=", "\"text/html; charset=utf-8\"", "><meta", "name=", "\"viewport\"", "content=", "\"initial-scale=1\"", "><title>http:", "<body", "style=", "\"font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;\"", "onload=", "\"e=document.getElementById('captcha');if(e){e.focus();}\"", ">", "<div", "style=", "\"max-width:400px;\"", ">", "<hr", "noshade", "size=", "\"1\"", "style=", "\"color:#ccc; background-color:#ccc;\"", "><br>", "<div", "style=", "\"font-size:13px;\"", ">", "I", "nostri", "sistemi", "hanno", "rilevato", "un", "traffico", "insolito", "proveniente", "dalla", "rete", "del", "tuo", "computer", ".", "Prova", "a", "inviare", "nuovamente", "la", "tua", "richiesta", "più", "tardi", ".", "<a", "href=", "\"#\"", "onclick=", "\"document.getElementById('infoDiv').style.display='block';\"", ">A", "che", "cosa", "è", "dovuto?</a><br><br>", "<div", "id=", "\"infoDiv\"", "style=", "\"display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;\"", ">", "Questa", "pagina", "viene", "visualizzata", "quando", "Google", "rileva", "automaticamente", "delle", "richieste", "provenienti", "dalla", "rete", "del", "tuo", "computer", "che", "apparentemente", "violano", "i", "<a", "href=", "\"//www.google.com/policies/terms/\"", ">Termini", "di", "servizio</a>", ".", "Il", "blocco", "scadrà", "quando", "tali", "richieste", "saranno", "terminate", ".", "<br><br>Questo", "traffico", "potrebbe", "essere", "stato", "inviato", "da", "software", "dannoso", ",", "da", "un", "plug-in", "del", "browser", "o", "da", "script", "che", "invia", "richieste", "automatiche", ".", "Se", "condividi", "la", "connessione", "di", "rete", ",", "rivolgiti", "all'amministratore", "per", "assistenza:", "la", "responsabilità", "potrebbe", "essere", "di", "un", "altro", "computer", "che", "utilizza", "lo", "stesso", "indirizzo", "IP", ".", "<a", "href=", "\"//support.google.com/websearch/answer/86640\"", ">Ulteriori", "informazioni</a><br><br>A", "volte", "questa", "pagina", "viene", "visualizzata", "se", "stai", "impiegando", "termini", "avanzati", "che", "vengono", "solitamente", "utilizzati", "dai", "robot", "o", "se", "stai", "inviando", "richieste", "molto", "rapidamente", ".", "</div><br>", "Indirizzo", "IP:", "62.10", ".30", ".148", "<br>Data:", "2018", "-10", "-23", "T", "15", ":", "27", ":", "57", "Z<br>URL:", "http:", "</div></div>", "</body>", "</html>"]
ast = {
"0"	"dannoso"
"1"	"rete"
"2"	"</html>"
}
-- display original text & phonetics


-- display major translation & phonetics
`

**Comment by fenix-soft** [comment]
sorry I was wrong button and I closed the discussion .. comuque the riapro maybe need and I debug

`trans -debug 'hello world'
  33 bytes > HTTP/1.1 503 Service Unavailable
  36 bytes > Date: Tue, 23 Oct 2018 15:33:52 GMT
  17 bytes > Pragma: no-cache
  39 bytes > Expires: Fri, 01 Jan 1990 00:00:00 GMT
  51 bytes > Cache-Control: no-store, no-cache, must-revalidate
  24 bytes > Content-Type: text/html
  30 bytes > Server: HTTP server (unknown)
  21 bytes > Content-Length: 2363
  32 bytes > X-XSS-Protection: 1; mode=block
  18 bytes > Connection: close
   1 bytes > 
  63 bytes > <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
  16 bytes > <html DIR="LTR">
 382 bytes > <head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>http://translate.googleapis.com/translate_a/single?client=gtx&amp;ie=UTF-8&amp;oe=UTF-8&amp;dt=bd&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;dt=at&amp;dt=qca&amp;sl=auto&amp;tl=it&amp;hl=it&amp;q=hello%20world</title></head>
 177 bytes > <body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;" onload="e=document.getElementById('captcha');if(e){e.focus();}">
  30 bytes > <div style="max-width:400px;">
  68 bytes > <hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
  29 bytes > <div style="font-size:13px;">
 261 bytes > I nostri sistemi hanno rilevato un traffico insolito proveniente dalla rete del tuo computer. Prova a inviare nuovamente la tua richiesta più tardi. <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">A che cosa è dovuto?</a><br><br>
 115 bytes > <div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
 858 bytes > Questa pagina viene visualizzata quando Google rileva automaticamente delle richieste provenienti dalla rete del tuo computer che apparentemente violano i <a href="//www.google.com/policies/terms/">Termini di servizio</a>. Il blocco scadrà quando tali richieste saranno terminate. <br><br>Questo traffico potrebbe essere stato inviato da software dannoso, da un plug-in del browser o da script che invia richieste automatiche. Se condividi la connessione di rete, rivolgiti all'amministratore per assistenza: la responsabilità potrebbe essere di un altro computer che utilizza lo stesso indirizzo IP. <a href="//support.google.com/websearch/answer/86640">Ulteriori informazioni</a><br><br>A volte questa pagina viene visualizzata se stai impiegando termini avanzati che vengono solitamente utilizzati dai robot o se stai inviando richieste molto rapidamente.
   0 bytes > 
  10 bytes > </div><br>
 308 bytes > Indirizzo IP: 62.10.30.148<br>Data: 2018-10-23T15:33:52Z<br>URL: http://translate.googleapis.com/translate_a/single?client=gtx&amp;ie=UTF-8&amp;oe=UTF-8&amp;dt=bd&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;dt=at&amp;dt=qca&amp;sl=auto&amp;tl=it&amp;hl=it&amp;q=hello%20world<br>
  12 bytes > </div></div>
   7 bytes > </body>
   7 bytes > </html>
content = '''
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html DIR="LTR">
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>http://translate.googleapis.com/translate_a/single?client=gtx&amp;ie=UTF-8&amp;oe=UTF-8&amp;dt=bd&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;dt=at&amp;dt=qca&amp;sl=auto&amp;tl=it&amp;hl=it&amp;q=hello%20world</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;" onload="e=document.getElementById('captcha');if(e){e.focus();}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<div style="font-size:13px;">
I nostri sistemi hanno rilevato un traffico insolito proveniente dalla rete del tuo computer. Prova a inviare nuovamente la tua richiesta più tardi. <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">A che cosa è dovuto?</a><br><br>
<div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
Questa pagina viene visualizzata quando Google rileva automaticamente delle richieste provenienti dalla rete del tuo computer che apparentemente violano i <a href="//www.google.com/policies/terms/">Termini di servizio</a>. Il blocco scadrà quando tali richieste saranno terminate. <br><br>Questo traffico potrebbe essere stato inviato da software dannoso, da un plug-in del browser o da script che invia richieste automatiche. Se condividi la connessione di rete, rivolgiti all'amministratore per assistenza: la responsabilità potrebbe essere di un altro computer che utilizza lo stesso indirizzo IP. <a href="//support.google.com/websearch/answer/86640">Ulteriori informazioni</a><br><br>A volte questa pagina viene visualizzata se stai impiegando termini avanzati che vengono solitamente utilizzati dai robot o se stai inviando richieste molto rapidamente.

</div><br>
Indirizzo IP: 62.10.30.148<br>Data: 2018-10-23T15:33:52Z<br>URL: http://translate.googleapis.com/translate_a/single?client=gtx&amp;ie=UTF-8&amp;oe=UTF-8&amp;dt=bd&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;dt=at&amp;dt=qca&amp;sl=auto&amp;tl=it&amp;hl=it&amp;q=hello%20world<br>
</div></div>
</body>
</html>
'''
tokens = ["<!DOCTYPE", "html", "PUBLIC", "\"-//W3C//DTD HTML 4.01 Transitional//EN\"", ">", "<html", "DIR=", "\"LTR\"", ">", "<head><meta", "http-equiv=", "\"content-type\"", "content=", "\"text/html; charset=utf-8\"", "><meta", "name=", "\"viewport\"", "content=", "\"initial-scale=1\"", "><title>http:", "<body", "style=", "\"font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;\"", "onload=", "\"e=document.getElementById('captcha');if(e){e.focus();}\"", ">", "<div", "style=", "\"max-width:400px;\"", ">", "<hr", "noshade", "size=", "\"1\"", "style=", "\"color:#ccc; background-color:#ccc;\"", "><br>", "<div", "style=", "\"font-size:13px;\"", ">", "I", "nostri", "sistemi", "hanno", "rilevato", "un", "traffico", "insolito", "proveniente", "dalla", "rete", "del", "tuo", "computer", ".", "Prova", "a", "inviare", "nuovamente", "la", "tua", "richiesta", "più", "tardi", ".", "<a", "href=", "\"#\"", "onclick=", "\"document.getElementById('infoDiv').style.display='block';\"", ">A", "che", "cosa", "è", "dovuto?</a><br><br>", "<div", "id=", "\"infoDiv\"", "style=", "\"display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;\"", ">", "Questa", "pagina", "viene", "visualizzata", "quando", "Google", "rileva", "automaticamente", "delle", "richieste", "provenienti", "dalla", "rete", "del", "tuo", "computer", "che", "apparentemente", "violano", "i", "<a", "href=", "\"//www.google.com/policies/terms/\"", ">Termini", "di", "servizio</a>", ".", "Il", "blocco", "scadrà", "quando", "tali", "richieste", "saranno", "terminate", ".", "<br><br>Questo", "traffico", "potrebbe", "essere", "stato", "inviato", "da", "software", "dannoso", ",", "da", "un", "plug-in", "del", "browser", "o", "da", "script", "che", "invia", "richieste", "automatiche", ".", "Se", "condividi", "la", "connessione", "di", "rete", ",", "rivolgiti", "all'amministratore", "per", "assistenza:", "la", "responsabilità", "potrebbe", "essere", "di", "un", "altro", "computer", "che", "utilizza", "lo", "stesso", "indirizzo", "IP", ".", "<a", "href=", "\"//support.google.com/websearch/answer/86640\"", ">Ulteriori", "informazioni</a><br><br>A", "volte", "questa", "pagina", "viene", "visualizzata", "se", "stai", "impiegando", "termini", "avanzati", "che", "vengono", "solitamente", "utilizzati", "dai", "robot", "o", "se", "stai", "inviando", "richieste", "molto", "rapidamente", ".", "</div><br>", "Indirizzo", "IP:", "62.10", ".30", ".148", "<br>Data:", "2018", "-10", "-23", "T", "15", ":", "33", ":", "52", "Z<br>URL:", "http:", "</div></div>", "</body>", "</html>"]
ast = {
"0"	"dannoso"
"1"	"rete"
"2"	"</html>"
}
-- display original text & phonetics


-- display major translation & phonetics

`

**Comment by Gutem** [comment]
@soimort Please, reopen.
Same problem here.

**Comment by Atavic** [comment]
> 32 bytes > X-XSS-Protection: 1; mode=block

System's security closes the network request.

**Comment by miranche** [comment]
@soimort Same issue here. I've just downloaded the utility and it hasn't even worked once. Running it with -debug gives the same 503 response and the X-XSS-Protection message, and I haven't accessed the Google translate server recently at all to my knowledge.

Is there a workaround? @fenix-soft, what values of -user-agent worked for you?

It seems that a number of users have experienced a similar issue in the last month -- has Google changed anything?

Thank you!
