### ISSUE TITLE
"-show-alternatives n " output nothing [empty translation]

### ISSUE THREAD

**Issue by qsimpleq** [soimort/translate-shell#262]
`$ trans -show-alternatives y -hl ru -sl auto -tl ru -show-original n -show-original-phonetics n -show-translation n -show-prompt-message n -show-languages n -indent 4 "Arrakis, the planet known as Dune, is forever his place."`
> Arrakis, the planet known as Dune, is forever his place.
    Арракис, планета, известная как Дюна, навсегда его место., Arrakis, планета известна как Дюна, навсегда его место.

`$ trans -show-alternatives n -hl ru -sl auto -tl ru -show-original n -show-original-phonetics n -show-translation n -show-prompt-message n -show-languages n -indent 4 "Arrakis, the planet known as Dune, is forever his place."`
> Nothing in output

In same time, -dump is absolutly identically
`$ trans -show-alternatives n -dump -hl ru -sl auto -tl ru -show-original n -show-original-phonetics n -show-translation n -show-prompt-message n -show-languages n -indent 4 "Arrakis, the planet known as Dune, is forever his place."`
> [[["Арракис, планета, известная как Дюна, навсегда его место.","Arrakis, the planet known as Dune, is forever his place.",null,null,3],[null,null,"Arrakis, planeta, izvestnaya kak Dyuna, navsegda yego mesto."]],null,"en",null,null,[["Arrakis, the planet known as Dune, is forever his place.",null,[["Арракис, планета, известная как Дюна, навсегда его место.",0,true,false],["Arrakis, планета известна как Дюна, навсегда его место.",0,true,false]],[[0,56]],"Arrakis, the planet known as Dune, is forever his place.",0,0]],1,null,[["en"],null,[1],["en"]]]

**Comment by soimort** [comment]
This is because you already set `-show-translation n`, and if you suppress alternatives by `-show-alternatives n` at the same time, clearly nothing will be shown.
