### ISSUE TITLE
It seems to be a problem when translating characters with html tags

### ISSUE THREAD

**Issue by Whosc** [soimort/translate-shell#263]
Hi,
Great tool, but I am having a small problem. 
It seems to be a problem when translating characters with html tags.
when i run

`trans -t ja -b '<a class="class" style="color:#fff;" href="https://www.bai.com" id="id" > hair</a><p> If you have a bug or an idea, read the contributing guidelines before opening an issue.</p>'`

then i get 

`<a class = "class" style = "color：#fff;"バグやアイデアがある場合は、問題を開く前に寄稿しているガイドラインをお読みください。</ p> <p> <href = "https://www.bai.com" id = "id"`

Please advise! Thank you again for a wonderful translate tool!

**Comment by soimort** [comment]
What is your problem, exactly?

Try using https://translate.google.com/ and see if there's any difference.

**Comment by Whosc** [comment]
Thank you for your reply,the two results are the same.
The problem is that the html tags in the results after the translation are out of order.
Is there any way to keep the translated html tag order normal?
Thanks again.

![image](https://user-images.githubusercontent.com/16221204/48523603-193f3780-e8b8-11e8-9a5e-16dbeaa76f2c.png)

**Comment by soimort** [comment]
This might be something you need to fix by yourself -- `trans` is just a faithful interface of Google Translate, etc., not a translator on its own.

The suggestion is to parse HTML and translate only the parts that are needed.
