### ISSUE TITLE
not translating

### ISSUE THREAD

**Issue by kurokirasama** [soimort/translate-shell#264]
hello,

i just downloaded the `trans` executable, and in my first tests was working fine, and then it suddenly stopped working

`trans :es hello`

shows only one empty line.

I tried the github version, but I got the same result.

I'm on ubuntu 18.04.

**Comment by soimort** [comment]
You've probably exceeded the quota and got blocked by Google's server.

**Comment by kurokirasama** [comment]
ooook!
