### ISSUE TITLE
Oops! Something went wrong and I can't transla te it for you :(

### ISSUE THREAD

**Issue by butterflyfirefly101** [soimort/translate-shell#265]
Translate Shell       0.9.6.8-git:c293d27

platform              Linux
gawk (GNU Awk)        4.1.4
fribidi (GNU FriBidi) 0.19.7
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64)
AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safa
ri/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/trans
late-shell/issues

###

rangel90@localhost:~$ trans Test --debug
[ERROR] Null response.
content = '''

'''
tokens =
ast =
[ERROR] Oops! Something went wrong and I can't transla
te it for you :(
### 

Using Ubuntu

**Comment by soimort** [comment]
You've probably exceeded the quota and got blocked by Google's server.
