### ISSUE TITLE
Interactive mode with pager behaving strangely

### ISSUE THREAD

**Issue by isamert** [soimort/translate-shell#266]
If I run `trans` with `-interactive -v` it behaves really strange. Generally every one out of three keystrokes goes to pager and I don't know where the rest goes. There are other inconsistencies that I am unable to describe (I can give more details if you cannot reproduce the issue).

Here is my `trans -V`:
```
Translate Shell       0.9.6.8-git:f2edc13

platform              Linux
gawk (GNU Awk)        4.2.1
fribidi (GNU FriBidi) 1.0.5
audio player          mpv --no-config
terminal pager        less
terminal type         st-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]
```

The thing I expect with `-interactive -v` combination is when I press Enter it simply shows translation in a pager, when I close the pager, it just simply needs to return to the interactive mode.

Thanks for the great work on this tool btw, it's an essential part of my workflow.

**Comment by soimort** [comment]
Thanks for the bug report.

It should be fixed in the latest `develop` branch now.
