### ISSUE TITLE
Bing excess IG generation

### ISSUE THREAD

**Issue by Shatur** [soimort/translate-shell#267]
For Bing, an generated [IG](https://github.com/soimort/translate-shell/blob/0fd54309830f36f987f82e3df6f1c4b92fb56215/include/Translators/BingTranslator.awk#L15) not required. You can simply use all links without IG:
`/tspeak?&IG=...` -> `/tspeak`
`/ttranslate?&IG=...` -> `/ttranslate`
`/ttranslationlookup?&IG=...` -> `/ttranslationlookup`
and so on, they will work.
And also you do not need cookies.

**Comment by soimort** [comment]
Thanks for the reminder!
