### ISSUE TITLE
DeepL no longer working with Translate-Shell

### ISSUE THREAD

**Issue by bowjest** [soimort/translate-shell#268]
As of yesterday I have found that the DeepL engine no longer seems to be working with Translate-Shell.

This was also an issue in July of this year (2018) 

I have called trans via both the command line and via a Keyboard Maestro macro, but have found it fails in both instances.

Here is my command line usage:

========================
trans -b -e deepl "Was ist das?"

(The output is just a blank line.)

If called with Yandex, however, I get the following:

==========================
trans -b -e yandex "Was ist das?"
What's that?

I have updated my Homebrew installation and upgraded Translate-Shell, but the problem still persists.

Here is the output of trans -V:

============================
Translate Shell       0.9.6.8-git:0fd5430

platform              Darwin
gawk (GNU Awk)        4.2.1
fribidi (GNU FriBidi) 1.0.5
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-256color
user locale           en_GB.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
============================

Hopefully this isn't a major issue.

Many thanks,

Bowjest

**Comment by ad-si** [comment]
For me, it always uses emoji instead of the specified language:

```txt
$ trans -engine=deepl de:en Test
Test



[ Emoji -> English ]
```

**Comment by bowjest** [comment]
Wow. That is weird. I just tried ad-si's example above (and a few variations) and I now get the same thing (sort of):

trans -e deepl "Wo bist du?"
Wo bist du?

[ Emoji -> English ]

Deus ex machina? ;)

**Comment by soimort** [comment]
FYI, DeepL is proactively blocking unauthorized access on a per IP basis. Once you get blocked, even the web interface will fail you for hours or so. Just don't use that engine now.

![screenshot from 2018-12-19 02-13-29](https://user-images.githubusercontent.com/342945/50194404-04ccdf80-033b-11e9-8f06-77d7a5f409d5.png)

**Comment by bowjest** [comment]
Thanks, soimort. Adieu, DeepL.

**Comment by soimort** [comment]
Support for DeepL will be abandoned in the next release.
    
DeepL is using all kinds of inscrutable conventions to prevent HTTP simulations: Such as requiring a redundant whitespace in the request string `"method": "LMT_split_into_sentences"`; together with some mysterious server-side timestamp and id verification. Upon receiving an invalid request, it might just block your IP for ages, which makes it very high-maintenance to hack.

It might be possible to find a way, but it won't worth my time; anyway, they might be already watching this repo (which is open-source) for countermeasures, so our asses are broken too easily.

**Comment by flobee** [comment]
> Support for DeepL will be abandoned in the next release.
> 
> DeepL is using all kinds of inscrutable conventions to prevent HTTP simulations: Such as requiring a redundant whitespace in the request string `"method": "LMT_split_into_sentences"`; together with some mysterious server-side timestamp and id verification. Upon receiving an invalid request, it might just block your IP for ages, which makes it very high-maintenance to hack.
> 
> It might be possible to find a way, but it won't worth my time; anyway, they might be already watching this repo (which is open-source) for countermeasures, so our asses are broken too easily.


Maybe the time is over to not have deepl on board? 
now i see it in alot of plattforms on the web using it/deepl (e.g mastodon). 
Or is this issue still up to not include deepl?

I was looking for a translation tool in my debian (again). 
i just want ONE installation. and switch to an engin i can have w/o internet. 
and i dont want all that extras packages other software offer to have deepl on board. hmm

idea: maybe someone can bundle an app as extension for this project to have it on a lot of linux distros ?

**Comment by soimort** [comment]
> Maybe the time is over to not have deepl on board? now i see it in alot of plattforms on the web using it/deepl (e.g mastodon). Or is this issue still up to not include deepl?
> 
> I was looking for a translation tool in my debian (again). i just want ONE installation. and switch to an engin i can have w/o internet. and i dont want all that extras packages other software offer to have deepl on board. hmm
> 
> idea: maybe someone can bundle an app as extension for this project to have it on a lot of linux distros ?

In order to use deepl on a Mastodon instance, it needs to provide an API key first; but that's not the case for translate-shell.

Just to be clear, this issue is up to *not include deepl **in an API-free way***, as I can no longer afford the time personally to hack & circumvent the anti-scraping technique. If anyone is unhappy about that, they are most welcome to hack it themselves and/or submit a PR.

Whether we should include deepl **for people who can provide their own API keys is open for discussion (#396, #457)**. So please upvote / comment there if you like the idea.
