### ISSUE TITLE
Width

### ISSUE THREAD

**Issue by seisdr** [soimort/translate-shell#269]
./trans :en+ar hi
fribidi: invalid screen width `0'
Try `fribidi --help' for more information.
fribidi: invalid screen width `-4'
Try `fribidi --help' for more information.

**Comment by soimort** [comment]
Can you post the output of `trans -V` on your system?

**Comment by seisdr** [comment]
`^C
$ ./trans -V
Translate Shell       0.9.6.8-release

platform              Linux
gawk (GNU Awk)        4.2.1
fribidi (GNU FriBidi) 1.0.5
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
$`

**Comment by soimort** [comment]
You may try setting the screen width manually and see if that works:

```
$ ./trans -w 40 :ar hi
```

**Comment by seisdr** [comment]
Yep it do but not like previous the words not in the left

**Comment by seisdr** [comment]
'` function initBiDi() {
FriBidi = detectProgram("fribidi", "--version", 1)
BiDiNoPad = FriBidi ? "fribidi --nopad" : "rev" SUPERR
BiDi = FriBidi ? "fribidi --width %s" :
"rev" SUPERR "| sed \"s/'/\\\\\\'/\" | xargs printf '%%s '"
} `'

**Comment by seisdr** [comment]
--width %s

**Comment by seisdr** [comment]
always gots problems when I reinstall termux ;(

**Comment by soimort** [comment]
In case you're on Termux you have to install the ncurses-utils package, something like

```
$ pkg install ncurses-utils
```

In order to print right-to-left languages like Arabic on the terminal, `trans` calls the command `tput` to determine its screen width, which is provided by ncurses-utils.

You may also hardcode the preferred screen width in your config file, e.g., 80, so that each line will start at position 80, and continues to the left:

```
{
 ...
 :width 80
}
```
