### ISSUE TITLE
It works only sudo

### ISSUE THREAD

**Issue by Jacobtey** [soimort/translate-shell#275]
Manjaro Linux. It was installed 0.9.6.5 before. Everything works fine with the command 'translate-shell'. After 0.9.6.6 until now a new command 'trans' works only with _sudo_
Executing the script by user results with the following lines:
Usage: trans { -D | -E }
         -D == German to English
         -E == English to German
What should I do?

**Comment by soimort** [comment]
I don't know how you installed `trans`, but given the message you just provided, that is not the official translate-shell here.
