### ISSUE TITLE
Why is the cpu so high?

### ISSUE THREAD

**Issue by Whosc** [soimort/translate-shell#276]
![image](https://user-images.githubusercontent.com/16221204/50747312-251ef880-126e-11e9-848b-f0f01e7bfca2.png)

**Comment by soimort** [comment]
Please attach the command you used, and the output of `trans -V`.

**Comment by Whosc** [comment]
The command : trans -s 'en' -t 'fr' -b -x proxy 'some text' 

![image](https://user-images.githubusercontent.com/16221204/50814229-eb282200-1353-11e9-8b18-4ca2b859a8e0.png)

**Comment by soimort** [comment]
Normally a single command should finish in a few seconds, and the gawk process is gone.

I see that you are trying to translate words such as "Buffer Capacity" "RFID Reader" and "With signal attenuation" with quite different gawk processes. Those are **not** just one command. It is possible that you are using some automated script that makes use of trans and massively propagates processes.

Please kill all such processes, and see if you can reproduce the issue in one single `trans` command.
