### ISSUE TITLE
ru locale is not detected

### ISSUE THREAD

**Issue by danpla** [soimort/translate-shell#280]
The issue seems to be similar to #179. My system locale is also `ru_RU.UTF-8`, but `trans` detects `emj` (Emoji) instead of `ru` .

    trans -b "Hello, world!"
    Hello, world!

    trans -b :ru "Hello, world!"
    Привет, мир!

```
trans -V
Translate Shell       0.9.6.9-release

platform              Linux
gawk (GNU Awk)        4.0.1
fribidi (GNU FriBidi) [NOT INSTALLED]
audio player          mplayer
terminal pager        less
terminal type         xterm
user locale           ru:en (Emoji)
home language         emj
source language       auto
target language       emj
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]
```
````
locale
LANG=ru_RU.UTF-8
LANGUAGE=ru:en
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=
````

**Comment by soimort** [comment]
`trans` prefers `LANGUAGE` over `LANG`. But why is your `LANGUAGE=ru:en`?

It seems that the environment variable was messed up at some point, probably when you wanted to call `trans ru:en` but accidentally set that parameter to `LANGUAGE`. Please try cleaning it up first:

```
$ export LANGUAGE=
```

**Comment by danpla** [comment]
`LANGUAGE` is a priority list of languages for gettext:

* [Specifying a Priority List of Languages](https://www.gnu.org/software/gettext/manual/html_node/The-LANGUAGE-variable.html#The-LANGUAGE-variable)
* [The LANGUAGE priority list](https://help.ubuntu.com/community/EnvironmentVariables#The_LANGUAGE_priority_list)

`ru:en` is a perfectly valid value, since Russian is a primary interface language on my system.

Yes, cleaning the variable up solves the problem. But if `trans` prefers `LANGUAGE` ([like gettext](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html#Locale-Environment-Variables)), why it ignores its value?

**Comment by soimort** [comment]
Apologies for not having thought of this carefully through; `trans` does not parse colon-separated values in such variables (yet).

As `trans` is a command-line program, it might make more sense to prefer `LANG` or `LC_CTYPE`, but not `LANGUAGE`. This will be fixed soon. Thanks for the info.
