### ISSUE TITLE
Translate -shell usage on Mac OS

### ISSUE THREAD

**Issue by IM-Ming** [soimort/translate-shell#282]
Translate -shell Mac OS terminal input trans command: parameter input error! For example, I typed "ls|trans en:zh "hello" in the terminal and it printed blank lines! Need to restart the computer to solve! Sometimes it can't be solved! This is what reason! Can solve?

**Comment by soimort** [comment]
Please follow https://github.com/soimort/translate-shell/blob/develop/CONTRIBUTING.md#how-to-report-an-issue when reporting an issue.
