### ISSUE TITLE
Translate -shell usage on Mac OS

### ISSUE THREAD

**Issue by IM-Ming** [soimort/translate-shell#283]
Translate -shell Mac OS terminal input trans command: parameter input error! For example, I typed "ls|trans en:zh "hello" in the terminal and it printed blank lines! Then type the correct command: ls| trans-no-auto -b :zh still displays blank lines! Need to restart the computer to solve! Sometimes it can't be solved! This is what reason! Can solve?

Translate Shell       0.9.6.9

platform              Darwin
gawk (GNU Awk)        4.2.1
fribidi (GNU FriBidi) 1.0.5
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

**Comment by soimort** [comment]
Your IP address is possibly blocked by Google's servers. This usually happens when you're using a proxy, or you abuse the service beyond their quota.
