### ISSUE TITLE
Shorthand for specifying languages

### ISSUE THREAD

**Issue by forthrin** [soimort/translate-shell#284]
I propose a short form for specifying languages, ie. rather than `trans -s fr -t en bonjour`, one of:

    trans fr en bonjour
    trans fr-en bonjour
    trans -fr -en bonjour

Obviously this may raise conflicts, eg. when you want to translate the word "en" itself. I have ideas of how to resolve this, but I'd first like to hear from the developer on the idea of this kind of shorthand.

**Comment by soimort** [comment]
The first and the third forms are quite confusing to me, especially when it comes to using source/target code alone. Say someone enters a command:

```
$ trans en de
```

Should  it just translate from English to German (while reading from standard input), or should it translate the word "de" into English? Or should it translate two words "en" and "de" (which are both real words in Spanish)?

Of course it's always possible to resolve the conflict by the `--` separator, but it only leads to surprising behaviors. For example, one might wonder why `trans in` will translate the word "in" into his preferred language, but `trans en` only recognizes "en" as the language code for English and `trans -- en` is necessary to achieve the same result. Way too counter-intuitive.

After all, none of your suggestions is even shorter than `trans fr:en bonjour` in length.

**Comment by forthrin** [comment]
Uh-oh... I was so exhilarated after discovering this utility that I didn't notice you actually have a shorthand already: `fr:en`! Sorry about that :) Thanks for a great tool which I will use a lot!
