### ISSUE TITLE
warning: regexp escape sequence `\"' is not a known regexp operator

### ISSUE THREAD

**Issue by lacygoill** [soimort/translate-shell#285]
- `$ gawk -V`:

        GNU Awk 4.2.62, API: 2.0 (GNU MPFR 3.1.4, GNU MP 6.1.0)

 - `$ trans -V`:

        gawk: /dev/fd/63:176: warning: regexp escape sequence `\"' is not a known regexp operator
        Translate Shell       0.9.6.4-git:84eaf66

        platform              Linux
        gawk (GNU Awk)        4.2.62
        fribidi (GNU FriBidi) [NOT INSTALLED]
        audio player          mpv
        terminal pager        less
        terminal type         tmux-256color
        user locale           en_US (English)
        home language         en
        source language       auto
        target language       en
        translation engine    google
        proxy                 [NONE]
        user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
        theme                 default
        init file             [NONE]

        Report bugs to:       https://github.com/soimort/translate-shell/issues

When I run any `$ trans` command, such as:

    $ trans -V

Or:

    $ trans 'Saluton, Mondo!'

The output begins with the following warning from gawk:

    gawk: /dev/fd/63:176: warning: regexp escape sequence `\"' is not a known regexp operator

It seems to be due to [this commit](https://git.savannah.gnu.org/cgit/gawk.git/commit/?id=3ddc932b0a808a4f5f55519ccf1d65f6caa41666) in the gawk codebase.

**Comment by soimort** [comment]
Thanks for the report.

`0.9.6.4` was a quite outdated version of translate-shell; a lot of code might have changed since then. Can you please confirm if the warning persists with the newest version `0.9.6.9`?

**Comment by lacygoill** [comment]
Yes, I think the issue is still present in `0.9.6.9`. I've just re-installed the latest version I could find from github, and the output of `trans -V` still begins with a warning:

    $ trans -V
    gawk: /dev/fd/63:177: warning: regexp escape sequence `\"' is not a known regexp operator
    Translate Shell       0.9.6.9-git:b13772d

    platform              Linux
    gawk (GNU Awk)        4.2.62
    fribidi (GNU FriBidi) 0.19.7
    audio player          mpv --no-config
    terminal pager        less
    terminal type         tmux-256color
    user locale           en_US.UTF-8 (English)
    home language         en
    source language       auto
    target language       en
    translation engine    google
    proxy                 [NONE]
    user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
    theme                 default
    init file             [NONE]

    Report bugs to:       https://github.com/soimort/translate-shell/issues

**Comment by soimort** [comment]
Thanks. Now I can reproduce it under the latest git build of `gawk`, too.

**Comment by zouhair** [comment]
Now that gawk version 5.0.0 is out the same problem happens again, as gawk change the regex routines now using GNULIB's ones. 

https://lists.gnu.org/archive/html/info-gnu/2019-04/msg00002.html

**Comment by forthrin** [comment]
Happens on macOS/Homebrew too with version 0.9.6.9 and gawk 5.0.0.

**Comment by rsmnarts** [comment]
same problem

**Comment by zouhair** [comment]
Last version fixed it.

https://github.com/soimort/translate-shell/releases/tag/v0.9.6.10

**Comment by ky0n** [comment]
i get this error with trans version 0.9.6.9 and gawk version 5.0.1
