### ISSUE TITLE
-bash: trans: The command was not found

### ISSUE THREAD

**Issue by VimWei** [soimort/translate-shell#286]
I've followed readme.md to install Translate Shell in Windows (through Cygwin)
All the dependencies and recommended dependencies have installed.
And install
```
$ wget git.io/trans
$ chmod +x ./trans
```
But `$ trans vorto` not working, and prompt the following error  "the command was not found": 
```
-bash: trans: 未找到命令
```
What can I do?

![](https://i.bmp.ovh/imgs/2019/03/9d8044ff5168db1e.png)

**Comment by VimWei** [comment]
Is this right?
```
$ mv trans /usr/bin/
```

**Comment by soimort** [comment]
You need to put the executable file `trans` into one of the directory in your `$PATH`. Yes, something like `mv 
trans /usr/bin/` should work.
