### ISSUE TITLE
Error  null response

### ISSUE THREAD

**Issue by SmoosQ** [soimort/translate-shell#289]
it seems I got a little problem in here, when I start to translate, it started to show like this
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(

[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(

installed version:

Translate Shell       0.9.6.9-git:9fd90e9

platform              Darwin
terminal type         xterm-256color
bi-di emulator        [N/A]
gawk (GNU Awk)        4.2.1
fribidi (GNU FriBidi) 1.0.5
audio player          mplayer
terminal pager        less
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
ip version            [DEFAULT]
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues

**Comment by soimort** [comment]
You've exceeded the quota.

https://github.com/soimort/translate-shell/wiki/FAQ#i-got-an-empty-output-should-i-report-an-issue-to-you

**Comment by SmoosQ** [comment]
thanks, fast response!!!

**Comment by SmoosQ** [comment]
emmmm, I tried again, it shows the same
`$ trans :fr kinetics
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(`
