### ISSUE TITLE
gawk syntax error?

### ISSUE THREAD

**Issue by isomorphisms** [soimort/translate-shell#291]
on mac OS I’ve tried building `translate-shell` several different ways (including git.io/trans) and keep getting this error.

```
gawk: syntax error at source line 116 in function escapeChar source file /dev/fd/63
 context is
 switch (char) >>>  { <<<
   gawk: illegal startingatement at source line 117 in function escapeChar source file /dev/fd/63
   gawk: illegal statement at source line 117 in function escapeChar source file /dev/fd/63
   24 missing ]'s
   7 missing )'source
```

I think I’ve `brew ` re`install`ed everything possible……   and iirc the tool used to work on this computer.

**Comment by soimort** [comment]
1. What is your `gawk` version?
2. Please git clone this repository, run `make`, and check if
```
$ build/trans -V
```
works. If not, verify that its md5sum is `10dd03cc1336df3d60bf0ce9e2cbae73`.

**Comment by soimort** [comment]
@isomorphisms Any follow-ups?

**Comment by soimort** [comment]
Please feel free to provide any further information on this if reproducible.
