### ISSUE TITLE
Please add to the brew package manager

### ISSUE THREAD

**Issue by vitaly-zdanevich** [soimort/translate-shell#292]

**Comment by soimort** [comment]
It's already there. 
https://formulae.brew.sh/formula/translate-shell

**Comment by vitaly-zdanevich** [comment]
But this is not mentioned in the README.md.

**Comment by soimort** [comment]
It's in the wiki page "Distros"; the section [Using your favorite package manager](https://github.com/soimort/translate-shell#using-your-favorite-package-manager) has a link to it.
