### ISSUE TITLE
Don't require quotes for sentences

### ISSUE THREAD

**Issue by forthrin** [soimort/translate-shell#294]
As of now, you have to use double quotes to translate a sentence:

    trans "All my troubles seemed so far away"

It would be better if we could skip the double quotes:

    trans All my troubles seemed so far away

So far, I've never once used the command line for batch-translating multiple words, ie.

    trans Horse Cow Mouse Lion

I suspect this is an edge use case, and that the far common use case is translating phrases.

Translating a list of words could be invoked by a command line switch, or those who want it (if anyone) could easily write a one-line shell wrapper for this.

**Comment by soimort** [comment]
By design, each command-line argument corresponds to a complete set of text to be translated. This default behavior will not be changed.

You may easily write your own shell wrapper, if the alternative behavior suits your use case the best. Or I can add a switch to enable automatic concatenation of multiple arguments.

**Comment by forthrin** [comment]
The latter would be nice. Then people can just do `alias trans='trans --option'` if they want that behaviour by default.

**Comment by soimort** [comment]
Now you can use the option `-j` (shorthand for `-join-sentence`) to achieve the expected result.

```
$ trans -j -b :fr All my troubles seemed so far away
Tous mes ennuis semblaient si loin
```

**Comment by soimort** [comment]
Alternatively, add the following line

```clj
 :join-sentence    true
```

to the [configuration file](https://github.com/soimort/translate-shell/wiki/Configuration). This will change the default behavior permanently.

**Comment by forthrin** [comment]
Just love this feature. A small detail, but punching in a phrase on the command line is just so much more convenient now that you don't have to think about the quote characters. Thanks a lot!

**Comment by VladimirSinitsin** [comment]
Hi,
I spent hours trying to write an alias that can pass all arguments as a double-quoted string, but I never could. Only now I decided to check issues with a similar problem. Thank you very much, it all works. I'm happy! Regards.
