### ISSUE TITLE
Ignoring characters and numbers

### ISSUE THREAD

**Issue by jonjow** [soimort/translate-shell#296]
Hello,

I am currently using the bing engine and it is messing with my numbers. Is it possible to ignore parts of the message?

$ trans :de --brief "Hello <@525363044948115456> and good morning <@420007334107152406> and go back to work <@367294461426008068>" 
Hallo < @ 525363644456 > und guten Morgen < @ 420007334107152406 > und gehen zurück zur Arbeit < @ 367294461426008868 > 

$ trans :fr --brief "Hello <@525363044948115456> and good morning <@420007334107152406> and go back to work <@367294461426008068>" 

Bonjour < @ 525363044948115456 > et bon matin < @ 420007334107152406 > et revenir au travail < @ 367294461426008068 >

**Comment by soimort** [comment]
`trans` is a faithful interface of translation services; it has no knowledge of the semantics of sentences itself. So this is actually an issue of Bing Translator (or similarly, Google Translate).

See #75 for a similar request and discussion.
