### ISSUE TITLE
Compatibility with gawk-5

### ISSUE THREAD

**Issue by ferki** [soimort/translate-shell#297]
When using [the recently been released gawk-5.0.0](https://lists.gnu.org/archive/html/info-gnu/2019-04/msg00002.html), the test suite seems to fail when asserting gawk version to match `^4.` (as reported for example in [Gentoo bug 684048](https://bugs.gentoo.org/684048)).

A quick and simple check of functionality with gawk-5.0.0 installed seems to indicate everything is still OK (at least with using Google translate). The test also passes except for the `GawkVersion` test mentioned above.

I'm opening this issue to learn how it is best to go forward in this regard. Would you prefer updating the test suite to also allow gawk-5, or would it be best to keep the dependency tied to gawk-4 on the packaging side?

**Comment by soimort** [comment]
Thanks for the report. They haven't packaged gawk 5.0.0 for Arch yet, so the test suite still ran fine on my side so far.

Except for #285, it seems gawk 5 is [mostly backward compatible](http://lists.gnu.org/archive/html/info-gnu/2019-04/msg00002.html) with its version 4. But I think I'll give it a try for a few extra days to make sure it breaks nothing. Then I'll mark it as gawk 5-ready.

```
        assertTrue(GawkVersion ~ "^(4|5).")
```
