### ISSUE TITLE
Cannot get audio from bing

### ISSUE THREAD

**Issue by wmhtet** [soimort/translate-shell#299]
trans -e bing -show-languages n -download-audio-as=canton.wav :yue "Hello, How are you?" -debug
 16 bytes > HTTP/1.1 200 OK
 23 bytes > Cache-Control: private
 23 bytes > Content-Length: 157394
 39 bytes > Content-Type: text/html; charset=utf-8
 22 bytes > Vary: Accept-Encoding
 62 bytes > P3P: CP="NON UNI COM NAV STA LOC CURa DEVa PSAa PSDa OUR IND"
 93 bytes > Set-Cookie: SRCHD=AF=NOFORM; domain=.bing.com; expires=Fri, 30-Apr-2021 02:54:24 GMT; path=/
 136 bytes > Set-Cookie: SRCHUID=V=2&GUID=9BF6503D9F554C90BACD09A577F423E6&dmnchg=1; domain=.bing.com; expires=Fri, 30-Apr-2021 02:54:24 GMT; path=/
 98 bytes > Set-Cookie: SRCHUSR=DOB=20190430; domain=.bing.com; expires=Fri, 30-Apr-2021 02:54:24 GMT; path=/
 79 bytes > Set-Cookie: _SS=SID=3FC5B7B8263E6D5F34E9BAF627EA6C54; domain=.bing.com; path=/
 101 bytes > X-MSEdge-Ref: Ref A: 09EEA52F416745AF9EFB7EA439638FE8 Ref B: SGEEDGE0111 Ref C: 2019-04-30T02:54:24Z
 96 bytes > Set-Cookie: _EDGE_S=F=1&SID=3FC5B7B8263E6D5F34E9BAF627EA6C54; path=/; httponly; domain=bing.com
 96 bytes > Set-Cookie: _EDGE_V=1; path=/; httponly; expires=Sun, 24-May-2020 02:54:24 GMT; domain=bing.com
 114 bytes > Set-Cookie: MUID=34A8EF3761946A733D53E27960406B7A; path=/; expires=Sun, 24-May-2020 02:54:24 GMT; domain=bing.com
 108 bytes > Set-Cookie: MUIDB=34A8EF3761946A733D53E27960406B7A; path=/; httponly; expires=Sun, 24-May-2020 02:54:24 GMT
 36 bytes > Date: Tue, 30 Apr 2019 02:54:24 GMT                                  
 18 bytes > Connection: close
 23 bytes > HTTP/1.1 403 Forbidden
 24 bytes > Cache-Control: no-cache
 17 bytes > Pragma: no-cache
 19 bytes > Content-Length: 58
 46 bytes > Content-Type: application/json; charset=utf-8
 12 bytes > Expires: -1
 77 bytes > Set-Cookie: mtstkn=; expires=Mon, 29 Apr 2019 02:54:25 GMT; path=/translator
 81 bytes > Set-Cookie: mtstkn=; expires=Mon, 29 Apr 2019 02:54:25 GMT; path=/translator/api
 60 bytes > X-MS-Trans-Info: 10951.3b19c0f8-cbee-43b8-8af6-dd739371c3f1
 28 bytes > X-AspNet-Version: 4.0.30319
 22 bytes > X-Powered-By: ASP.NET
 101 bytes > X-MSEdge-Ref: Ref A: F05DF7CCE19C41ACA557CE4CCB0DC2F6 Ref B: SGEEDGE0116 Ref C: 2019-04-30T02:54:25Z
 36 bytes > Date: Tue, 30 Apr 2019 02:54:24 GMT
 18 bytes > Connection: close
 1 bytes >
 58 bytes > {"message":"Service unavailable. Please try again later."}
 content = '''
 {"message":"Service unavailable. Please try again later."}
 ''' 
 tokens = ["{", "\"message\"", ":", "\"Service unavailable. Please try again later.\"", "}"]
 ast = {
 "0,message"     "\"Service unavailable. Please try again later.\""
 }
 -- display original text
 Hello, How are you?
 -- display major translation

**Comment by wmhtet** [comment]
it generates invalid audio file(ts/mpeg/...) of 1 byte.

**Comment by soimort** [comment]
It's not just the audio. It seems the Bing translator is not working on your side at all.

1. What is your `trans -V`?
2. Is your IP address located in China? (if so this might be related to #225)

**Comment by wmhtet** [comment]
Ok.

1 - 
 trans -V
 Translate Shell       0.9.6.6
 platform              Linux
 gawk (GNU Awk)        4.1.4
 fribidi (GNU FriBidi) 0.19.7
 audio player          [NOT INSTALLED]
 terminal pager        less
 terminal type         xterm-256color
 user locale           C.UTF-8 (English)
 home language         en
 source language       auto
 target language       en
 translation engine    google
 proxy                 [NONE]
 user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
 theme                 default
 init file             [NONE]
 Report bugs to:       https://github.com/soimort/translate-shell/issues

2- 
My IP is-not-supposed to be from China.... Sadly, I won't know for sure and I cannot guarantee. The ISP here is using the Chinese infrastructure ....

**Comment by soimort** [comment]
> Translate Shell 0.9.6.6

Clearly you're using a very outdated version of translate-shell.

Back in Mar 17, 2018, [0.9.6.7](https://github.com/soimort/translate-shell/releases/tag/v0.9.6.7) fixed exactly [this issue](218) about Bing.

**Comment by wmhtet** [comment]
Ok. It is just that Ubuntu has that version as a latest

  sudo apt-get upgrade translate-shell
  Reading package lists... Done
  Building dependency tree
  Reading state information... Done
  translate-shell is already the newest version (0.9.6.6-1).
  Calculating upgrade... Done
  0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

I have checked it on Brew and it is 0.9.6.9 and yes, the issue is solved and I can get the audio. Thanks a lot for such an awesome app. Keep up the goodwork!!!
