### ISSUE TITLE
[ERROR] errors with "sh trans" command with cygwin

### ISSUE THREAD

**Issue by LightSunChen** [soimort/translate-shell#303]
I got these errors with "sh trans" command with cygwin :

/usr/bin/trans: trans: line 5630: syntax error near unexpected token `('      
  
/usr/bin/trans: trans: line 5630: `gawk -f <(echo -E "$TRANS_PROGRAM") - "$@"'

**Comment by soimort** [comment]
You need to run it through `bash`, not `sh`.
