### ISSUE TITLE
[enhancement] download audio for multiple sentences in bulk

### ISSUE THREAD

**Issue by omega3** [soimort/translate-shell#309]
Please, can you add option to download audio for multiple sentences in bulk? I mean for each sentence separate audio file?

Let's say I have csv or other file format with database of many sentences - every sentence in one line. Would it be possible?

2. Would it be possible to create filename automatically for each sentence ? For example:
In csv it its possible to separate columns by tabs, so:
I would create Filenames for each sentence (each line) and would it be possible for the program to use it? For example 
0001 (tab) Why not test this thing
0002 (tab) What's today date?

and the output would be:
0001.mp3
0002.mp3

I use program called Anki to learn English and I would like to create audio for my English database. 

Bulk translation into my native as output.csv separated by tabs with each sentence in new line would also be welcomed, but I can do it in other way (manually in web browser).

That would be extremely useful for Anki users and other flashcards / spaced repetition programs. 

I tried:

```
trans -e bing -download-audio-as 01.mp3 -sp -n m,GB "Creeps in this petty pace from day to day,
> > To the last syllable of recorded time;
> > And all our yesterdays have lighted fools
> > The way to dusty death."

```

But it puts all audio into single mp3 file.  And it outputs sentences translations separated by: `\n> ` but this can be converted to csv manually.

**Comment by soimort** [comment]
This is something you have to implement on your own, I'm afraid. Bulk downloading can get oneself easily banned by Google, and that's not a feature that I'm planning to add to `trans`. Sorry.
