### ISSUE TITLE
Firewall port

### ISSUE THREAD

**Issue by WangLinAndy** [soimort/translate-shell#313]
Hello. Is there any way to directly test whether the connection is connected? Now the firewall is closed. I don't know which port to open to ensure successful translation.

**Comment by Vascom** [comment]
There is no need to open any port for outgoing connection.

**Comment by WangLinAndy** [comment]
> 无需为传出连接打开任何端口。

At present, what I am experiencing is that the firewall is open. Now the translation returns empty, and the firewall is closed to translate the result.

**Comment by soimort** [comment]
Sorry, I don't understand what your question is about. `trans` uses the standard port of HTTP which is 80.

Should any problem arise, please refer to the documentation of your firewall.
