### ISSUE TITLE
gawk: build.awk:5: @include "include/Commons.awk"

### ISSUE THREAD

**Issue by ruoyuzsj** [soimort/translate-shell#314]
gawk: build.awk:5: @include "include/Commons.awk"
gawk: build.awk:5: ^ invalid char '@' in expression
make: *** [build] Error 1

**Comment by soimort** [comment]
Please describe your issue in more details. When did it happen? What is your gawk version / OS?

**Comment by soimort** [comment]
Should this happen again, please follow https://github.com/soimort/translate-shell/blob/develop/CONTRIBUTING.md and report another issue with the needed information.
