### ISSUE TITLE
Cut translate requests before reaching (Google's) maximum length

### ISSUE THREAD

**Issue by chazanov** [soimort/translate-shell#315]
As widely known translation services – especially Google – deny further service beyond a certain character limit.

It would be great if translate-shell could automatically cut at this limit.

I don't have numbers, but I'm quite sure that the recent change https://github.com/soimort/translate-shell/issues/312 also reduced Google's limit.

**Comment by soimort** [comment]
Honestly I doubt if there could be any hardcoded "number" of characters before Google shuts down its free service and keeps yelling 403 at users. While translating 20 chars every minute seems perfectly ok, translating the same amount of chars every decisecond would certainly be not. 

I'm not Google, so I can't tell you to what extent Google Translate can tolerate such abusive requests. So sorry, I can't implement this feature.

If you're writing a script to use `trans` programmatically, then it should be quite simple for you to estimate and implement this limit on your own. I'm not going to enforce any restriction here.

On #312 (or precisely, commit d3f9251): This only matters if the UTF8-encoded GET request exceeds the maximum length of technically permissible requests. If it's one single big request, Google server will just stop consuming beyond a certain limit. There's really no reason to cut down a request a priori. The scenario that can get one blocked by Google servers (for, like, 24 hours) largely depends on the **frequency of recurring requests**, but that limit does not seem static / consistent, and definitely not easy to figure out.
