### ISSUE TITLE
odd characters

### ISSUE THREAD

**Issue by TunnelThruTime** [soimort/translate-shell#325]
translator displays odd characters when translating Japanese to English  

trans ja:en こい人
ããäºº

ã “ã„ äºº

Translations of ããäºº
[ 日本語 -> English ]

ããäºº
    ã “ã„ äºº, ã ã äºº

**Comment by soimort** [comment]
Please read [How to Report an Issue](https://github.com/soimort/translate-shell/blob/stable/CONTRIBUTING.md#how-to-report-an-issue) and make sure you're using the latest  version.

This particular issue is already fixed in 0.9.6.11.
