### ISSUE TITLE
Wrong detecting language

### ISSUE THREAD

**Issue by KeHuang1** [soimort/translate-shell#326]
sudo apt-get translate-shell

trans -id 工作
Norsk
Name                  Norwegian
Family                Indo-European
Writing system        Latin
Code                  no
ISO 639-3             nor

trans  工作
å·¥ä½
to · ¥ ½
Translations of å·¥ä½
[ Norsk -> English ]

trans zh-CN:en 工作
å·¥ä½
å·¥ä1⁄2œ
Translations of å·¥ä½
[ 简体中文 -> English ]

trans -id vær
English
Name                  English
Family                Indo-European
Writing system        Latin

trans -V
Translate Shell       0.9.6.6

platform              Linux
gawk (GNU Awk)        4.1.4
fribidi (GNU FriBidi) 0.19.7
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         xterm-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

Thanks you!

**Comment by KeHuang1** [comment]
And it knows short format of Chinese PinYing but not characters. 
~$ trans zh: we
Showing translation for:  (use -no-auto to disable autocorrect)
巍峨
(Wéi'é)
巍峨
Translations of 巍峨
[ 简体中文 -> English ]
巍峨
    巍峨, Towering

**Comment by soimort** [comment]
Please update to the latest version (0.9.6.11).
(#310, #312, #320, #321, #325)

**Comment by soimort** [comment]
> And it knows short format of Chinese PinYing but not characters.
> ~$ trans zh: we
> Showing translation for: (use -no-auto to disable autocorrect)
> 巍峨
> (Wéi'é)
> 巍峨
> Translations of 巍峨
> [ 简体中文 -> English ]
> 巍峨
> 巍峨, Towering

This just produces the same result as Google Translate (https://translate.google.com). Not really an issue on my part, I'm afraid to say.

![2019-09-27-105823_1920x1200_scrot](https://user-images.githubusercontent.com/342945/65756663-d07e1f00-e115-11e9-848f-7c868915b85d.png)
