### ISSUE TITLE
FEATURE REQUEST: GUI

### ISSUE THREAD

**Issue by xpheres** [soimort/translate-shell#328]
it would be really nice to add a GUI to this program and I would like to suggest gooey for it: https://github.com/chriskiehl/Gooey#how-does-it-work

**Comment by soimort** [comment]
Thanks for the suggestion.

The goal of this project is about making a command-line interface for Google Translate, so something like a GUI would be out of scope. Furthermore, Gooey is for Python, but this is not a Python project.
