### ISSUE TITLE
wrong output: ÐÐ¾Ðµ Ð¿ÑÐµÐ´Ð»Ð¾Ð¶ÐµÐ½Ð¸Ðµ

### ISSUE THREAD

**Issue by OlegShevtsov1** [soimort/translate-shell#329]
```
$ trans -shell ru:en
Translate Shell
(:q to quit)
Русский> Мое предложение
ÐÐ¾Ðµ Ð¿ÑÐµÐ´Ð»Ð¾Ð¶ÐµÐ½Ð¸Ðµ

REMAINS

Translations of ÐÐ¾Ðµ Ð¿ÑÐµÐ´Ð»Ð¾Ð¶ÐµÐ½Ð¸Ðµ
[ Русский -> English ]

ÐÐ¾Ðµ Ð¿ÑÐµÐ´Ð»Ð¾Ð¶ÐµÐ½Ð¸Ðµ
    REMAINS, Ð Ð¾Ðμ Ð¿Ñ ÐμÐ'Ð »Ð¾Ð¶ÐμÐ½Ð¸Ðμ

Русский> 
```
I read this page 
https://github.com/soimort/translate-shell/wiki/Writing-Systems-and-Fonts
### In case you see any small boxes ▯ ("tofu character") in the Sample column, you are missing corresponding fonts for that writing system. Please refer to the Unicode Fonts section below.

To solve this i tried install package console-cyrillic
```
sudo apt install console-cyrillic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  libunicode-string-perl
The following NEW packages will be installed:
  console-cyrillic
0 upgraded, 1 newly installed, 0 to remove and 20 not upgraded.
Need to get 108 kB of archives.
```

Ubuntu 18.04 LTS
How I can solve this mistake?

**Comment by soimort** [comment]
Hi,

This is a known issue (#310) already fixed by d3f9251. Please update your translate-shell to the latest version (0.9.6.11).
