### ISSUE TITLE
gawk: cmd. line:181: fatal: attempt to use scalar parameter `array' as an array

### ISSUE THREAD

**Issue by tillea** [soimort/translate-shell#33]
Hi,

I hope you will be able to reproduce the following

$ trans es:de salir
gawk: cmd. line:181: fatal: attempt to use scalar parameter `array' as an array

If not, please contact me for further information.

Please peing me via mail if you might issue a new release to make sure I'll create a Debian package from it.

Kind regards

```
    Andreas.
```

**Comment by soimort** [comment]
This is indeed a bug. Thanks for the good catch!
