### ISSUE TITLE
sh: /inet/tcp/0/socks5/: No such file or directory

### ISSUE THREAD

**Issue by ghost** [soimort/translate-shell#331]
I set `HTTP_PROXY` and got this:

```
➜  ~ trans blabla
sh: /inet/tcp/0/socks5/: No such file or directory
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```

I've read the FAQ and I'm convinced it's not caused by network issues. Because commands below  works fine.

- `trans blabla` (without `HTTP_PROXY`)
- `proxychains trans blabla` (proxy settings in `proxychains.conf` is same as `HTTP_PROXY`)
- `curl translate.googleapis.com` (with the same `HTTP_PROXY`)

I searched the error message `sh: /inet/tcp/0/socks5/: No such file or directory` but didn't find anything useful.

## System Information

- OS: `Arch Linux x86_64`
- Shell: `fish 3.0.2`(same output in `zsh 5.7.1` and `bash 5.0.011-2`)
- `translate-shell 0.9.6.11-1`
- `gawk 5.0.1-2`

**Comment by soimort** [comment]
What kind of HTTP proxies are you using? translate-shell does not support SOCKS5 proxy by itself, so even if it works perfectly with `proxychains`, simply assigning a SOCKS proxy as `HTTP_PROXY` will not work as expected.

Note that `curl` does not take the uppercase environment variable `HTTP_PROXY` (https://ec.haxx.se/usingcurl/usingcurl-proxies) by default. Please try with `http_proxy` to make sure that the HTTP proxy really works.

**Comment by ghost** [comment]
I'm using a SOCKS5 proxy, so that's the cause. Thanks for your time.
