### ISSUE TITLE
Problem when sending chinese characters in input

### ISSUE THREAD

**Issue by Ziltosh** [soimort/translate-shell#337]
Hello,

First of all, thank you for this great tool. 
However I have a problem with the Chinese translation, but only in the Chinese > Latin language direction.

Example:
```
trans en:zh-CN -b -e google "Brian is in the kitchen."
布莱恩在厨房里。
```
No problem here, but if I try the reverse translation (with copy/paste):
```
trans zh-CN:en -b -e google "布莱恩在厨房里。"
å¸ƒèŽ ± æ © åœ¨åŽ¨æˆ¿ é ‡ Œã € ‚
```

Do you have an idea ?

Thank you.

**Comment by soimort** [comment]
Hi,

This is a known issue (#310) already fixed by d3f9251. Please update your translate-shell to the latest version (0.9.6.11).
