### ISSUE TITLE
Returns empty string

### ISSUE THREAD

**Issue by joeyhub** [soimort/translate-shell#343]
After translating a few dozen strings it very quickly stops working returning only an empty line. Is there some rate limit it's failing to detect?

**Comment by joeyhub** [comment]
Our systems have detected unusual traffic from your computer network.  Please try your request again later.

**Comment by soimort** [comment]
Yes.

https://github.com/soimort/translate-shell/wiki/FAQ#i-got-an-empty-output-should-i-report-an-issue-to-you
