### ISSUE TITLE
empty

### ISSUE THREAD

**Issue by lakelord** [soimort/translate-shell#346]
I am experiencing no output at all from translate-shell
I installed from github.
I am using Linuxmint 19.3 MATE

^[[1mTranslate Shell       0.9.6.11-git:a915583

^[[22mplatform              Linux
terminal type         xterm-256color
bi-di emulator        [N/A]
gawk (GNU Awk)        4.1.4
fribidi (GNU FriBidi) 0.19.7
audio player          mpv --no-config
terminal pager        less
web browser           xdg-open
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
ip version            [DEFAULT]
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues

**Comment by soimort** [comment]
Please include the command you used.  https://github.com/soimort/translate-shell/blob/develop/CONTRIBUTING.md#how-to-report-an-issue
