### ISSUE TITLE
empty output

### ISSUE THREAD

**Issue by lakelord** [soimort/translate-shell#347]
I am experiencing no output at all from translate-shell

for example: 

trans :fr dejeuner

returns empty 

I installed from github.
I am using Linuxmint 19.3 MATE

trans - V
^[[1mTranslate Shell 0.9.6.11-git:a915583

^[[22mplatform Linux
terminal type xterm-256color
bi-di emulator [N/A]
gawk (GNU Awk) 4.1.4
fribidi (GNU FriBidi) 0.19.7
audio player mpv --no-config
terminal pager less
web browser xdg-open
user locale en_US.UTF-8 (English)
home language en
source language auto
target language en
translation engine google
proxy [NONE]
user-agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
ip version [DEFAULT]
theme default
init file [NONE]

**Comment by soimort** [comment]
1. Can you access https://translate.google.com from your web browser?
2. What is the output of `trans -D fr: dejeuner`?

**Comment by lakelord** [comment]
Yes I can access translate.google.com
it is 'lunch'

**Comment by soimort** [comment]
> What is the output of trans -D fr: dejeuner?
> it is 'lunch'

Then you already got a nonempty output.
