### ISSUE TITLE
The garbled words when Chinese translated into English

### ISSUE THREAD

**Issue by cs-moushuai** [soimort/translate-shell#358]
![Screen Capture_select-area_20200725124313](https://user-images.githubusercontent.com/60532551/88448891-e6af5580-ce74-11ea-82c0-2a4af7310d31.png)
And my Linux distribution is deepin 20 Beta.
![Screen Capture_select-area_20200725124913](https://user-images.githubusercontent.com/60532551/88448927-5b828f80-ce75-11ea-9416-2b8443106e04.png)

**Comment by soimort** [comment]
#310

If the issue persists after upgrading, please provide the full output of `trans -V`.
