### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by brookskindle** [soimort/translate-shell#362]
I wanted to express my appreciation for this project. I'm learning Italian and was searching for a way to translate words / small sentences to/from Italian without constantly having a browser tab open for Google translate. I always have at least one terminal open when I'm on the computer, so having a command line tool that does what I need is awesome, and fits perfectly into my workflow.

`trans it: 'Grazie mille!' -b -p`

**Comment by soimort** [comment]
:smile:  `trans it: 'Prego!' -sp`
