### ISSUE TITLE
can't use a url as a input

### ISSUE THREAD

**Issue by PeopleComeAndGo** [soimort/translate-shell#363]
trans :fr http://www.w3.org/, it doesn't work.
shows the message below:
sh: 1: https://translate.google.com/translate?hl=en&sl=auto&tl=fr&u=http://www.w3.org/: not found

**Comment by soimort** [comment]
Please post the output of `trans -V`.

**Comment by soimort** [comment]
can't reproduce -- please feel free to comment if there's more information to share.
