### ISSUE TITLE
How to get translation that uses the alphabet for some languages that support them

### ISSUE THREAD

**Issue by seededplyr** [soimort/translate-shell#366]
Example is the English to Tamil language translation in Google Translate: [(link)](https://translate.google.com/#view=home&op=translate&sl=en&tl=ta&text=a%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog)
_Input:_
`a quick brown fox jumped over the lazy dog`

_Output:_
`ஒரு விரைவான பழுப்பு நரி சோம்பேறி நாய் மீது குதித்தது`

_Output: (small print)_
`Oru viraivāṉa paḻuppu nari cōmpēṟi nāy mītu kutittatu`

Is there presently anyway of getting the small print from translate-shell and if not are there any plans to implement such a feature?

**Comment by soimort** [comment]
By default, `trans :ta 'A quick brown fox jumped over the lazy dog'` should already print the translation in both forms. (and you can use something like `sed -n '4p'` to filter out the line)

**Comment by seededplyr** [comment]
> 
> 
> By default, `trans :ta 'A quick brown fox jumped over the lazy dog'` should already print the translation in both forms. (and you can use something like `sed -n '4p'` to filter out the line)

indeed it does, thank you for your quick reply, turns out i was turning on brief mode with meaning to because i didnt know thats what -b was, thanks again for pointing me in the right direction.
