### ISSUE TITLE
empty output problem

### ISSUE THREAD

**Issue by gauloran** [soimort/translate-shell#371]
I tried this solution https://github.com/soimort/translate-shell/issues/127  but it didn't help me 

trans -version
Translate Shell       0.9.6.12-git:04102e0

platform              Linux
terminal type         xterm-256color
bi-di emulator        [N/A]
gawk (GNU Awk)        5.0.1
fribidi (GNU FriBidi) [NOT INSTALLED]
audio player          mpg123
terminal pager        less
web browser           xdg-open
user locale           tr_TR.utf8 (Turkish)
home language         tr
source language       auto
target language       tr
translation engine    google

 and btw I am not blocked by google because I can connect google translation service and my network is just fine. Please I am addicted to translate-shell and I should fix this issue.

**Comment by soimort** [comment]
Please post the output of `trans -debug 'hello world'`.

**Comment by gauloran** [comment]
I don't know how but my problem is solved. But I'm very afraid of having the same problem again.

my trans -debug 'hello world' output is:
 16 bytes > HTTP/1.1 200 OK
  46 bytes > Content-Type: application/json; charset=utf-8
  32 bytes > X-Content-Type-Options: nosniff
  31 bytes > Access-Control-Allow-Origin: *
  62 bytes > Cache-Control: no-cache, no-store, max-age=0, must-revalidate
  17 bytes > Pragma: no-cache
  39 bytes > Expires: Mon, 01 Jan 1990 00:00:00 GMT
  36 bytes > Date: Sat, 19 Sep 2020 19:59:56 GMT
  80 bytes > Content-Disposition: attachment; filename="json.txt"; filename*=UTF-8''json.txt
  43 bytes > Cross-Origin-Resource-Policy: cross-origin
 192 bytes > Content-Security-Policy: script-src 'report-sample' 'nonce-k5T5nJAkhJNP3QU/yHHeEQ' 'unsafe-inline';object-src 'none';base-uri 'self';report-uri /_/TranslateApiHttp/cspreport;worker-src 'self'
  12 bytes > Server: ESF
  20 bytes > X-XSS-Protection: 0
  28 bytes > X-Frame-Options: SAMEORIGIN
  20 bytes > Accept-Ranges: none
  69 bytes > Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
  18 bytes > Connection: close
  27 bytes > Transfer-Encoding: chunked
   1 bytes > 
   4 bytes > 12b
  43 bytes > [[["Selam Dünya","hello world",null,null,1]
   1 bytes > ]
  74 bytes > ,null,"en",null,null,[["hello world",null,[["Selam Dünya",1000,true,false]
  31 bytes > ,["merhaba dünya",0,true,false]
   1 bytes > ]
   8 bytes > ,[[0,11]
   1 bytes > ]
  19 bytes > ,"hello world",0,0]
   1 bytes > ]
  13 bytes > ,0.8180167,[]
   8 bytes > ,[["en"]
  17 bytes > ,null,[0.8180167]
   7 bytes > ,["en"]
   1 bytes > ]
  54 bytes > ,null,null,null,null,null,null,null,null,null,[null,2]
   1 bytes > ]
   1 bytes > 
   2 bytes > 0
   1 bytes > 
content = '''
12b                                                                                       
[[["Selam Dünya","hello world",null,null,1]                                               
]                                                                                         
,null,"en",null,null,[["hello world",null,[["Selam Dünya",1000,true,false]                
,["merhaba dünya",0,true,false]                                                           
]                                                                                         
,[[0,11]                                                                                  
]                                                                                         
,"hello world",0,0]                                                                       
]                                                                                         
,0.8180167,[]                                                                             
,[["en"]                                                                                  
,null,[0.8180167]                                                                         
,["en"]                                                                                   
]                                                                                         
,null,null,null,null,null,null,null,null,null,[null,2]                                    
]                                                                                         
                                                                                          
0                                                                                         
                                                                                          
'''                                                                                       
tokens = ["12", "b", "[", "[", "[", "\"Selam Dünya\"", ",", "\"hello world\"", ",", "null", ",", "null", ",", "1", "]", "]", ",", "null", ",", "\"en\"", ",", "null", ",", "null", ",", "[", "[", "\"hello world\"", ",", "null", ",", "[", "[", "\"Selam Dünya\"", ",", "1000", ",", "true", ",", "false", "]", ",", "[", "\"merhaba dünya\"", ",", "0", ",", "true", ",", "false", "]", "]", ",", "[", "[", "0", ",", "11", "]", "]", ",", "\"hello world\"", ",", "0", ",", "0", "]", "]", ",", "0.8180167", ",", "[", "]", ",", "[", "[", "\"en\"", "]", ",", "null", ",", "[", "0.8180167", "]", ",", "[", "\"en\"", "]", "]", ",", "null", ",", "null", ",", "null", ",", "null", ",", "null", ",", "null", ",", "null", ",", "null", ",", "null", ",", "[", "null", ",", "2", "]", "]", "0"]                                       
ast = {
"0,0,0,0"       "\"Selam Dünya\""                                                         
"0,0,0,1"       "\"hello world\""                                                         
"0,0,0,2"       "null"                                                                    
"0,0,0,3"       "null"                                                                    
"0,0,0,4"       "1"                                                                       
"0,1"   "null"                                                                            
"0,2"   "\"en\""                                                                          
"0,3"   "null"                                                                            
"0,4"   "null"                                                                            
"0,5,0,0"       "\"hello world\""                                                         
"0,5,0,1"       "null"                                                                    
"0,5,0,2,0,0"   "\"Selam Dünya\""                                                         
"0,5,0,2,0,1"   "1000"                                                                    
"0,5,0,2,0,2"   "true"                                                                    
"0,5,0,2,0,3"   "false"                                                                   
"0,5,0,2,1,0"   "\"merhaba dünya\""                                                       
"0,5,0,2,1,1"   "0"                                                                       
"0,5,0,2,1,2"   "true"                                                                    
"0,5,0,2,1,3"   "false"                                                                   
"0,5,0,3,0,0"   "0"                                                                       
"0,5,0,3,0,1"   "11"                                                                      
"0,5,0,4"       "\"hello world\""                                                         
"0,5,0,5"       "0"                                                                       
"0,5,0,6"       "0"                                                                       
"0,6"   "0.8180167"                                                                       
"0,8,0,0"       "\"en\""                                                                  
"0,8,1" "null"                                                                            
"0,8,2,0"       "0.8180167"                                                               
"0,8,3,0"       "\"en\""                                                                  
"0,9"   "null"                                                                            
"0,10"  "null"                                                                            
"0,11"  "null"                                                                            
"0,12"  "null"                                                                            
"0,13"  "null"                                                                            
"0,14"  "null"                                                                            
"0,15"  "null"                                                                            
"0,16"  "null"                                                                            
"0,17"  "null"                                                                            
"0,18,0"        "null"                                                                    
"0,18,1"        "2"                                                                       
"0"     "0"                                                                               
}                                                                                         
-- display original text & phonetics
hello world

-- display major translation & phonetics
Selam Dünya

-- display prompt message (Translations of ...)
hello world çevirileri
-- display source language -> target language
[ English -> Türkçe ]

-- display alternative translations
hello world
    Selam Dünya, merhaba dünya

**Comment by soimort** [comment]
Closing for now - If the same problem happens again, you're welcome to post more information here.
