### ISSUE TITLE
 Oops! Something went wrong and I can't translate it for you

### ISSUE THREAD

**Issue by rmGFW** [soimort/translate-shell#375]
cmd : `trans` 
then In interactive mode ，type some words 

output as follow:
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(

expect:
the correct translation

the trans -V output 

```txt
Translate Shell       0.9.6.12-release

platform              Darwin
terminal type         xterm-256color
bi-di emulator        [N/A]
gawk (GNU Awk)        5.1.0
fribidi (GNU FriBidi) 1.0.9
audio player          [NOT INSTALLED]
terminal pager        less
web browser           open
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
ip version            [DEFAULT]
theme                 default
init file             [NONE]
```

**Comment by soimort** [comment]
Please post the output of `trans -debug test`.

**Comment by rmGFW** [comment]
> Please

trans -debug test
[ERROR] Null response.
content = '''

'''
tokens =
ast =
[ERROR] Oops! Something went wrong and I can't translate it for you :(

**Comment by soimort** [comment]
That means either your network setting is problematic, or you cannot access google at all (because of a firewall, etc.)

What is the output of `curl -I translate.googleapis.com`?

**Comment by rmGFW** [comment]
> That means either your network setting is problematic, or you cannot access google at all (because of a firewall, etc.)
> 
> What is the output of `curl -I translate.googleapis.com`?

this is the output
 curl -I translate.googleapis.com
HTTP/1.1 404 Not Found
Date: Thu, 29 Oct 2020 15:12:43 GMT
Content-Type: text/html; charset=UTF-8
Server: ESF
Content-Length: 1561
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff

but I tried this command on another machine , it get same response (404)
but the script work well on the another machine

**Comment by soimort** [comment]
What's the output of `trans -debug test /bing`?

**Comment by soimort** [comment]
> but the script work well on the another machine

Well, if that is the case, then most likely your current IP is banned by Google Translate.
