### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by dmiraj** [soimort/translate-shell#377]
Translation to arabic shows the arabic letter sequence in reverse.
Latin-languages syntax is written from left to right. Arabic syntax is written from right to left.
When trying to translate from a latin-language(english, french, spanish...) The translation in arabic come up with a writing from left to right.

**Comment by soimort** [comment]
Please provide the output of your `trans -V`.

In order to output right-to-left languages correctly on the screen it is required to install FriBidi. See [Recommended Dependencies](https://github.com/soimort/translate-shell#recommended-dependencies).

**Comment by dmiraj** [comment]
Hello thank you for the fast feedback. Here is the output of my `trans -V`:
```
Translate Shell       0.9.6.11

platform              Linux
terminal type         screen.xterm-256color
bi-di emulator        [N/A]
gawk (GNU Awk)        5.0.1
fribidi (GNU FriBidi) 1.0.8
audio player          mpv --no-config
terminal pager        less
web browser           xdg-open
user locale           en_CA.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
ip version            [DEFAULT]
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
```
I have downloaded the latest version (0.9.6.12) of the software from `https://www.soimort.org/translate-shell/trans` the same issue is persistent, when running `./trans :ar "hello"` and `./trans :ar -bidi "hello"`.
I have checked, and yes I have the `libfribidi-bin` library installed.
Thank you :smile_cat: 

Edit: Lol, I haven't realized the wrong output. Just updated it.

**Comment by soimort** [comment]
What terminal emulator are you using?

(better if you could also post a screenshot for demonstration of the issue here)

**Comment by soimort** [comment]
This issue should be related to #288, which was fixed for at least some types of terminal emulators. You can try the `-no-bidi` option if the default `-bidi` doesn't work.

Closing since I can't investigate any further without information about the terminal emulator.
