### ISSUE TITLE
bit strange when tranlate chinese to english

### ISSUE THREAD

**Issue by apuppy** [soimort/translate-shell#388]
![image](https://user-images.githubusercontent.com/6140347/105703507-4da6e780-5f48-11eb-9e69-c8fa09c023e9.png)

**Comment by apuppy** [comment]
Seems that hexdump have no options --version and --help.

**Comment by soimort** [comment]
And what's the output of `trans -V`?

Make sure that you're using the latest version (0.9.6.12) of translate-shell.

https://github.com/soimort/translate-shell/blob/stable/CONTRIBUTING.md#how-to-report-an-issue

**Comment by apuppy** [comment]
Here is the command `trans -V` output bellow:
![image](https://user-images.githubusercontent.com/6140347/105708805-e42ad700-5f4f-11eb-99ef-d849ef9b5170.png)

**Comment by apuppy** [comment]
I purged the package which I installed by Debian command `apt install translate-shell`. And then clone it from git, make and make install. Finally, it works correctly.
![image](https://user-images.githubusercontent.com/6140347/105709756-1db01200-5f51-11eb-931a-c02bec2c3e7f.png)

Thank you, man.

**Comment by soimort** [comment]
Nice to see it works.

(Yes, packages from Debian's official repository are sometimes very *out of date*...)

**Comment by osiris** [comment]
In _Debian Trixie_ install `hexdump` with `apt install bsdextrautils`
