### ISSUE TITLE
en:zh-CN translation got markdown syntax characters converted/deleted

### ISSUE THREAD

**Issue by tjyang** [soimort/translate-shell#393]
WHAT:
  * Command line
  ```
trans file://./en/rocky/8/guides/ssh_public_private_keys.md   en:zh-CN  
  ``` 
  * Expect trans with an argument to NOT translating  markdown syntax characters into target language.
  *  Also not to delete space character after "*".
  *  Please see example in screenshot below.

![image](https://user-images.githubusercontent.com/378638/110777456-c0350380-8226-11eb-9abd-b75708d3534b.png)

**Comment by soimort** [comment]
Does https://translate.google.com show the same result?

**Comment by tjyang** [comment]
Yes, you are correct. Not translate's issue.

* text below
```
# Rocky Linux - SSH Public and Private Key

## Prerequisites

* A certain amount of comfort operating from the command line
* Rocky Linux servers and/or workstations with *openssh* installed
* Okay technically, this process whould work on any Linux system with openssh installed
* Optional: familiarity with linux file and directory permissions
```
* Got translated with same issue, space got deleted.
![image](https://user-images.githubusercontent.com/378638/110830186-8bdd3980-825e-11eb-8ddf-aa874de8bbf2.png)
