### ISSUE TITLE
How to get rid of history files in HOME directory

### ISSUE THREAD

**Issue by weilbith** [soimort/translate-shell#395]
I having tons of `.trans_history-<number>.tmp` files in my `$HOME` directory. I actually don't need this history, but if I can't disable it I would rather have it following the xdg-base-dir specification and have it go into `$XDG_DATA_HOME/translate-shell/`. Unfortunately I'm unable to find any hints in regards to the history in this repository. Are there any configuration options for that but are not documented?

**Comment by soimort** [comment]
I think these `.*_history` files are generated by [rlwrap](https://linux.die.net/man/1/rlwrap) (which `trans` invokes when using interactive mode), not by `trans` itself.

You can try setting `RLWRAP_HOME` explicity in `.bashrc` or `.zshrc`:

```
export RLWRAP_HOME=$XDG_DATA_HOME/translate-shell/
```


(Edit: See comment https://github.com/soimort/translate-shell/issues/395#issuecomment-1288415702 below)

**Comment by weilbith** [comment]
Perfect. I made an experiment and it works. Thank you very much for your help! 🙏🏾

**Comment by Vinfall** [comment]
@soimort IMO it's better to suggest people set `RLWRAP_HOME` to its own directory instead, as all `$HOME/.*_history` are generated by rlwrap (https://github.com/hanslub42/rlwrap/issues/25):

```bash
export RLWRAP_HOME="$XDG_DATA_HOME"/rlwrap 
```

People might have `.bash_history`, `.python_history`, `.ssh_history`, `.trans_history`, `.zsh_history` in `$HOME` and all these would go to `$XDG_DATA_HOME/translate-shell/` (by default `$HOME/.local/share/translate-shell/`) in your suggestion.

Also, I think the manual should mention this (possibly in `FILES` section?). Even if `trans` itself does not *created* `.trans_history`, `rlwrap` is still *invoked* by `trans` in interactive mode.

**Comment by soimort** [comment]
Thanks @Vinfall, you're absolutely right.

Will update the manual to clarify that `trans` simply invokes `rlwrap` and users should take care of `RLWRAP_HOME` on their own choice.
