### ISSUE TITLE
Bing is less reliable and more laggy than before

### ISSUE THREAD

**Issue by v1993** [soimort/translate-shell#399]
Have been using this awesome tool (hey, thank you so much!) for a while and now having trouble with it (version 0.9.6.12). Apparently, when using Bing there is a considerable delay and sometimes outright failure:

```
v@v-home:~$ trans -e bing
привет, мир!
<second later>
[WARNING] Connection timed out. Retrying IPv4 connection.
<considerable delay here>
привет, мир!
(privet, mir!)

Hello, peace!

[ Русский -> English ]
```

(and yes, Bing's translation is hilariously wrong, but that's not the point here)

This issue does not happen when using google translate engine. I'm not sure if it's Bing changing things, but sure it is less comfortable than it was before.

**Comment by soimort** [comment]
Having to wait until the connection falls back to IPv4 will always take some extra time. (see #287)

Have you tried to specify IPv4 explicitly (by option `-4`)?
