### ISSUE TITLE
Use Google Text-to-Speech engine to pronounce

### ISSUE THREAD

**Issue by soimort** [soimort/translate-shell#4]
Could be a useful feature.

**Comment by Synchro** [comment]
On OS X you can just pipe it into `say`.

**Comment by soimort** [comment]
haha, thanks for this tip. I wish I could do that on Linux :shipit:

**Comment by nivit** [comment]
On Linux you can pipe to `espeak` [http://espeak.sourceforge.net/](http://espeak.sourceforge.net/)

**Comment by vitaly-zdanevich** [comment]
Bad quality :(
