### ISSUE TITLE
Trans doesn't do anything

### ISSUE THREAD

**Issue by sk8nfool** [soimort/translate-shell#416]
I have a file of directory names that are most likely in Chinese (Google translate of the first claims Simplified Chinese). I have tried both Simplified and Traditional and there is no translation. I've attached both the input and output files. One of the commands I used is

> `trans -show-original y -e bing -s zh-CN -verbose -o eng.txt < dirs.txt`

The output file contains no translations.

The input file: [dirs.txt](https://github.com/soimort/translate-shell/files/6872597/dirs.txt)
The output file: [eng.txt](https://github.com/soimort/translate-shell/files/6872599/eng.txt)

I am running _trans_ on Ubuntu 18.04 after loading it from Ubuntu's repository with

> `sudo apt install translate-shell`

What's wrong?

**Comment by salkin-mada** [comment]
I have a similar experience. 
Was working on a `lua` script using `curl` and `trans`. And the translation was working flawless one minute. The next it returns nothing.
```zsh
❯ trans -b :dk "hello world"


```
... hmm. I wonder if my IP is now blocked somehow?
At some point I was issuing bad cmd's like:
```lua
function T.translate()
    local command = "trans -brief :da \\\""..result.."\\\""
    local handle = io.popen(command)
    translated = handle:read("*a")
    handle:close()
end
```
Should have used `string.format` .. or of-course just `local command = "trans -brief :da '"..result.."'"`
Nevertheless `trans` was working and then I escaped some chars wrongly. The cli was hanging. `Ctrl-c`
After that I have not been able to get `trans` working again.

Even the "try it!" example does not work anymore.
```zsh
❯ gawk -f <(curl -Ls --compressed https://git.io/translate) -- -shell
Translate Shell
(:q to quit)
> hej verden


> hvad sker der?


> nothing


> :q

~ took 19s
❯
```

**Comment by salkin-mada** [comment]
Aha. Something iffy had happened. I left the system on for an hour. Came back and reran the following command in the same terminal.
```zsh
❯ trans -b :fr "hello world"


~
❯ trans -b :fr "hello world"
Bonjour le monde

```

So not sure if this issue/experience is related to @sk8nfool's

**Comment by Apolsus** [comment]
This tool fail to work sometimes.
I have post a similar issue [418](https://github.com/soimort/translate-shell/issues/418)
However it was closed.

**Comment by soimort** [comment]
The OP is about an issue with Bing, whose support is known to be broken at the moment (as observed in #406).

As for the second issue, the empty output is because Google temporarily blocks IP addresses from time to time. In that case you'll need to wait for a few hours until Google unblocks you, or simply change to a different IP address.
