### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by Apolsus** [soimort/translate-shell#418]
The command I input was "trans :en '工作'"

![image](https://user-images.githubusercontent.com/59809602/127763831-f7fc15b6-322a-40f4-87e5-4cdd0d72912b.png)

I used to get the right answer. But recently it doesn't work.

OS: BigSur 11.4

Device: MacBook Pro 2020(Apple chip)

**Comment by soimort** [comment]
Please read https://github.com/soimort/translate-shell/blob/develop/CONTRIBUTING.md and follow the steps.

**Comment by Apolsus** [comment]
The version:
![image](https://user-images.githubusercontent.com/59809602/127853808-4303b422-e326-4bd0-b1ee-aedb5181f399.png)
The result I expect
![image](https://user-images.githubusercontent.com/59809602/127853988-aec592b3-5086-4687-b0fb-9e96e2353512.png)

As you can see， now it works. However, it doesn't work sometimes, for example , in this afternoon( UTC +8:00 ).
