### ISSUE TITLE
Certain Languages create blank output

### ISSUE THREAD

**Issue by brettcol** [soimort/translate-shell#437]
On an install from .deb created a blank line of output. Reinstalled from git and with make and got a 400 error.

Example inputs:
`trans -sl en -tl yue 'hello'`

Github direct ver. Output:
`[ERROR] Google returned an error response. HTTP status code: 400
[ERROR] Other HTTP error`

Version info:
Translate Shell       0.9.6.12-git:d3e0836

platform              Linux
terminal type         xterm-256color
bi-di emulator        [N/A]
gawk (GNU Awk)        4.2.1
fribidi (GNU FriBidi) 1.0.5
audio player          mpv --no-config
terminal pager        less
web browser           xdg-open
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
ip version            [DEFAULT]
theme                 default
init file             [NONE]

**Comment by brettcol** [comment]
Dump ( `trans -sl en -tl yue 'hello' -dump` )

[ERROR] Google returned an error response. HTTP status code: 400
[ERROR] Other HTTP error
695
<html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 400 (Bad Request)!!1</title><style nonce="3HG45VeTeJoRNTLQp/gRMA">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><main id="af-error-container" role="main"><a href=//www.google.com><span id=logo aria-label=Google role=img></span></a><p><b>400.</b> <ins>That’s an error.</ins><p>The server cannot process the request because it is malformed. It should not be retried. <ins>That’s all we know.</ins></main>
0

**Comment by K1ngst0m** [comment]
```bash
trans -e bing -sl en -tl yue 'hello' -dump

{"statusCode":400,"errorMessage":""}
```   
                                                                      
same status code output with bing engine

**Comment by soimort** [comment]
Please use the latest `develop` branch where this issue has been fixed.

**Comment by soimort** [comment]
By the way, Google Translate never supported Cantonese (`yue` as the language code), so the Bing engine had to be invoked explicitly in this case.

**Comment by strogonoff** [comment]
> By the way, Google Translate never supported Cantonese (`yue` as the language code), so the Bing engine had to be invoked explicitly in this case.

It doesn’t work with Bing either, but with a different failure mode (passing e.g. `-e bing en:yue "<common english word>"` returns `<common english word>` verbatim). This is with Docker image pulled today.

**Comment by soimort** [comment]
> > By the way, Google Translate never supported Cantonese (`yue` as the language code), so the Bing engine had to be invoked explicitly in this case.
> 
> It doesn’t work with Bing either, but with a different failure mode (passing e.g. `-e bing en:yue "<common english word>"` returns `<common english word>` verbatim). This is with Docker image pulled today.

Seems that the docker image was a bit outdated. It should work with the latest version (0.9.7.1).

```
$ trans -e bing en:yue "I don't know"
I don't know

我唔知

[ English → 粵語 ]
```
