### ISSUE TITLE
Garbled characters are displayed in Chinese

### ISSUE THREAD

**Issue by JefferyBoy** [soimort/translate-shell#441]
$ trans zh:en “中国”
âä¸u00adåââ€œä¸å›½â€

âä¸u00adåâ 的翻译
[ 简体中文 -> English ]

âä¸u00adåâ
    â€œä¸å›½â€, u200bu200bu200bu200bu200bu200b

How can I solve this problem？ Thanks

**Comment by soimort** [comment]
Update to the latest version.
