### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by UnixCro** [soimort/translate-shell#446]
```
gawk -f <(curl -Ls --compressed https://git.io/translate) -- -shell
```

**Comment by soimort** [comment]
Hi,

If you are asking a question rather than raising an issue, please post in [Discussions](https://github.com/soimort/translate-shell/discussions).

**Comment by UnixCro** [comment]
In the discussion nobody wants to deal with you. Unfortunately, that's the way it is and that's why everyone uses the issue page.

However. Can you please explain the command to me? It is very interesting.
