### ISSUE TITLE
In Shell mode, cannot reset input language to "Detect Automatically" 

### ISSUE THREAD

**Issue by Ao1Pointblank** [soimort/translate-shell#451]
using the shell option with `trans -shell -brief`, i cannot revert back to detecting languages automatically once i select 1 input language manually. 

example (translating a dutch word):
```
nl: aardappel
potato
```
✅ correct translation

then if i want to translate another word from an unknown language, i would have to restart the shell completely or else it would incorrectly keep trying to translate only from NL:

```
:en 土豆
土豆
```
❌ can't translate; is still trying to use dutch as input instead of detecting chinese

**Comment by soimort** [comment]
Thanks for reporting the issue.

I've added a workaround for this. Now it should be possible to use the following command to explicitly set the source language back to `auto`:

```
:set sl auto 
```
