### ISSUE TITLE
only conversion required in output

### ISSUE THREAD

**Issue by helpinghandindia1** [soimort/translate-shell#459]
Hello 
@JoshStrobl @soimort and team.

We are a NGO in India, using trans successfully. We need your support for a small issue.
trans is converting word, it is fine, but we need source word's conversion in English.
pls understand with following example.
trans  -brief hi:en कविता
Poem
and we need output should be - kavita
pls guide.

**Comment by JoshStrobl** [comment]
Spam or why am I being pinged? I am not part of the team.

**Comment by soimort** [comment]
@helpinghandindia1 
There is currently no built-in option to output the transliteration only, but you can pipe it to sed and get what you want. For example:

```
$ trans -no-ansi hi:en कविता | sed '2q;d' | sed 's/^.//;s/.$//'
$ trans -no-ansi mr:en कवितासंतरा | sed '2q;d' | sed 's/^.//;s/.$//'
```
