### ISSUE TITLE
trans does not work on gawk 5.2

### ISSUE THREAD

**Issue by zetatez** [soimort/translate-shell#465]
```bash
trans -e bing en:zh time

# gawk: /dev/fd/63:215: fatal: internal error: file interpret.h, line 254: unexpected parameter type Node_val
```

**Comment by soimort** [comment]
Closing as a duplicate of #463.

**Comment by soimort** [comment]
For now, downgrading to gawk 5.1.1 temporarily fixes this.

I was not able to reproduce #463 but I can reproduce this one on 5.2.0, so they might have separate but related causes. This definitely has something to do with gawk 5.2.

**Comment by soimort** [comment]
See https://github.com/soimort/translate-shell/issues/463#issuecomment-1282271847
