### ISSUE TITLE
translate-shell timing out on Mac Monterey 12.6

### ISSUE THREAD

**Issue by horstmr** [soimort/translate-shell#467]

**Comment by soimort** [comment]
Please read https://github.com/soimort/translate-shell/blob/develop/CONTRIBUTING.md#how-to-report-an-issue and report the details.

**Comment by horstmr** [comment]
found with latest stable version; `trans -v` is not giving any response.
The translated output eventually returns, but after a really long time (some minutes).

**Comment by soimort** [comment]
> found with latest stable version; trans -v is not giving any response.

You should report the output of `trans -V`, not `trans -v`.

**Comment by horstmr** [comment]
Translate Shell       0.9.7

platform              Darwin
terminal type         ansi
bi-di emulator        [N/A]
gawk (GNU Awk)        5.1.0
fribidi (GNU FriBidi) 1.0.12
audio player          [NOT INSTALLED]
terminal pager        less
web browser           open
user locale           pt_BR.UTF-8 (Portuguese (Brazilian))
host language         pt-BR
source language       auto
target language       pt-BR
translation engine    auto
proxy                 [NONE]
user-agent            Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36 Edg/104.0.1293.54
ip version            [DEFAULT]
theme                 default

**Comment by soimort** [comment]
That sounds like a network issue then. Try
```
curl -I http://translate.googleapis.com
```
and see if you get anything.

**Comment by horstmr** [comment]
response:

HTTP/1.1 404 Not Found
Date: Wed, 26 Oct 2022 15:32:59 GMT
Content-Type: text/html; charset=UTF-8
Server: ESF
Content-Length: 1561
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff

**Comment by soimort** [comment]
If you're on an IPv4 network, try to use trans with the `-4` option. Or you can disable IPv6 on your system setting completely.

Mac's IPv6 fallback mechanism is known to cause slowness problems (see #287).

**Comment by horstmr** [comment]
using -4 option did the trick!
many many thanks, I really appreciate!
would you mind if I donate a coffee for you?

**Comment by soimort** [comment]
Good to see it works for you!

Alternatively you can add this line to the [configuration](https://github.com/soimort/translate-shell/wiki/Configuration)
```
 :ip-version 4
```
to avoid adding the `-4` option in every command.

I'm closing this issue as it is solved.
