### ISSUE TITLE
Suddenly not working, no information to check what to do.

### ISSUE THREAD

**Issue by EddieLukeAtmey** [soimort/translate-shell#469]
https://user-images.githubusercontent.com/10751944/198561630-63797092-9910-40a3-a447-a7842c06cb1f.mov

It runs a few commands and then display nothing. I'm not sure what to do.

trans --version
Translate Shell       0.9.6.12

platform              Darwin
terminal type         xterm-256color
bi-di emulator        [N/A]
gawk (GNU Awk)        5.2.0
fribidi (GNU FriBidi) 1.0.11
audio player          [NOT INSTALLED]
terminal pager        less
web browser           open
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
ip version            [DEFAULT]
theme                 default
init file             [NONE]

Maybe because of this? 
curl -I http://translate.googleapis.com

HTTP/1.1 404 Not Found
Date: Fri, 28 Oct 2022 10:04:49 GMT
Content-Type: text/html; charset=UTF-8
Server: ESF
Content-Length: 1561
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff

**Comment by soimort** [comment]
Please check whether you can translate normally from the web browser.

This is most likely because either your IP is temporarily banned by the server, or your IP address is located in a region where Google Translate discontinued their service (for instance, mainland China).

**Comment by EddieLukeAtmey** [comment]
Yes I can do it normally from the web browser. Now it's working again in the terminal. Don't know what happened, no clue at all. I'll close this for the moment.
