### ISSUE TITLE
How to change the default engine?

### ISSUE THREAD

**Issue by LiuZengqiang** [soimort/translate-shell#471]
Because of the network problem the default translate engine google is not available in China.
How to change the default engine without specify the engine by option ``-e``  in translating?

**Comment by soimort** [comment]
See  https://github.com/soimort/translate-shell/wiki/Configuration

**Comment by LiuZengqiang** [comment]
> See https://github.com/soimort/translate-shell/wiki/Configuration

Thank you :)
