### ISSUE TITLE
 Oops! Something went wrong and I can't translate it for you :(

### ISSUE THREAD

**Issue by dingdangky** [soimort/translate-shell#476]
I have the latest version of 0.9.7 installed, but no matter what I type, after a long time, it always returns:
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(

I try the commend "curl -I translate.googleapis.com",the output is as follows.
curl: (28) Failed to connect to translate.googleapis.com port 80 after 75020 ms: Operation timed out

The mac's firewall is off, allowing any connection.And my browser can access google translate website.

**Comment by soimort** [comment]
If you can't reach the server via `curl -I translate.googleapis.com` then it's simply a network problem.

Turn off IPv6 on Mac, and/or try using a proxy (if you live in a place where Google is blocked).
