### ISSUE TITLE
Japanese Translation is nonsense

### ISSUE THREAD

**Issue by KodeToad** [soimort/translate-shell#478]
$ trans ja: おまけのGIFアニメ
ã��ã�¾ã��ã�®GIFã�¢ã��ã�¡
(Ã ã ¾ ã ã ® GIFã ¢ ã ã¡)

What?

Translations of ã��ã�¾ã��ã�®GIFã�¢ã��ã�¡
[ 日本語 -> English ]

ã��ã�¾ã��ã�®GIFã�¢ã��ã�¡
    What?

Actual translation if input to translate.com or google is: Bonus GIF animation

**Comment by soimort** [comment]
Please update to the latest version (0.9.7).

**Comment by KodeToad** [comment]
I sent a message to translate-shell@packages.debian.org

**Comment by soimort** [comment]
I believe Debian Sid already has the latest version: https://packages.debian.org/sid/misc/translate-shell. You just need to add sid to your sources.list.
