### ISSUE TITLE
Options -no-translate and -download-audio-as result in a error

### ISSUE THREAD

**Issue by Driglu4it** [soimort/translate-shell#481]
trans en:ru "test"  -brief -no-translate -download-audio-as trans.mp3
give this error: mv: cannot stat '/translate_tts?ie=UTF-8&client=gtx&tl=en&q=%74%65%73%74': No such file or directory

Early it work.

How can I download original text TTS without translations?

Thanks.

**Comment by soimort** [comment]
Thanks for reporting. It's a regression bug, should be fixed in the `develop` branch now.

**Comment by Driglu4it** [comment]
Thank you for efficiency!
