### ISSUE TITLE
Feature request: -b but showing both languages

### ISSUE THREAD

**Issue by 621625** [soimort/translate-shell#485]
Hi,

I'm BM, a very nice and polite guy.

As it stands, if I use trans :es -b -i inputfile then I get a brief translation of the input from inputfile. 

However I would like to be able to intermix input and output languages.

Current behavior input:

how are you (english)

Current behavior output:

how are you (spanish)

Desired behavior input:

how are you (english)

Desired behavior output:

how are you (english)
how are you (spanish)

I would like to have both languages intermixed sentence by sentence in the output so that it is easier to read when learning the language. Hope you understand, I would like to have a flag for this, if it's not clear, then let me know and I will update again.

**Comment by soimort** [comment]
The `-b` option shows the translation and the translation only; this behavior is expected and will not be changed.

You can achieve this by simply using the verbose mode but hiding other information you don't need:
```
$ trans -show-original-phonetics=0 -show-prompt-message=0 -show-languages=0 -show-original-dictionary=0 -show-dictionary=0 -show-alternatives=0 :es 'how are you' 
how are you

cómo estás
```

You can set these options to `false` in [a configuration file](https://github.com/soimort/translate-shell/wiki/Configuration) if you want it by default.
