### ISSUE TITLE
macOS,为什么输入命令无法启动translate-shell

### ISSUE THREAD

**Issue by cocoyamm** [soimort/translate-shell#488]
![IMG_6166](https://user-images.githubusercontent.com/122199469/226991544-4fb99580-46ba-4fdd-8047-2eed92f57d8c.jpg)
![IMG_6167](https://user-images.githubusercontent.com/122199469/226991560-2ecc4727-4a20-4323-bea5-ef88e111e5b2.jpg)
![IMG_6169](https://user-images.githubusercontent.com/122199469/226994580-425bf0ee-3423-474a-9aa5-96b9bcc2d1a5.JPEG)
![IMG_6168](https://user-images.githubusercontent.com/122199469/226994592-1a36a623-5a7c-4ed7-a0e6-38b09b79a58f.JPEG)

重新安装的时候又显示已经安装成功了，但是无法启动程序。。doesn't work for me

**Comment by soimort** [comment]
Regarding the brew installation, please report your issue to https://github.com/Homebrew/homebrew-core/issues

I do not maintain homebrew and have no knowledge of it.
