### ISSUE TITLE
Support socks proxy

### ISSUE THREAD

**Issue by jiacai2050** [soimort/translate-shell#510]
When search the issues, I sees some problems are caused by not support socks5 proxy,

Since I'm not familiar with the codebase, I wasn't sure if it's hard to add this feature.

**Comment by soimort** [comment]
There is no plan to support SOCKS proxy natively, due to the lack of existing libraries one has to re-implement the SOCKS protocol in gawk, which is beyond the goal of this project.

It's recommended to just use [proxychains](https://github.com/rofl0r/proxychains-ng).
