### ISSUE TITLE
Response time on mac os x

### ISSUE THREAD

**Issue by Cerebellum-ITM** [soimort/translate-shell#520]
I have noticed that when using the trans command the response time is up to 15 or 20s, but I see that this only happens on a mac os x machine. When I use it on my linux servers this does not happen. Does anyone know the reason? I installed the command using brew
<img width="1468" alt="image" src="https://github.com/user-attachments/assets/6756f19e-3187-4369-bad5-540a88e2db6c">

**Comment by soimort** [comment]
Possibly related to #287 -- Try using the `-4` option to enforce IPv4 on Mac, or [disable IPv6](https://support.nordvpn.com/hc/en-us/articles/19924913336081-How-to-disable-IPv6-on-macOS).

**Comment by Cerebellum-ITM** [comment]
Hi, thanks for the reply. Yes, when I use that option, the response is almost immediate. Sorry for repeating a question, I didn't find it when I checked. Maybe it would be a good idea to add it to the readme as a comment for Mac OS X users. Thanks again.
