### ISSUE TITLE
Offline language files?

### ISSUE THREAD

**Issue by tommedema** [soimort/translate-shell#53]
I'd like to do a lot of translating and fear that Google wouldn't allow such traffic.

Therefore I am wondering if it's possible to install the language files locally, such that one doesn't need to access Google's translation service online?

**Comment by soimort** [comment]
Unfortunately no. Google Translate uses its own statistical machine translation engine, which is a proprietary software. Although you can, technically, harvest all its vocabulary data for offline use, those data would be useless without Google's algorithm. I'd like to see an open source machine translator which enables people to translate between over 90 languages, but for now there is really no good alternative.

The suggestion is to use their paid [Translate API](https://cloud.google.com/translate/) instead.

**Comment by soimort** [comment]
On a side note, Google Translate does make use of free/open source Wordnets for some languages (http://translate.google.com/about/intl/en_ALL/license.html). If all you need is a word database, not the whole Google Translate functionality, then they might be useful.
