### ISSUE TITLE
Add HEAD for the Homebrew formula

### ISSUE THREAD

**Issue by zmwangx** [soimort/translate-shell#56]
`gawk 4.1.2` broke 0.8.23 (#55), and the fix hasn't made into a release yet. Therefore, could you please add a `HEAD` to the Homebrew formula so that we may install the latest version without breaking out of `brew`? The formula could be like this: (By the way, latest `develop` doesn't really work on OS X, but that will be the subject of another issue)

``` ruby
require "formula"

class TranslateShell < Formula
  homepage "http://www.soimort.org/translate-shell"
  url "http://www.soimort.org/translate-shell/translate-shell.tar.gz"
  sha1 "f33287a1f0827b215514e2bd82671e03f0d908ce"
  version "0.8.23"

  head "https://github.com/soimort/translate-shell.git", :branch => "develop"

  depends_on 'fribidi' => :optional
  depends_on 'gawk'
  depends_on 'mplayer'
  depends_on 'rlwrap'

  def install
    if build.head?
      system "make"
      bin.install "build/trans"
      man1.install "man/trans.1"
    else
      bin.install "trans"
      man1.install "trans.1"
    end
  end
end
```

**Comment by soimort** [comment]
I might have to create a 0.8 branch and roll out a stable 0.8.24 tomorrow, however 0.9 won't be too far either...
