### ISSUE TITLE
[Configuration] a more common and appropriate path

### ISSUE THREAD

**Issue by chenkaie** [soimort/translate-shell#60]
Are you considering to put `~/.translate-shell/init.trans` under `~/config/translate-shell/` which is a more general and common way of where configuration files are placed (on some Linux distro, e.g., Ubuntu)

Or a prioritize it as below
1. `.trans`
2. `~/config/translate-shell/init.trans`
3. `~/.translate-shell/init.trans`
4. `/etc/translate-shell (not recommended)`

**Comment by soimort** [comment]
I suppose you mean **`.config/`**. It is indeed a convention for many Linux programs, but not a standard. Also it's not widely used on OS X. There are also a great deal of software which don't use this convention at all (to name a few, emacs, vim, wireshark, Telegram, VirtualBox, etc.)

I've added `~/.config/translate-shell` as an alternative path of configuration files.

**Comment by chenkaie** [comment]
Ah.. right, sorry for the typo. And it's actually a well-known convention instead of standard.
Agreed on OS X part, since it's a _new_ convention, IMO it'll somehow become a panic to those well known software, which might affect on lots of system.
However if a newly created software can follow the convention, that would be really appreciated :+1: 
Because my `dotfiles` repo won't require to manually add extra rules to backup new configs :)

Thanks for your commit, I really enjoy this tool.
