### ISSUE TITLE
"Something went wrong" error

### ISSUE THREAD

**Issue by alescode** [soimort/translate-shell#64]
I just installed translate-shell via Homebrew and I'm getting this error every time I'm attempting to translate something.

**Command entered**

```
trans vorto
```

**Actual output**

```
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```

**Output of `trans -V`**

```
Translate Shell       0.9.0.4-release

platform
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) 0.19.6
audio player          mplayer
terminal pager        less
terminal type         xterm-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
```

I wish I could be more helpful, but the error message is not very descriptive. I'm running OS X 10.10.4, and I have all the latest dependencies installed.

**Comment by soimort** [comment]
It's a [network issue](https://github.com/soimort/translate-shell/wiki/FAQ#i-got-an-empty-output-should-i-report-an-issue-to-you) then.

Can you reproduce the error on another network / machine?

**Comment by alescode** [comment]
Not yet, I don't currently have access to another network. Feel free to close this if you're sure it's a network issue, but please consider adding a little more context to the error message (e.g. check your network configuration).

Thanks!

**Comment by soimort** [comment]
Sure. I agree that error message is a bit confusing; surely it's something that can be improved. Thanks for pointing this out.

You may try a 

```
curl -A "" 'http://translate.google.com/translate_a/single?client=t&ie=UTF-8&oe=UTF-8&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&dt=at&q=vorto&sl=auto&tl=en&hl=en'
```

If the above command works for you but `trans` doesn't, please let me know again.

**Comment by alescode** [comment]
The command works, but `trans` doesn't. Here's the output.

```
[[["word","vorto"]],,"eo",,,[["vorto",1,[["word",479,true,false],["the word",134,true,false],["a word",119,true,false]],[[0,5]],"vorto",0,1]],1,,[["eo"],,[1]]]
```

**Comment by soimort** [comment]
This is weird.

What about the debug output?

```
$ trans -debug vorto
```

**Comment by alescode** [comment]
```
content = '''

'''
tokens =
ast =
gawk: /dev/fd/63:42: fatal: attempt to use scalar parameter `array' as an array
```

**Comment by soimort** [comment]
I think I might have a clue now, but not sure if it's the case for you.

```
$ trans -proxy '' -user-agent 'translate-shell' vorto
```

Does this work or not?

**Comment by alescode** [comment]
Nope, same error message :(

**Comment by soimort** [comment]
So, if `curl` does access Google's API correctly, but `trans` gives a null content (an empty line), there must be something wrong with gawk's TCP implementation that I'm not aware of. (a regression of gawk 4.1.3 on OS X? I don't know)

I may not be able to dive into this issue further at the moment (since I cannot reproduce it on my machine), but hopefully I will come up a solution soon.

(one obvious solution: use `curl` as an alternative networking library, instead of gawk's own TCP interface, since `curl` always works better at performing networking tasks)

Thanks for providing these information!

**Comment by alescode** [comment]
Thank you for diving into it! Yes, I have a pretty slow connection and I have noticed that running `curl` gives me output a lot faster than running `trans`.

**Comment by soimort** [comment]
I just made a new release (0.9.0.5) so that the whole HTTP message body may be collected for debugging purpose. Let me know how this goes.

```
$ trans -debug -proxy '' -user-agent 'translate-shell' vorto
```

**Comment by alescode** [comment]
```
  16 bytes > HTTP/1.1 200 OK
  20 bytes > Via: 1.1 GRYFFINDOR
  18 bytes > Connection: close
  24 bytes > Proxy-Connection: close
  27 bytes > Transfer-Encoding: chunked
  39 bytes > Expires: Fri, 01 Jan 1990 00:00:00 GMT
  36 bytes > Date: Fri, 29 May 2015 13:48:25 GMT
  46 bytes > Content-Type: application/json; charset=UTF-8
  30 bytes > Server: HTTP server (unknown)
  17 bytes > Pragma: no-cache
  51 bytes > Cache-Control: no-cache, no-store, must-revalidate
  32 bytes > X-Content-Type-Options: nosniff
  50 bytes > Content-Disposition: attachment; filename="f.txt"
  32 bytes > X-XSS-Protection: 1; mode=block
  32 bytes > Alternate-Protocol: 80:quic,p=0
  20 bytes > Accept-Ranges: none
  22 bytes > Vary: Accept-Encoding
   1 bytes >
   3 bytes > 9f
 160 bytes > [[["word","vorto"]],,"eo",,,[["vorto",1,[["word",479,true,false],["the word",134,true,false],["a word",119,true,false]],[[0,5]],"vorto",0,1]],1,,[["eo"],,[1]]]
   2 bytes > 0
   1 bytes >
[ERROR] Null response.
content = '''

'''
tokens =
ast =
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```

**Comment by soimort** [comment]
I see.
There is a `Via` field in your HTTP response, it seems the gateway/proxy is doing something nasty there: injecting an extra `9f` before the message body and a `0` after it. (I have no idea why it works this way since I'm no expert on networking - maybe someone can explain this to me?)

A clear response should be something like:

```
  16 bytes > HTTP/1.1 200 OK
  36 bytes > Date: Fri, 29 May 2015 15:04:38 GMT
  17 bytes > Pragma: no-cache
  39 bytes > Expires: Fri, 01 Jan 1990 00:00:00 GMT
  51 bytes > Cache-Control: no-cache, no-store, must-revalidate
  46 bytes > Content-Type: application/json; charset=UTF-8
  32 bytes > X-Content-Type-Options: nosniff
  50 bytes > Content-Disposition: attachment; filename="f.txt"
  30 bytes > Server: HTTP server (unknown)
  32 bytes > X-XSS-Protection: 1; mode=block
  32 bytes > Alternate-Protocol: 80:quic,p=0
  20 bytes > Accept-Ranges: none
  22 bytes > Vary: Accept-Encoding
  18 bytes > Connection: close
   1 bytes > 
 159 bytes > [[["word","vorto"]],,"eo",,,[["vorto",1,[["word",479,true,false],["the word",134,true,false],["a word",119,true,false]],[[0,5]],"vorto",0,1]],1,,[["eo"],,[1]]]
```

You may use wireshark to find out what actually happened in your network. However, trans 0.9.0.6 should handle this kind of malformed response now.

(Again, HTTPS is the best solution for this, but `gawk` doesn't come with any SSL/TLS library afaik. Got to move to `curl` someday)

**Comment by alescode** [comment]
Thanks! This was incredibly quick! I'm no expert in networking either, but if you want me to test anything else, let me know. Good luck with the future move to `curl`.

**Comment by soimort** [comment]
Cool. Good to know it works for you now:+1:

**Comment by cjhuang** [comment]
I meet the same problem. I put the following command:
trans -debug -proxy '' -user-agent 'translate-shell' vorto

the output is:
 31 bytes > HTTP/1.1 301 Moved Permanently
  20 bytes > Server: nginx/1.5.3
  36 bytes > Date: Mon, 26 Oct 2015 06:51:28 GMT
  24 bytes > Content-Type: text/html
  20 bytes > Content-Length: 184
  18 bytes > Connection: close
 176 bytes > Location: https://translate.google.com/translate_a/single?client=t&ie=UTF-8&oe=UTF-8&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&dt=at&q=vorto&sl=auto&tl=en&hl=en&tk
   1 bytes > 
   7 bytes > <html>
  50 bytes > <head><title>301 Moved Permanently</title></head>
  23 bytes > <body bgcolor="white">
  48 bytes > <center><h1>301 Moved Permanently</h1></center>
  33 bytes > <hr><center>nginx/1.5.3</center>
   8 bytes > </body>
   8 bytes > </html>
[ERROR] Null response.
content = '''

'''
tokens = 
ast = 
[ERROR] Oops! Something went wrong and I can't translate it for you :(

I see the first is very strange.
The version of the trans is 0.9.0.9

**Comment by offlinehoster** [comment]
Tried this tool today and getting a

text = vorto
tkk = 408183
tk = 469183.70345
  23 bytes > HTTP/1.1 403 Forbidden
  39 bytes > Content-Type: text/html; charset=UTF-8
  32 bytes > X-Content-Type-Options: nosniff
  36 bytes > Date: Mon, 25 Jul 2016 14:41:23 GMT
  30 bytes > Server: HTTP server (unknown)
  21 bytes > Content-Length: 1796
  32 bytes > X-XSS-Protection: 1; mode=block
  18 bytes > Connection: close
   1 bytes > 
  15 bytes > <!DOCTYPE html>
  14 bytes > <html lang=en>
  22 bytes >   <meta charset=utf-8>
  85 bytes >   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  41 bytes >   <title>Error 403 (Forbidden)!!1</title>
   9 bytes >   <style>

**Comment by pixelastic** [comment]
Just tried it with a fresh install from the Ubuntu repo, and here is the error I'm having:

```
$ trans -debug -proxy '' -user-agent 'translate-shell' vorto                                                                        
text = vorto
tkk = 409861
tk = 915614.768410
  23 bytes > HTTP/1.1 403 Forbidden
  39 bytes > Content-Type: text/html; charset=UTF-8
  32 bytes > X-Content-Type-Options: nosniff
  36 bytes > Date: Mon, 03 Oct 2016 12:52:15 GMT
  30 bytes > Server: HTTP server (unknown)
  21 bytes > Content-Length: 1797
  32 bytes > X-XSS-Protection: 1; mode=block
  18 bytes > Connection: close
   1 bytes >
  15 bytes > <!DOCTYPE html>
  14 bytes > <html lang=en>
  22 bytes >   <meta charset=utf-8>
  85 bytes >   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  41 bytes >   <title>Error 403 (Forbidden)!!1</title>
   9 bytes >   <style>
1136 bytes >     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  10 bytes >   </style>
  71 bytes >   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  44 bytes >   <p><b>403.</b> <ins>That’s an error.</ins>
 335 bytes >   <p>Your client does not have permission to get URL <code>/translate_a/single?client=t&amp;ie=UTF-8&amp;oe=UTF-8&amp;dt=bd&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=qca&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;dt=at&amp;sl=auto&amp;tl=en&amp;hl=en&amp;tk=915614.768410&amp;q=vorto</code> from this server.  <ins>That’s all we know.</ins>
[ERROR] Null response.
content = '''

'''
tokens =
ast =
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```

and 

```
$ trans --version
Translate Shell       0.9.2.1

platform              Linux
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) 0.19.7
audio player          mplayer
terminal pager        less
terminal type         screen-256color
user locale           en_US (English)
home language         en
source language       auto
target language       en
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues
```

**Comment by soimort** [comment]
To all who are still seeing the `403 forbidden` issue: please update to **0.9.4**. Any version older than that won't work due to some online translation providers' API change. If you prefer to use a software repo from your Linux distro, kindly ask the downstream maintainer to update the package there.

**Comment by pixelastic** [comment]
I can confirm it works with the latest version from the repo. Thanks.
