### ISSUE TITLE
Install: cannot create regular file ‘/usr/local/share/man/man1/trans.1’: No such file or directory

### ISSUE THREAD

**Issue by nkahe** [soimort/translate-shell#66]
Install from git failed for me because there isn't right directory for manual file by default. After creating directory "/usr/local/share/man/man1/" install was successful. I'm using openSUSE Tumbleweed.

Output:
[~/temp] >git clone https://github.com/soimort/translate-shell
Cloning into 'translate-shell'...
remote: Counting objects: 2518, done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 2518 (delta 23), reused 0 (delta 0), pack-reused 2459
Receiving objects: 100% (2518/2518), 1.53 MiB | 1.12 MiB/s, done.
Resolving deltas: 100% (1512/1512), done.
Checking connectivity... done.
[~/temp/translate-shell] >make
[OK] Task build completed.
[~/temp/translate-shell] >sudo make install
root's password:
cp: cannot create regular file ‘/usr/local/share/man/man1/trans.1’: No such file or directory
Makefile:33: recipe for target 'install' failed
make: **\* [install] Error 1

85-23-29-218:[~] # cd /usr/local/share  
85-23-29-218:/usr/local/share # mkdir man
85-23-29-218:/usr/local/share # cd man
85-23-29-218:/usr/local/share/man # mkdir man1
85-23-29-218:/usr/local/share/man # cd /home/[user]/temp/translate-shell 
85-23-29-218:/home/[user]/temp/translate-shell # make install
[OK] translate-shell installed.

85-23-29-218:/home/[user]/temp/translate-shell # trans -V
Translate Shell       0.9.0.7-git:2eea418

platform              Linux
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) 0.19.6
audio player          mplayer
terminal pager        less
terminal type         xterm
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
proxy                 [NONE]
user-agent            [NONE]
theme                 default
init file             [NONE]

**Comment by soimort** [comment]
should be fixed in the `develop` branch now.

**Comment by XRevan86** [comment]
Could you also use $(DESTDIR)?
