### ISSUE TITLE
translate-shell doesn't work

### ISSUE THREAD

**Issue by conformist-mw** [soimort/translate-shell#67]
./translate :ru you
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(
./translate --version
Translate Shell       0.9.0.7

platform              Linux
gawk (GNU Awk)        4.1.3
fribidi (GNU FriBidi) 0.19.6
audio player          mpv
terminal pager        less
terminal type         xterm
user locale           ru_RU.utf8 (Russian)
home language         ru
source language       auto
target language       ru
proxy                 [NONE]
user-agent            [NONE]
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues

**Comment by moobee** [comment]
Same here :

> Translate Shell       0.9.0.7-release
> 
> platform              Linux
> gawk (GNU Awk)        4.1.1
> fribidi (GNU FriBidi) [NOT INSTALLED]
> audio player          mplayer
> terminal pager        less
> terminal type         xterm
> user locale           fr_FR (French)
> home language         fr
> source language       auto
> target language       fr
> proxy                 [NONE]
> user-agent            [NONE]
> theme                 default
> init file             [NONE]
> 
> Report bugs to:       https://github.com/soimort/translate-shell/issues

**Comment by altonio** [comment]
Me too. What I can do?

**Comment by temach** [comment]
Went down for me as well (on a mac). Maybe google changed the html tags?
running `trans -V`
`
Translate Shell 0.8.22.2

gawk (GNU Awk)        4.1.1
fribidi (GNU FriBidi) 0.19.6
User Language         English (English)
`

**Comment by soimort** [comment]
@temach 0.8.22.2 won't work, it's a **very outdated** version released 8 month ago. Could you please try to reproduce the bug on 0.9.0.7?

Guys, I don't have a clue what went wrong. (It could be a temporary IP block by Google) For now it keeps working on my side.
Please ping me if you can come up with more details.

**Comment by ntgpsta** [comment]
Not working too. 
But <b>works</b> with "User-Agent" option. For example:
trans -u firefox hello 
OR
trans -u chrome hello

---

trans -V

Translate Shell       0.9.1-dev-git:1164473

platform              Linux
gawk (GNU Awk)        4.0.1
fribidi (GNU FriBidi) [NOT INSTALLED]
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         screen
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       ru
proxy                 [NONE]
user-agent            [NONE]
theme                 default
init file             [NONE]

**Comment by moobee** [comment]
Yep, it works :+1:

In the meantime, I made an alias : alias trans="trans -u firefox"

**Comment by XRevan86** [comment]
``` patch
--- a/include/Main.awk
+++ b/include/Main.awk
@@ -44,7 +44,7 @@

     # Networking
     Option["proxy"] = ENVIRON["HTTP_PROXY"] ? ENVIRON["HTTP_PROXY"] : ENVIRON["http_proxy"]
-    Option["user-agent"] = ENVIRON["USER_AGENT"]
+    Option["user-agent"] = ENVIRON["USER_AGENT"] ? ENVIRON["USER_AGENT"] : "Mozilla/5.0"

     # Interactive shell
     Option["no-rlwrap"] = 0
```

**Comment by altonio** [comment]
Thanks @ntgpsta, it works. But, what is "user-agent"?

**Comment by axelhodler** [comment]
works with the user agent option :+1:

**Comment by CoolAller** [comment]
I do not understand what need to correct, please explain. Where to add the lines?

**Comment by conformist-mw** [comment]
@soimort, there is a solution in a comment from @XRevan86

**Comment by casperl** [comment]
Adding this line:  

> alias trans="trans -u firefox" 

to ~/.bashrc worked for me.

Yippeeee! This makes a big difference to my workflow.
