### ISSUE TITLE
error: null response

### ISSUE THREAD

**Issue by tukusejssirs** [soimort/translate-shell#70]
hey there … today I just wanted to use `trans` to translate some word, but it has stopped working ⁧…

```
$ trans en:sk burka
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```

I am sure it use to work perfectly … all the depencences are fulfilled …

**Comment by soimort** [comment]
See #67 for solution.

**Comment by tukusejssirs** [comment]
thank You, it works with user agent :)

**Comment by rikhtehgaran** [comment]
$ trans -u chrome hello 
returned:
```
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```
