### ISSUE TITLE
Null response sinces today

### ISSUE THREAD

**Issue by Napfton** [soimort/translate-shell#71]
Hello

using current Version 
Translate Shell       0.9.0.7-release

platform              Linux
gawk (GNU Awk)        4.1.1
fribidi (GNU FriBidi) [NOT INSTALLED]
audio player          [NOT INSTALLED]
terminal pager        less
terminal type         rxvt-unicode
user locale           de_DE.utf8 (German)
home language         de
source language       auto
target language       de
proxy                 [NONE]
user-agent            [NONE]
theme                 default
init file             [NONE]

since this morning I am getting:

[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(

Is it me or a bug?

**Comment by Jatiba** [comment]
I have the same issue.. Tried on two different systems. (Mac - Brew / Linux - Direct download)

[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(

**Comment by soimort** [comment]
Seems like Google starts to apply browser sniffing generally these days (I
haven't experienced this myself, though).

As suggested in the discussion of #67, please try with a customized user
agent:

```
$ trans -u 'Mozilla/5.0' hello
```

On Thu, Aug 20, 2015 at 10:15 PM, Patrik Bengtsson <notifications@github.com

**Comment by Napfton** [comment]
Seems to be working for me, closing the issue.

Thx mate!
