### ISSUE TITLE
Empty translation

### ISSUE THREAD

**Issue by poliveira89** [soimort/translate-shell#74]
I have installed now the `translate-shell` with `brew`.

When I try to translate from Portuguese to English, this is what happens:

``` bash
$ trans -b pt:en "Eu sou o Paulo"


```

Returns to "empty line". I thought maybe it's related to the source language so I tried:

``` bash
$ trans -b en:es "Hello I'm Paulo"


```

Exactly the same.

**Comment by soimort** [comment]
Duplicate of #67. Please try the latest `develop` branch.

**Comment by poliveira89** [comment]
@soimort how do I install `develop` branch with brew?

**Comment by soimort** [comment]
Unfortunately you can't. However, a new release will be tagged very soon, just to solve this for everyone.

**Comment by poliveira89** [comment]
Great :+1:  I wait patiently for that release. Thanks for the answer :smile:

**Comment by vitaly-zdanevich** [comment]
I faced with empty output too, in interactive shell also. Internet connection is ok.

$ trans -version
Translate Shell       0.9.6.9

```
platform              Darwin
gawk (GNU Awk)        4.2.1
fribidi (GNU FriBidi) 1.0.5
audio player          mpg123
terminal pager        less
terminal type         xterm-256color
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]
```

I faced with that after a few dozens of translations from my bash script, maybe Google banned me, the more I see translations with `-engine yandex`. And looks like no way to use my Google key.
