### ISSUE TITLE
rev: stdin: Invalid or incomplete multibyte or wide character

### ISSUE THREAD

**Issue by tillea** [soimort/translate-shell#76]
Hi,

I wanted to upgrade the Debian package of translate-shell to version 0.9.0.8.  Whatever I call I get

$ trans en:de test
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
test
/test/

Test

Definitions of test
[ English -> Deutsch ]

noun
    (der) Test
        test
    (die) Prüfung
        examination, test, audit, testing, check, exam
...

Any idea how to suppress

   rev: stdin: Invalid or incomplete multibyte or wide character

Everything else seems to work fine.

Kind regards

```
   Andreas.
```

**Comment by soimort** [comment]
1. Please post the output of `trans -V`.
2. This issue seems to be related to your system update, rather than an update of translate-shell itself. Can you reproduce this with an earlier version of `trans`?

**Comment by tillea** [comment]
On Thu, Sep 10, 2015 at 08:20:23AM -0700, Mort Yao wrote:

> 1. Please post the output of `trans -V`.

The following version (as previous Debian package):

$ trans -V de:en test
Translate Shell 0.8.23

gawk (GNU Awk)        4.1.1
fribidi (GNU FriBidi) [NOT INSTALLED]
User Language         German (Deutsch)
$ trans de:en test
test

Übersetzungen für test
(Deutsch ➔ English)
test(test/tested/assay/a review/be tested)

[Substantiv]
    test
        Test, Prüfung, Probe, Versuch, Untersuchung, Kriterium

does not show the problem.  When I simply upgrade the (not
yet uploaded package) I get:

$ trans -V
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
rev: stdin: Invalid or incomplete multibyte or wide character
Translate Shell       0.9.0.8

platform              Linux
gawk (GNU Awk)        4.1.1
fribidi (GNU FriBidi) [NOT INSTALLED]
audio player          mplayer
terminal pager        less
terminal type         xterm
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0
theme                 default
init file             [NONE]

Report bugs to:       https://github.com/soimort/translate-shell/issues

I did not changed anything on my system except installing the new
package I've built.  May be something changed in the install
procedure and I did not proberly crafted the package?

> 1. This issue seems to be related to your system update, rather than an update of translate-shell itself. Can you reproduce this with an earlier version of `trans`?

I do not think so.  But I noticed that you changed the Makefile
from INSTALLDIR to PREFIX and may be I overlooked something in
the packaging.

Kind regards

```
    Andreas.
```

## 

http://fam-tille.de

**Comment by soimort** [comment]
If you think that's a regression bug, then you'll need to use the git version of trans and try to bisect which commit(s) introduced this issue.

**Comment by tillea** [comment]
I did not bisected the Git repository but rather the file
   include/Languages.awk
which looked suspicious when trying

$ recode ..l1 include/Languages.awk
recode: include/Languages.awk failed: Invalid input in step `CHAR..ISO-8859-1'

The following patch is removing the section

  #3 Arabic (Standard Arabic)

which reduces the number of 

rev: stdin: Invalid or incomplete multibyte or wide character

messages by one.  So if you find the problem in the according section
you might possibly also find the other seven problematic language
definitions causing the encoding problems.

Kind regards

```
   Andreas.
```

On Thu, Sep 10, 2015 at 09:28:35AM -0700, Mort Yao wrote:

> If you think that's a regression bug, then you'll need to use the git version of trans and try to bisect which commit(s) introduced this issue.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/soimort/translate-shell/issues/76#issuecomment-139301833

## 

http://fam-tille.de

**Comment by tillea** [comment]
Further hint:  I noticed that there are exactly eight languages marked "rtl".  After removing all these languages the problematic error vanished.

**Comment by tillea** [comment]
It was simply a lack of "libfribidi-bin" in the installation which formerly did not seem to be necessary when not dealing with rtl languages but now is needed in all cases.  I'll bump libfribidi-bin from Suggests to Depends in the Debian package.

**Comment by soimort** [comment]
My guess it that the regression is caused by [323d8b](https://github.com/soimort/translate-shell/commit/323d8b0ff1ce09b21e0102f648c2d7980a24e80a), which forces the use of `rev` in case Fribidi not present.

Can you just do a 

```
$ echo 'ﺔﻴﺑﺮﻌﻟﺍ' | rev
```

on your system? It might be a Debian issue ([#282482](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=282482)), such that the util-linux `rev` doesn't respect the current locale's charset.

**Comment by tillea** [comment]
echo 'עברית' | rev
תירבע

This bug was closed in 2004 and should not affect these days systems.

**Comment by soimort** [comment]
Then I've got no idea why `rev` is having encoding issues in that way. But for sure, adding Fribidi to your deps is a win for everyone. Fribidi handles right-to-left scripts much, much smarter than a literal reverse. For joined-up scripts like Arabic, Fribidi is a must because letter-by-letter `rev` does not give the correct output.
