### ISSUE TITLE
Download audio?

### ISSUE THREAD

**Issue by damaru2** [soimort/translate-shell#77]
How could I, instead of playing the text-to-speech audio with -p or -player option, save the audio in a file?
Is that possible?

**Comment by soimort** [comment]
The easy trick is to play the audio in a web browser, then you can save the stream to a file from there.

```
$ trans -b -player firefox 'lorem ipsum'
```

**Comment by damaru2** [comment]
Oh, I see, thank you!

**Comment by birone** [comment]
This would be very handy - especially if it worked for for input and output languages.

**Comment by iveskins** [comment]
make a script 

``` bash
#!/bin/bash
mplayer -dumpstream -dumpfile `echo $1 | awk -F"=" '{print $NF}'`.mp3 $1
```

and make that your player.
