### ISSUE TITLE
Not working since yesterday

### ISSUE THREAD

**Issue by admirabilis** [soimort/translate-shell#82]
Hello, @soimort!

Since yesterday, I'm getting the following response:

```
$ trans -brief pt:en 'Olá'
[ERROR] Null response.
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```

I thought I should update my translate-shell, but I get the same error with `gawk -f <(curl -Ls git.io/translate) -shell`.

Thank you and best regards!

**Comment by admirabilis** [comment]
Maybe this is similar to a recent problem in the Google Speech API, for which a solution is available at https://stackoverflow.com/questions/9893175/google-text-to-speech-api/31791632#31791632

Basically, a "Referer: http://translate.google.com/" header is now mandatory in the Speech API request.

**Comment by soimort** [comment]
This is not "a recent problem" anymore, everything related to Speech API should be fixed in 0.9.0.8 (so as closing #73). If it still doesn't work for you, then it could be your IP address being blocked by Google. See another discussion #81 on this.

A general tip: please don't abuse Google's API.

**Comment by admirabilis** [comment]
Well, I don't think I'm abusing the service, since I just use it once a day to check some pieces of text before posting, but what is considered as "abuse" is up for Google to decide, so I'll have to check it with another IP to see if it works, thanks!

**Comment by admirabilis** [comment]
I have just checked, and my IP seems to have been blocked indeed. Thank you for your help!
