### ISSUE TITLE
Program very slow?

### ISSUE THREAD

**Issue by emilfihlman** [soimort/translate-shell#84]
Expected: translation appears in less than ~1 second
Actual: translation appears in ~4 seconds

> user@server ~ % time trans -b :fi "Hello world!"
> Hei maailma!
> trans -b :fi "Hello world!"  0.08s user 0.09s system 3% cpu 4.299 total
> user@server ~ %

When I tried this program before (the version before translate-shell) translation took less than half a second.

How can I alleviate this?

**Comment by soimort** [comment]
Since both the user time and sys time are very trivial (0.08s+0.09s compared to 4.299s), most of your time has been spent on TCP transmitting rather than translate-shell itself. Please check your network settings.

**Comment by soimort** [comment]
Can we close this now? It doesn't seem to be a `trans`-related problem. @emilfihlman

**Comment by emilfihlman** [comment]
If no one else is experiencing the problem then it's probably me so why not.

**Comment by tukusejssirs** [comment]
Well, sometimes I experience the problem, too. However, I do not really care about the slowliness, but about the [null response](https://github.com/soimort/translate-shell/issues/83) issue, which makes me open my web browser to translate some piece of text.
