### ISSUE TITLE
rev: stdin: Invalid or incomplete multibyte or wide character

### ISSUE THREAD

**Issue by emilfihlman** [soimort/translate-shell#86]
> user@server:~$ uname -a
> Linux user 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux
> 
> user@server:~$ wget git.io/trans
> //Lots of output
> user@server:~$ chmod +x ./trans
> user@server:~$ ./trans :fi "Hello world!"
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> Hello world!
> 
> Hei maailma!
> 
> Translations of Hello world!
> [ English -> Suomi ]
> 
> Hello world!
>    Hei maailma!, Moikka maailma !
> user@server:~$ ./trans -b :fi "Hello world!"
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> rev: stdin: Invalid or incomplete multibyte or wide character
> Hei maailma!
> user@server:~$

**Comment by soimort** [comment]
It's a known bug #76 (perhaps Debian only?). I suggest installing the [translate-shell](https://packages.debian.org/sid/translate-shell) package from Debian unstable or testing, otherwise, just make sure that you've installed the `libfribidi-bin` package.

**Comment by emilfihlman** [comment]
Thanks! Installing libfribidi-bin fixed it. Should this be mentioned in the dependencies section?

**Comment by soimort** [comment]
I've added this information to the [FAQ](https://github.com/soimort/translate-shell/wiki/FAQ#i-got-an-error-message-like-rev-stdin-invalid-or-incomplete-multibyte-or-wide-character) - Hopefully it helps.
