### ISSUE TITLE
README: why bash/zsh?

### ISSUE THREAD

**Issue by Artoria2e5** [soimort/translate-shell#91]
The README states that the app requires bash/zsh, however the script only reads:

``` sh
#!/bin/sh

cd `dirname $0`
gawk -f translate.awk -- "$@"
```

This is simply POSIX shell language, and should not require any specific shell(s). At least it works with bash, ash (dash, busybox), "bourne” sh (ksh (mksh, ksh88, ksh92, pdksh..)..), zsh and hush.

Please note that for old bourne shells there is an exception with the expansion of `"$@"` when `$1` does not exist: they expand it into an empty string `''` instead of nothing.

**Comment by soimort** [comment]
Thanks for noting.

The [`translate` script for development](https://github.com/soimort/translate-shell/blob/develop/translate) is indeed POSIX compliant. However, the standalone executable we distribute (https://www.soimort.org/translate-shell/trans) is not. It requires [process substitution](https://en.wikipedia.org/wiki/Process_substitution) to do a few tricks.

It is unlikely the case for any real person, who have GNU awk 4.0 installed on their machine, will want to stick with an old-style bourne shell without having GNU bash. Hence, it seems reasonable for me to claim the necessity of bash / zsh. Still, you're free to switch to any antique shell as you like, so long as you have bash in the first place.

**Comment by Artoria2e5** [comment]
Regarding process substitution, I think it comes from ksh92. mksh may also support it too.
